### ISSUE TITLE
Remove warnings

### ISSUE THREAD

**Issue by zTgx** [litentry/litentry-parachain#1003]
Before commit, make sure those command executed and no warnings generated.

- [ ] cargo fmt
- [ ] cargo clippy --workspace
- [ ] cargo test --release --workspace

**Comment by Kailai-Wang** [comment]
I didn't quite understand this issue. 
Do you want to add these checks to the CI? or only keep them locally?

IIRC some of them are already in CI, if not all

**Comment by zTgx** [comment]
This is a suggestion.

Yes, there are some of them in CI already. This issue's title is not very clear maybe. 

There're some compiler warnings in the repo, so I recommend that we can run those commands locally before committing, to make the code clean and avoid committing warnings to the repo.

Or, we can enhance CI if appropriate.

**Comment by Kailai-Wang** [comment]
I think we have the [pre_commit](https://github.com/litentry/tee-worker/blob/dev/.githooks/pre-commit) hook already -- it's just not everyone has installed it.

**Comment by Kailai-Wang** [comment]
but I think some **cargo tests** are indeed not run by default

**Comment by Kailai-Wang** [comment]
Is this issue still valid? @zTgx

**Comment by zTgx** [comment]
> Is this issue still valid? @zTgx

close it.
