### ISSUE TITLE
Add error handling in `stf_task_receiver`

### ISSUE THREAD

**Issue by ziming-zung** [litentry/litentry-parachain#1008]
Currently, if we get an error in `stf_task_receiver`, `stf_task_receiver` will exit, and the tee-worker will no longer be able to enter `stf_task_receiver`. 

We need to add error handling so that `stf_task_receiver` does not panic if an error occurs during processing, and also need to send extrinsic to parachain to let parachain know that an error has occurred

https://github.com/litentry/tee-worker/blob/49061fb037fdbede76041079018ff98c32cf2532/litentry/core/stf-task/receiver/src/stf_task_receiver.rs#L35-L57

**Comment by Kailai-Wang** [comment]
Reopened, as this is not yet fully completed, in the end the errors should be propagated to the parachain and visible to the F/E.

https://github.com/litentry/tee-worker/blob/8a2c6e4f8a13fe065b093d41d4188e477582573a/litentry/core/stf-task/receiver/src/stf_task_receiver.rs#L40
