### ISSUE TITLE
Evaluate the exposure of trusted RPC port in production env

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1010]
In order for privileged users to query the storage via RPC, integritee has built-in support for RPC requests of trusted state. We should evaluate:

- is it safe to keep it open in production env?
- if so, which TrustedGetter should we have?

**Comment by Kailai-Wang** [comment]
The pros and cons are obvious IMO:

++ you get the synchronous responses for your trustedGetter queries - very F/E friendly
--  the worker IP/port gets exposed, attackers might try ddos to bring the service down => maybe we'll have some non-validateer nodes

**Comment by jingleizhang** [comment]
> the worker IP/port gets exposed, attackers might try ddos to bring the service down

We can put an AWS LoadBalance or even an Nginx reverse proxy in front of those workers to protect them.

**Comment by jingleizhang** [comment]
Does TrustedGetter have any auth mechanism? For example, does the user still need to sign a transaction to call the rpc?

**Comment by Kailai-Wang** [comment]
> Does TrustedGetter have any auth mechanism? For example, does the user still need to sign a transaction to call the rpc?

It does. It requires a signature from the user to prove its identity

**Comment by jingleizhang** [comment]
Get it. I think making the trusted RPC port be exposed to F/E is acceptable.

**Comment by Kailai-Wang** [comment]
This is done, we have a decision
