### ISSUE TITLE
move the existed TrustedCommands into async request daemon

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1012]
There are existed TrustedCommands located in stf_sgx_litentry.rs. 
- Move the functionality into request daemon, but keep the origin as an API wrapper. 
- Take care of the error handling inside daemon.

**Comment by Kailai-Wang** [comment]
> Move the functionality into request daemon, but keep the origin as an API wrapper

This should be done in litentry/tee-worker#90 already

All commands that have an enclave signer origin should send extrinsics directly to parachain => they are under `base_cli/commands/litentry`
All commands that don't have a parentchain extrinsic associated can be tested using a root origin => they are under `trusted_base_cli/commands/litentry`

**Comment by Kailai-Wang** [comment]
can you confirm this? @BillyWooo

**Comment by BillyWooo** [comment]
irrelevant any more.
