### ISSUE TITLE
Investigate public information retrieval of enclave

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1019]
For the purpose of verifiability we need to check:

- which information should we make public? (e.g. TEE's shielding key, MRENCLAVE, shard-Id, attestation report?)
- and how? Ideally, all the information should be queriable on parachain

A written document is beneficial

**Comment by Kailai-Wang** [comment]
This might be related to https://docs.integritee.network/5-nodes-and-infrastructure/5.3-how-to-deploy (i.e.if we want to do the RA ourselves and register the information on chain - using Attesteer? or simply use Integritee's service?)

It would need a careful and thorough research

**Comment by Kailai-Wang** [comment]
As mentioned, this is an open topic that should include the following aspects:
- what's the process of remote attestation? Ideally with code example and report example => let's have a sharing session among TEE devs
- which information in the report do we actually need to make public? We don't exclude the option for the users to get the full report, but we want to make some information explicitly verifiable to improve the user's experience. Probably this needs to be aligned with the fields in VC design by @jingleizhang 
- how can we publicise that information on chain?
- what about other information: shielding key, MRENCLAVE, shard...? Do we need a new pallet to register and store such information, or do we reuse/extend the teerex pallet?

Then we can start coding.

**Comment by zTgx** [comment]
Maybe we (tee-worker) should support quote sign types (linkable and unlinkable) both. and here is the difference between linkable and unlinkable quote types,  https://api.portal.trustedservices.intel.com/EPID-attestation.
Let's make it configurable which type we use when running the service, for example, use the `linkable` flag under the `run` command to specific `linkable quote`, or without it we use `unlinkable quote` instead.

```shell
./integritee-service run --linkable 
```

**Comment by zTgx** [comment]
> Maybe we (tee-worker) should support quote sign types (linkable and unlinkable) both. and here is the difference between linkable and unlinkable quote types, https://api.portal.trustedservices.intel.com/EPID-attestation. Let's make it configurable which type we use when running the service, for example, use the `linkable` flag under the `run` command to specific `linkable quote`, or without it we use `unlinkable quote` instead.
> 
> ```shell
> ./integritee-service run --linkable 
> ```

 relevant [pr](https://github.com/litentry/litentry-parachain/pull/1042)

**Comment by jingleizhang** [comment]
The investigate is completed. Close this issue.

**Comment by jingleizhang** [comment]
Since the PR https://github.com/litentry/litentry-parachain/pull/1115 is merged, should we close this issue? @Kailai-Wang @zTgx

**Comment by BillyWooo** [comment]
> Since the PR #1115 is merged, should we close this issue? @Kailai-Wang @zTgx



> As mentioned, this is an open topic that should include the following aspects:
> 
> * what's the process of remote attestation? Ideally with code example and report example => let's have a sharing session among TEE devs
> * which information in the report do we actually need to make public? We don't exclude the option for the users to get the full report, but we want to make some information explicitly verifiable to improve the user's experience. Probably this needs to be aligned with the fields in VC design by @jingleizhang
> * how can we publicise that information on chain?
> * what about other information: shielding key, MRENCLAVE, shard...? Do we need a new pallet to register and store such information, or do we reuse/extend the teerex pallet?
> 
> Then we can start coding.

Do all these bullets covered by PR #1115  or somewhere?

**Comment by Kailai-Wang** [comment]
It doesn't. @zTgx is working on it right now
