### ISSUE TITLE
Some CI tests randomly fail

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1020]
It's been a while since we had this problem, a few out of 9 integration tests sometimes fail randomly and we need to rerun the failed job from time to time.  E.g.:
https://github.com/litentry/tee-worker/actions/runs/3099250774/jobs/5019658635
https://github.com/litentry/tee-worker/actions/runs/3091569189/attempts/1
https://github.com/litentry/tee-worker/actions/runs/3091569189/attempts/2

Sometimes I see a timeout (so in that case 600s waiting time is not enough), sometimes the test ran through but the result was incorrect.

Ideally we can find out the reason of the failing tests and fix it.

**Comment by Kailai-Wang** [comment]
It's partially known in upstream: https://github.com/integritee-network/worker/issues/1023

**Comment by Kailai-Wang** [comment]
Who wants to check it? @litentry/tee

**Comment by BillyWooo** [comment]
one more record: https://github.com/litentry/tee-worker/actions/runs/3542718265/attempts/1
Repeat attempts, it finally past. 😕

**Comment by BillyWooo** [comment]
Looks like solved from upstream: https://github.com/integritee-network/worker/issues/1023. @Kailai-Wang

**Comment by Kailai-Wang** [comment]
It doesn't :(  at leats from following reading the comments in the issue.

We can close this ticket for now as it's (partially) superseded by #1175
