### ISSUE TITLE
Investigation and implementation of VC storage

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1021]
Current idea is to include the VC itself as the extrinsic/event parameter when passing back to parachain, e.g. `VCGenerated(origin, <account>, <identity>, <vc>)`, but we are not sure if it fits.

Tasks:
- [x] investigate the maximum allowed length in extrinsic/event
- [x] check how big the size of  a VC for simple rulesets would be and if it can fit into the extrinsic/event
- [ ] implement the storage of VC with external storage (IPFS, Arweave) -> I believe we need it sooner or later, as the VC **could** certainly be very large.

**Comment by jingleizhang** [comment]
Moved the task of `implement the storage of VC with external storage (IPFS, Arweave)` to issue https://github.com/litentry/litentry-parachain/issues/998. 

Due to the investigation is completed, close this one.
