### ISSUE TITLE
VC generation implementation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1022]
Following https://github.com/litentry/litentry-parachain/issues/782, we'd like to implement the VC generation function to generate a VC in JSON format. It needs to include the static part (e.g. metadata) and dynamic part (assertions).

If we find it difficult to get the metadata all at once, we may use some mocked data first.

**Comment by jingleizhang** [comment]
short term sub-issues:

- https://github.com/litentry/litentry-parachain/issues/1065
- https://github.com/litentry/litentry-parachain/issues/1004
- https://github.com/litentry/litentry-parachain/issues/1129
- https://github.com/litentry/litentry-parachain/issues/1002
- https://github.com/litentry/litentry-parachain/issues/1198
- https://github.com/litentry/litentry-parachain/issues/1234
- https://github.com/litentry/litentry-parachain/issues/1238

long term:
- https://github.com/litentry/litentry-parachain/issues/998

**Comment by jingleizhang** [comment]
Should be closed when all the short term issues are closed.

**Comment by jingleizhang** [comment]
All short-term issues are completed, except the implementation and test of A5. Close this issue.
