### ISSUE TITLE
Build Ruleset 13: The user has more than x amount of Karma on Reddit

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1023]
Build **Ruleset 13: The user has more than x amount of Karma on Reddit**. If the following is true it will generate a Verifiable Credential (VC):
- Reddit account must be provided and passed to the Parachain from the F/E using the `params` extrinsic param to verify this
- Reddit user/account must be linked and verified against the `idhub-address` which made the extrinsic call
- TEE must utilize Reddit REST API to validate if the Reddit user has Karma over one or more of the following:
  - 1K+ followers
  - 10K+ followers
  - 100K+ followers

**Comment by StamfordDigital** [comment]
Moving to the icebox. Not required for the initial phase.

**Comment by Kailai-Wang** [comment]
Close for now, we are not supporting Reddit right now
