### ISSUE TITLE
Build Assertion 12: LIT Hodler: The user held LIT before a specific year

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1024]
Check whether any of the linked accounts holds a minimum amount (0.000001) of LIT since year xxxx.

If TRUE, a VC should be generated and returned to the F/E. ?

------------------------------------------------------------------------------------------

Old description obsolate：

Build **Assertion 12: LIT Hodler: The user held LIT before a specific date/year**

- One or more Substrate Address(es)/account(s) must be provided and passed to the Parachain from the F/E using the `params` extrinsic param to verify this
- Substrate address(es)/account(s) provided must be linked and verified against the `idhub-address` which made the extrinsic call
- The TEE will call The Graph to determine when ****the user started holding LIT for address(es)/account(s) provided
- The TEE will look at the years for each Substrate address/account by The Graph and determine the earliest year the user has held LIT .
- The JSON payload of the VC will illustrate which year they have held LIT from

**Comment by bdmason** [comment]
Just to clarify, from TDF you want to send us an array of Litentry addresses and get the date when each one first held LIT?

cc @markdavison @jdomingos
