### ISSUE TITLE
Build Assertion 10: BTC Hodler: The user held Wrapped BTC before a specific date/year

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#1026]
Build **Assertion 10: BTC Hodler: The user held Wrapped BTC before a specific date/year**
- One or more EVM Address(es)/account(s) must be provided and passed to the Parachain from the F/E using the `params` extrinsic param to verify this
- EVM address(es)/account(s) provided must be linked and verified against the `idhub-address` which made the extrinsic call
- The TEE will call The Graph to determine how much **Wrapper BTC** the user has held historically over for the EVM address(es)/account(s) provided.
- The TEE will validate if the user has held **Wrapped BTC** before against all the required years. A **single BTC Hodler VC** will be generated if we find that the user has indeed held BTC before X date/year.
- The JSON payload of the VC will illustrate which date they have held BTC before 2011, 2015, and 2020.

**Comment by jingleizhang** [comment]
The years of 2011, 2015, and 2020 need to be converted to the corresponding block height on Ethereum.

**Comment by ziming-zung** [comment]
WBTC created at: https://etherscan.io/tx/0xdaaa0b08e0fa932ebf1ebc9ed2de9a6eb4db3f03c77e9ed937d9c9a3a49e2b81

Last block in 2020 is [11565018](https://etherscan.io/block/11565018)

**Comment by ziming-zung** [comment]
We can query the block by timestamp on the  [blockchair.com](https://blockchair.com/ethereum/transactions)
![image](https://user-images.githubusercontent.com/108339900/198952845-1eeaf8b2-2f4f-4244-ba65-bf52b2895403.png)

**Comment by Kailai-Wang** [comment]
I thought the query has to be served by Litentry Graph (TDF), doesn't it

So I simply call their interface with the parameters:
- address
- threshold
- year

In worst case LG only provides us a range of results (like amount in each year) and we have to go one step further and do a little verification work, but that's it.

> The TEE will call **The Graph** to determine how much Wrapper BTC the user has held historically over for the EVM address(es)/account(s) provided.
