### ISSUE TITLE
"IdentityAlreadyExist" error returned when using different arguments`

### ISSUE THREAD

**Issue by montogeek** [litentry/litentry-parachain#1048]
### Context
1. Make a call to `linkIdentity("twitter")` with **address0** and username0.
2. Get challenge code successfully.
3. Make a second call to `linkIdentity("twitter")` with **address0** and username1.
4. Get `IdentityAlreadyExist` error. 

### Acceptance criteria
Return new challenge code instead of `IdentityAlreadyExist` error since the username is different.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jonalvarezz** [comment]
Here are more details of this same issue:

1. Link a Twitter account
* handle: “my-username”; web_type: “Twitter”
* `linkIdentity`: Success. Block [42246](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-eu-0.staging.litentry.io#/explorer/query/0xb84883daed4ab8a8517abd520274a117cbc9cb8349dcc397e9035607b4860010)
* `verifyIdentity`: Success. Block [42251](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-eu-0.staging.litentry.io#/explorer/query/0xe3e62168649ff3de8ec50cda529d0299ebcb047e954bd37ac4715232b6ce8721)

2. Link another Twitter account:
* handle: “my-username-2”; web_type: “Twitter”
* challengeCode: Error(IdentityAlreadyExist). Block [42267](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-eu-0.staging.litentry.io#/explorer/query/0x16caf26ae2b64caea60c1d598eaadb27827e2a61b62965e82b5585c45f4fdc25)


Expected: user can request challenge codes for different `handle` of the same `web_type`

**Comment by Kailai-Wang** [comment]
Thanks for the report.

Looks like the handle type is incorrectly set when constructing the twitter identity, we expect a encoded "string", not `Address32` (as Twitter handle can be variable length).

<img width="638" alt="image" src="https://user-images.githubusercontent.com/7630809/205038761-39fadd75-f172-4489-8bfd-1a6f2484d338.png">

I wrote a rust unittest to double-check it but I couldn't reproduce the problem

**Comment by jonalvarezz** [comment]
Thank you for looking into it, Kai

I dug into our implementation and found that out the culprit was the `LitentryIdentity` type creation – which also confirms your finding.

For the record, this payload was producing the error:
```js
{
    handle: {
        Address32: '0x00000000000',
        Address20: '0x00000000000',
        PlainString: '0x1235....',
    },
    web_type: {
        Web2Identity: "Twitter",
    },
};
```

it should be
```js
{
    handle: {
        PlainString: '0x1235....',
    },
    web_type: {
        Web2Identity: "Twitter",
    },
};
```

**Comment by jonalvarezz** [comment]
This issue can be closed

**Comment by montogeek** [comment]
Fixed from the client side in https://github.com/litentry/my-crypto-profile/pull/1278
