### ISSUE TITLE
Figure out the workflow of Litmus leasing continuation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1055]
### Context
We still have 42 days left for Litmus leasing period.
How can we continue leasing it?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
https://guide.kusama.network/docs/learn-auction/#parachain-lease-extension

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/Parachain-Litmus-Lease-Period-Extension-2022-12-7-f88e1b72d8f24ed6a6891a8de2cabc0c
