### ISSUE TITLE
`Web3Validation` types for Polkadot.js API metadata

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#1058]
### Context
What's the right type for [`Web3Validation`](https://github.com/litentry/litentry-parachain/blob/d1d15217fb1b9c60e5bade95118eab2a6cf18630/mock-tee-primitives/src/validation_data.rs#L74) when verifying a web3 identity?

I am having issues with the `verifyIdentity` transaction. I get `identityManagementMock.VerifySubstrateSignatureFailed` all the time, as if the payload sent is not being picked up in the pallet; i.e., I may have the wrong type/payload for [`IdentityMultiSignature`](https://github.com/litentry/litentry-parachain/blob/d1d15217fb1b9c60e5bade95118eab2a6cf18630/mock-tee-primitives/src/validation_data.rs#L31).

I've tried these combinations: 

```js
Web3: {
  Substrate: {
    message: `0x1234...`;
    signature: {
      Sr25519: `0x1234...`; 
    }
  }
}
```

```js
Web3: {
  Substrate: {
    message: `0x1234...`;
    signature: `0x1234...`;
  }
}
```

```js
Web3: {
  Substrate: {
    message: `0x1234...`;
    signature: {
      Sr25519: {
        Signature: `0x1234...`;
      }
    }
  }
}
```

What's the correct one?

For signing, I am doing:
```js
message: blake2_256(code, address, identity)
signature: sign(address, message)
```

I want to make sure the types are right (they are incomplete on the [ts-test](https://github.com/litentry/tee-worker/blob/dev/ts-tests/type-definitions.ts) also) as it is not giving me assurance on what's wrong. 

I'd appreciate any insight, thanks

**Comment by jonalvarezz** [comment]
Related: https://github.com/litentry/litentry-parachain/issues/1054

**Comment by Kailai-Wang** [comment]
Can this issue be closed via #1072 @jonalvarezz, or do you need something else?

**Comment by jonalvarezz** [comment]
We can close it now.

For the sake of completeness, here is answer to the original question:

The right type is:

```
Web3ValidationData: {
  _enum: {
    Substrate: 'Web3CommonValidationData',
    Evm: 'Web3CommonValidationData',
  },
},
Web3CommonValidationData: {
  message: 'Vec<u8>',
  signature: 'IdentityMultiSignature',
},
IdentityMultiSignature: {
  _enum: {
    Ed25519: 'ed25519::Signature',
    Sr25519: 'sr25519::Signature',
    Ecdsa: 'ecdsa::Signature',
    Ethereum: 'EthereumSignature',
  },
},
```

For substrate accounts, depending on its signature crypto type, dApps need to pass the signature hex value on Ed25519, Sr25519, or Ecdsa.

**Comment by Kailai-Wang** [comment]
Thanks, closing it now :)
