### ISSUE TITLE
make returned error value be clear and specific 

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1064]
Identity Management Pallet only has `SomeError` right now which is not quite clear.

Those returned error values should be more clear and specific, and more friendly to FE and users.

reference error codes: https://docs.litentry.com/products/my-crypto-profile/developer-documentation/api-references

**Comment by Kailai-Wang** [comment]
related to https://github.com/litentry/litentry-parachain/issues/1008
