### ISSUE TITLE
Upgrade integritee dependencies to polkadot-v0.9.32 base

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1069]
### Context

As agreed with Integritee we'll start to take over the upgrade work of substrate/polkadot dependencies. The changes should be submitted as **PRs** into the **master(default)** branch of the corresponding integritee repos, in the following order:
1. [pallets](https://github.com/integritee-network/pallets)
2. [node](https://github.com/integritee-network/integritee-node)
3. [worker](https://github.com/integritee-network/worker)

It shouldn't break anything even we do it sequentially as `Cargo.lock` makes sure it has the matching revision.

**Please note:**
- we should only submit the next PR when the previous PR gets reviewed and merged
- we should only upgrade the dependencies without touching any code logic
- contact integritee colleagues if we meet any blockers during upgrade and/or need responsive reviews

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Btw please add links to PRs when closing this issue

**Comment by jingleizhang** [comment]
The pallets repo is merged

- [x] https://github.com/integritee-network/pallets/pull/121

**Comment by Marky-Shi** [comment]
node and worker pr is merged 

- [x] https://github.com/integritee-network/worker/pull/1124
- [x] https://github.com/integritee-network/integritee-node/pull/159
