### ISSUE TITLE
enclave can sign any given data within stf

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1078]
input:  any given data in Vec\<u8\> format

sign method: ed25519

output: signature and enclave's public key

**Comment by jingleizhang** [comment]
Should describe the whole enclave sign workflow. Then we can update it to our documents and articles.

**Comment by Teunhbrkn** [comment]
This would be very help full for understanding and giving outsiders an idea of how enclaves work as blackbox/truth oracles.

**Comment by jingleizhang** [comment]
Hey @Teunhbrkn, here is the link  https://www.notion.so/web3builders/004-enclave-sign-work-flow-366e9a9c95c14c4caff4e9951f1391cd . Please let us know if you need any data or information.

**Comment by jingleizhang** [comment]
will close this issue
