### ISSUE TITLE
Robustness and stability test for tee-worker

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1084]
### Context
We need to think of how can we make the tee-worker <> parachain setup more robust/stable as it's in a production env:

- sidechain block time: `itp_settings::sidechain::SLOT_DURATION` vs `itp_sgx_runtime_primitives::constants::SLOT_DURATION`
- stress test?
- benchmarking?
- random disconnect/reconnect test?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by ziming-zung** [comment]
Just to mark related issue or PR,  so that we can easily raise PR to upstream
### Issue
#1092 
#1175
