### ISSUE TITLE
VC generator: generates an unsigned VC according to schema

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1088]
input: VC json schema, https://github.com/w3c-ccg/vc-json-schemas/blob/main/docs/schema/2.0/schema.json

output: an unsigned VC with blank assertion content

**Comment by Kailai-Wang** [comment]
Is this issue still required?

**Comment by jingleizhang** [comment]
Yes. It's required as schemas are important to Assertion generation and F/E parsing. We are going to provide this feature from the beginning of next version.

**Comment by jingleizhang** [comment]
Another related issue is this https://github.com/litentry/litentry-parachain/issues/1298. @zhouhuitian will work on these two issues this and next week.

**Comment by jingleizhang** [comment]
The finalized JSON schema is [here](https://www.notion.so/web3builders/VC-Verification-e21fcb4cd9004672ac25b44609c8a86b?pvs=4#b9fa04eda3ac4299b69822092025cf26)
