### ISSUE TITLE
Devops: automation Set up TEE environment

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1089]
Ansible playbook to automate the installation and configuration steps of TEE environment.

**Comment by niteshb3495** [comment]
The ansible playbook is complete. I wanted to check the same. More details on Notion.

**Comment by niteshb3495** [comment]
The code is partially tested successfully. 
Next time when we will launch the new instance, the whole code can be tested and the installation will be from scratch.

**Comment by jingleizhang** [comment]
done, close this
