### ISSUE TITLE
Add staging env

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#109]
- [x] add a staging env that uses a fresh relay chain (restarted and get the parachain registered every time when dev is updated)

**Comment by chenzongxiong** [comment]
@Kailai-Wang Please check this branch and continue work if there is something missing 
https://github.com/Litentry-Dark/devops-scripts/tree/refactor-staging-scripts

**Comment by Kailai-Wang** [comment]
Staging env is now available:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-sg-1.staging.litentry.io#/explorer
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain-sg-2.staging.litentry.io#/explorer
