### ISSUE TITLE
Token Bridge Relayer account transfer

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#1090]
- [x] setup SSH and other stuff on prod1

- [x] Ethereum Token Bridge Multisig add/remove new and old ethereum wallet addresses.

- [x] Parachain add/remove new and old substrate wallet address (EnsureRootOrHalfCouncil)
pub fn add_relayer(origin: OriginFor<T>, v: T::AccountId)
pub fn remove_relayer(origin: OriginFor<T>, v: T::AccountId)

- [x] follow guidance setup token bridge service

**Comment by Kailai-Wang** [comment]
Please update and close this ticket when it's done :) thanks!

**Comment by jingleizhang** [comment]
cc @BillyWooo

**Comment by jingleizhang** [comment]
All accounts had been transferred.
