### ISSUE TITLE
Check extrinsic status in `indirect_calls_executor`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1092]
### Context
As far as I experimented, the `IndirectCallsExecutor` simply iterates over all extrinsics in a parentchain block and handles them, without checking the extrinsic status.

I intentionally misconfigured the parameter so that the extrinsic failed and threw out an error, but this extrinsic was still parsed. This seems incorrect.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
This is indeed a serious bug that I have reproduced before. Those failed extrinsic on parentchain should not be parsed and executed.

**Comment by ziming-zung** [comment]
See at: https://github.com/litentry/litentry-parachain/blob/78e162e218dd57c38a9d427cbe085b778ba09a9a/tee-worker/service/src/parentchain_handler.rs#L135-L155

**Comment by Kailai-Wang** [comment]
Please add a test for it whenever possible.

This will be later merged into upstream as it's a bug fix.
