### ISSUE TITLE
Parachain onboarding fails with polkadot-v0.9.33

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1097]
### Context
Steps to reproduce:
- change the following line to download 0.9.33 polkadot binary: https://github.com/litentry/litentry-parachain/blob/8b7f31b764f988b77bda6b27d4e4a796c95923bc/scripts/launch-local-binary.sh#L45
- make launch-binary-rococo
- observe that the `register-parachain` is executed successfully but the parachain can't be onboarded as parachain, but only as parathread:
<img width="479" alt="image" src="https://user-images.githubusercontent.com/7630809/208054511-f449ec5d-b3e0-4469-bb10-08718a1b4232.png">

polkadot 0.9.32 binary works smoothly.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
After that manually force-lease the parachain slot will upgrade the parathread to parachain, maybe we only need to add this step.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/7630809/208055030-84dbcd69-513a-428c-8358-fe41847dd972.png">

**Comment by Marky-Shi** [comment]
polkadot-v0.9.36 too,  but I'm more curious that the lease period set manually is 100 days, I'm more curious that the manually set lease period is 100 days, but on polkadot.js it shows as `1D 23H xxMins`.

<img width="1193" alt="image" src="https://user-images.githubusercontent.com/87012234/211450095-a32d6974-6391-4a68-9d73-e7e5874d97cb.png">

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/87012234/211449798-204cc290-76f0-4215-9c31-b74bc70612b9.png">

**Comment by Kailai-Wang** [comment]
I suspect something is wrong in polkadot-js.

If I manually execute `parasSudoWrapper.sudoScheduleParaInitialize` on polkadot-js UI, the parachain can be registered successfully. Why?

**Comment by Kailai-Wang** [comment]
Reopened just for the question above

**Comment by Marky-Shi** [comment]
> I suspect something is wrong in polkadot-js.
> 
> If I manually execute `parasSudoWrapper.sudoScheduleParaInitialize` on polkadot-js UI, the parachain can be registered successfully. Why?

I'll deal with it.

**Comment by Marky-Shi** [comment]
recarding  the related commit https://github.com/mangata-finance/mangata-node/commit/0f202986f112d8dc2a70d09c2733461af47cef04     
Prior to this,  was also used `parasSudoWrapper.sudoScheduleParaInitialize` for parachain registration, and the function of renewing the lease was added to this commit.   

The specific cause is still under investigation.

**Comment by Marky-Shi** [comment]
related  issue and question :

- https://substrate.stackexchange.com/questions/6706/use-polkadot-v0-9-33-or-hight-verison-bianry-launch-local-parachain-onborading-f
- https://github.com/polkadot-js/api/issues/5411

**Comment by Kailai-Wang** [comment]
Lower the priority again, we can live with that even if we can't find out the reason

**Comment by jingleizhang** [comment]
Should we close this issue?

**Comment by Kailai-Wang** [comment]
Have you investigated further into this? @Verin1005

**Comment by 0xverin** [comment]
> Have you investigated further into this? @Verin1005

I am not currently following up on it, may need to wait a little longer.

**Comment by 0xverin** [comment]
After reviewing it, it's difficult to determine the exact problem. It is likely a version issue. The local polkadot/api version we had at the time might not be consistent with the `polkadot/api` version used in the` polkadot.js UI`. This discrepancy caused the script to fail,but manual operations worked. Unfortunately, we couldn't find the specific reason for the update mismatch, and there were hardly any related issues available.Can we temporarily close this issue for now? @Kailai-Wang

**Comment by Kailai-Wang** [comment]
Let's close it for now - we can live with the parathread upgrade.
