### ISSUE TITLE
Build a token circulation monitor tool

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1104]
### Context

Not super urgent, but it would be helpful if we have a page on the network app to show the token circulation statistics:
- to publicize total supply and distribution
- for internal monitor

Chains to include: ERC20, parachains, token bridge, BSC?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by chenzongxiong** [comment]
any information related to this topic, e.g. contract address, detailed requirements. @jingleizhang

**Comment by qiuhaiguo** [comment]
Hi @chenzongxiong
**ERC20-LIT:** https://etherscan.io/token/0xb59490ab09a0f526cc7305822ac65f2ab12f9723,  the ecosystem, team, and foundation wallet's LITs are locked, others are in circulation
**Token-Bridge:** https://etherscan.io/token/0xb59490ab09a0f526cc7305822ac65f2ab12f9723?a=0x11bce4536296c81d1a291b1ffbe292fdd55a3a89
**Parachain-LIT:** I think we can query balance from our parachain RPC node
**BSC20-LIT:** https://bscscan.com/token/0xb59490ab09a0f526cc7305822ac65f2ab12f9723, all in circulation

### Requirement Details: 
1. Present total supply and total circulation of LIT token
2. Present the locked LIT token in our token bridge
3. Present issued LIT token in both parachains(Litmus and Litentry)
4. Locked LIT in the token bridge should be equal to the issued LIT token in both parachains

**Comment by chenzongxiong** [comment]
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.litentry-parachain.litentry.io#/chainstate

![image](https://user-images.githubusercontent.com/8354165/212568983-3ec37df4-f5ab-4c01-814f-ea795b601c18.png)

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.litmus-parachain.litentry.io#/chainstate
![image](https://user-images.githubusercontent.com/8354165/212569010-7cc40f21-9ab7-4d15-966b-6cc2e8933dc9.png)


**The total issuance is always 0**
@Kailai-Wang @qiuhaiguo

**Comment by Kailai-Wang** [comment]
The `Tokens` module is `orml_tokens`, so it's actually correct 🤔 @chenzongxiong

**Comment by chenzongxiong** [comment]
so I can read the data from api `token.totalIssuance`, right?

**Comment by chenzongxiong** [comment]
@qiuhaiguo @Kailai-Wang 
I add an api `token-info` for circulation & locked tokens info, i.e.

`GET /token-info`

and the response is that:
```
{

    "eth_total_supply": "100000000000000000000000000",
    "bsc_total_supply": "5000000000000000000000000",
    "litentry_total_supply": "11467730332678166738",
    "litmus_total_supply": "491396464779294304",
    "locked_info": {
        "ecosystem": "41909683000000000000000000",
        "team": "11341106580000000000000000",
        "foundation": "6579842790000000000000000",
        "bridge": "3185444866887807451830000"
    }
}
```

**I didn't find the resource to adapt our api for coingecko & coinmarket**, @qiuhaiguo do you have any related information. 

![image](https://user-images.githubusercontent.com/8354165/213810195-5001d4e8-8170-4ac1-b3ad-79b5ea615a7e.png)

**Comment by jingleizhang** [comment]
This API doesn't need to be adapted to them, just telling them the endpoint and data format is fine.

**Comment by jingleizhang** [comment]
@chenzongxiong Thanks, it's very helpful and looks fancy! Maybe only one more thing: the `decimal` fields needs to be added to each eth/bsc/litmus/litentry chain, as they are quite different.

**Comment by chenzongxiong** [comment]
It is normalized. I noticed that problem, evm is 18 whereas Substrate is 12 before sending to prometheus. Currently the decimal is missing in api response. Will add it soon

**Comment by jingleizhang** [comment]
ok

**Comment by chenzongxiong** [comment]
updated.
```

{

    "eth_total_supply": {
        "amount": "100000000000000000000000000",
        "decimal": 18
    },
    "bsc_total_supply": {
        "amount": "5000000000000000000000000",
        "decimal": 18
    },
    "litentry_total_supply": {
        "amount": "11387435524471171587",
        "decimal": 12
    },
    "litmus_total_supply": {
        "amount": "491351246026308843",
        "decimal": 12
    },
    "locked_info": {
        "ecosystem": {
            "amount": "41909683000000000000000000",
            "decimal": 18
        },
        "team": {
            "amount": "11341106580000000000000000",
            "decimal": 18
        },
        "foundation": {
            "amount": "6579842790000000000000000",
            "decimal": 18
        },
        "bridge": {
            "amount": "3072980137573724799830000",
            "decimal": 18
        }
    }

}

```

**Comment by jingleizhang** [comment]
cc @qiuhaiguo, Please check whether the above value is expected or not.

**Comment by jingleizhang** [comment]
from Remy: We should include the total LIT staked in collators for the dashboard. 

As web3go has a [dashboard](https://app.web3go.xyz/#/LitentryMainnetStaking), I think at least the following 2 values need to be added:

- amount of Total Validators
- amount of Total Staked LIT

**Comment by chenzongxiong** [comment]
done.

**Comment by jingleizhang** [comment]
<img width="2040" alt="image" src="https://user-images.githubusercontent.com/7367842/216339800-f0166f0a-6ec6-495d-a9e1-6a6161d2b24b.png">

It looks good, thanks!

**Comment by jingleizhang** [comment]
Issue is completed.
