### ISSUE TITLE
Rebuild T40 env

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#1119]
### Context
rebuild T40  env

### Task

- [x]  Reinstall ubuntu 20.04

- [x] rebuild sgx env

**Comment by Marky-Shi** [comment]
The T40 machine has abnormal power failure, resulting in static electricity between the memory and the motherboard, so that the machine cannot start. It takes a few days to observe and feel free to @ me if there are any questions.

**Comment by jingleizhang** [comment]
The instance is back to normal.
