### ISSUE TITLE
Tee doesn't support `mr_enclave` is not the same as `shard`

### ISSUE THREAD

**Issue by ziming-zung** [litentry/litentry-parachain#1128]
### Context
Currently, `mr_enclave` can only be the same as `shard` in parachain. See at:
https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/pallets/sidechain/src/lib.rs#L98-L101

But in tee-worker, `mr_enclave` is allowed to be different with `shard`. See at:
https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/tee-worker/service/src/utils.rs#L25-L42

When the `enclave_runtime` is modified, `mr_enclave` will be different every time. 
On the other hand, sometimes we may use the `init_shard` subcommand to fix the `shard` that make development and testing more efficient.

**Comment by jingleizhang** [comment]
Is this a tee-worker bug?

**Comment by ziming-zung** [comment]
I think it is a bug. :thinking:

**Comment by Kailai-Wang** [comment]
Yes it's a bug or at least inconsistent behaviour. It mostly benefits the testing setup

**Comment by Kailai-Wang** [comment]
It's known that only `MRENCLAVE == shard` is supported at the moment, I'll close it first.
