### ISSUE TITLE
Add entrance for users to apply for a credential

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1129]
The credential building process is hiding in the TEE-worker: https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/tee-worker/app-libs/stf/src/trusted_call_litentry.rs#L185-L189

But there isn't any entrance on the Parachain for users to make a Credential Issuance request. 

Now we have to:

- [x] add Credential Issuance Request extrinsic to VC Management Pallet
- [x] process the encrypted requests on Parachain, build the credential in TEE-worker accordingly

**Comment by jingleizhang** [comment]
What do you think? @Kailai-Wang

**Comment by Kailai-Wang** [comment]
There is: https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/pallets/vc-management/src/lib.rs#L178-L186

At least this is enough for the hardcoded assertions.

But we still need to add handling logic in `tee-worker/core/parentchain/indirect-calls-executor/src/indirect_calls_executor.rs`

**Comment by jingleizhang** [comment]
Should the parameter in [request_vc](https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/pallets/vc-management/src/lib.rs#L178-L186) be encrypted by `user_shielding_key` or not? @Kailai-Wang

**Comment by Kailai-Wang** [comment]
I think it's OK to leave it unencrypted, it's just an assertion ID.
