### ISSUE TITLE
Review the enclave registration process

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1133]
### Context
The last modification regarding enclave registration in worker-main won't change the logic, because `trusted_url` differs each time although `MRENCLAVE` is identical, is this intended? https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/tee-worker/service/src/main.rs#L544-L554

<img width="860" alt="image" src="https://user-images.githubusercontent.com/7630809/210019265-e5cc414d-6614-4f76-b1a5-8f6c235d1fbd.png">

We might need to ask Integritee why such a registration process is implemented, it seems more intuitive to have MRENCLAVE as key and a list of workers as (sub)-values.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Please note if we want to change it we have to consider some implicit consequences, e.g. when `search_peers` it looks for all registered enclaves (even with duplicated `MRENCLAVE`) to find all worker-URLs: https://github.com/litentry/litentry-parachain/blob/a56a56b05f309d29a9df51ec72ad50f46fb4dd34/tee-worker/service/src/worker.rs#L150-L161

**Comment by felixfaisal** [comment]
Hey @Kailai-Wang 
Could this issue be related to this - https://github.com/litentry/litentry-parachain/issues/1820
