### ISSUE TITLE
`identityManagement.verifyIdentity` doesn't accept signatures generated from Browser Extensions (Polkadot.js)

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#1137]
### Context
`identityManagement.verifyIdentity` validates the received Substrate signatures using `sp_io::crypto::sr25519_verify`
https://github.com/litentry/litentry-parachain/blob/37390508a87b79c09a1cba26488b09ebc45756eb/pallets/identity-management-mock/src/lib.rs#L603

`sp_io::crypto::sr25519_verify` works fine for local accounts, e.g. Alice, Bob, or those created using Keyring, but it fails at verifying signatures from Polkadot.js or any Browser Extension – main use case for dApps.

In other words, signatures created using https://polkadot.js.org/apps/#/signing will fail in `sp_io::crypto::sr25519_verify`.

Kailai and I were able to confirm that signatures from extensions wrap the data inside `<Bytes>...</Bytes>` as reported [here](https://substrate.stackexchange.com/questions/1810/transaction-fails-with-account-from-an-extension-but-ok-with-local-account). 

### Task
Even though we could find a workaround for this issue from a dApp, the pallets should consider extension signatures valid. Here is a Rust test supporting this use case: https://github.com/polkadot-js/wasm/blob/1916a4e10cd7fc151edbfbd95a9dafc724920110/packages/wasm-crypto/src/rs/sr25519.rs#L252-L269

What do you think?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Thanks for the issue @jonalvarezz ,I already have an issue for this: #1131 :)

If you don't find a way to sign the raw message without the `Bytes` wrapper, I'd suggest we make changes on runtime side.

In that case you don't have to change anything from F/E, and we post-process the message to **always** wrap it with `<Bytes>..</Bytes>` before verifying the signature. Please note you should pass in the **raw message**(so without Bytes wrap-up) in the validation_data as before.

Please lmk how that sounds to you. I'll make the change once you confirm

**Comment by jonalvarezz** [comment]
> we post-process the message to always wrap it with <Bytes>..</Bytes> before verifying the signature.

Yes, that's the way to go. When using extensions, we only have access to `signRaw` which, indeeded, forcibly wraps the data. 

However, can we support both? with and without `<Bytes>...</Bytes>`?  I am thinking of Node.js apps where Keyring is used, for example, the `tee-worker/ts-tests`

i.e., if signature verify fails, wrap/unwrap it with `<Bytes>...</Bytes>` and try again

**Comment by Kailai-Wang** [comment]
> > we post-process the message to always wrap it with .. before verifying the signature.
> 
> Yes, that's the way to go. When using extensions, we only have access to `signRaw` which, indeeded, forcibly wraps the data.
> 
> However, can we support both? with and without `<Bytes>...</Bytes>`? I am thinking of Node.js apps where Keyring is used, for example, the `tee-worker/ts-tests`
> 
> i.e., if signature verify fails, wrap/unwrap it with `<Bytes>...</Bytes>` and try again

Theoretically we could do that, yes, but I want to raise a few alternatives.

Imagine:
`M(r)` = raw message, in our case it's the blake2_256 hash of the encoded payload
`M(w)` = wrapped version of raw message: `<Bytes>M(r)</Bytes>`
`S(r)` = Signature by signing `M(r)`
`S(w)` = Signature by signing `M(w)`

### Option 1
we **only** accept `M(r)` and `S(w)` in `verify_identity`, we will transform `M(r)` to `M(w)` internally. In this case IDHub doesn't have to change anything, but we need to adjust ts-tests to comply with it.

### Option 2
we support both `S(r)` and `S(w)`, there are again two ways to do it:
2.1: we only accepted matched message and signature. So either `M(r)` and `S(r)`, or `M(w)` and `S(w)`, but not mixed. Internally we check if M starts with `<Bytes>` to tell if it's `M(r)` or `M(s)`.
2.2: we only accept `M(r)`. We verify the signature against `M(r)`, if it fails, we transform `M(r)` to `M(w)` and verify it again.

I personally prefer option 1 as it's simple enough and throughout consistent, but please let me know what you think @jonalvarezz @litentry/parachain

**Comment by jonalvarezz** [comment]
Thank you, Kai.

I prefer option 2.2. The first option is more consistent technically but not practically, I'd prefer to make it as straightforward as possible to clients when interacting with our pallets.

**Comment by Kailai-Wang** [comment]
> Thank you, Kai.
> 
> I prefer option 2.2. The first option is more consistent technically but not practically, I'd prefer to make it as straightforward as possible to clients when interacting with our pallets.

Sure, I'm fine with any of these. I'll implement option 2.2
