### ISSUE TITLE
The returned IdGraph is not reflecting the latest state

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#1148]
Hi folks, we found the following bug. Is it expected?

### Steps to reproduce

1. Link an Identity and complete both `createIdentity` and `verifyIdentity` transactions.
2. Inspect the `idGraph` returned as part of the `IdentityManagement[Mock].IdentityCreated` event

### Result

The `idGraph` includes the newly added Identity, but its property `isVerified`  comes as `false`

Here is a screenshot for reference.
![Screen Shot 2023-01-04 at 09 09 48](https://user-images.githubusercontent.com/2167222/210518425-1631d3f1-2543-47e7-b3a5-b87059c9b0dd.png)

Notice that the added identity (`0x3cc0d57dd514...`) comes with `isVerified` false.

### Expected:

The new identity is in the idGraph and is set to `isVerified == true`

### More info

Consequent events containing `idGraph` reflect the correct value. 

Here is a screenshot of a subsequent challenge code request for another Identity:

![Screen Shot 2023-01-04 at 09 10 43](https://user-images.githubusercontent.com/2167222/210519140-d8876fb4-d749-4bc4-bcd5-9b0c112c84e9.png)

Additionally, I noticed that running `tee-worker/ts-tests` fail at the end by asserting precisely if `isVerified == true`

**Comment by jonalvarezz** [comment]
cc @montogeek

**Comment by Kailai-Wang** [comment]
I see where it goes wrong, will fix it today. Thanks for reporting

**Comment by Kailai-Wang** [comment]
> Additionally, I noticed that running tee-worker/ts-tests fail at the end by asserting precisely if isVerified == true

Can you please elaborate on this part?
I'm able to locate the problem in the IMP mock pallet, but the real pallet should function correctly.

In the `tee-worker/ts-tests` we do assert the identity is verified: https://github.com/litentry/litentry-parachain/blob/5c57a53e33909fb103138e1ebc3691a9743ea154/tee-worker/ts-tests/identity.test.ts#L276

**Comment by jingleizhang** [comment]
reopen this until the fix is verified by IDHub team

**Comment by Kailai-Wang** [comment]
> reopen this until the fix is verified by IDHub team

cc @jonalvarezz 
Please leave a comment and close this ticket after you verify it, thanks!

**Comment by jonalvarezz** [comment]
Looking good. Thank you! I'm thus closing this issue.
![Screen Shot 2023-01-05 at 14 15 28](https://user-images.githubusercontent.com/2167222/210788624-6696fb1e-8310-476b-a23b-47b3bf0b4be3.png)
