### ISSUE TITLE
pass credential as event parameter back to parachain

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1150]
TEE-worker should be able to pass a credential as event parameter back to parachain.

The related discussion is https://github.com/litentry/litentry-parachain/issues/998

**Comment by Kailai-Wang** [comment]
The related extrinsic is ready: https://github.com/litentry/litentry-parachain/blob/147d56ffe635143e7cec9d1f077bb21f04bb10aa/pallets/vc-management/src/lib.rs#L218-L229

**Comment by jingleizhang** [comment]
Got it, thanks!
