### ISSUE TITLE
Restructure the integration test cases

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1153]
### Context
We are having more and more integration tests for the tee-workers. Putting every test case into a separate YML might be overkill since it introduces a new matrix-branch in the CI.

Is there a better way to group them?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
For the shell script we could extract the standard part (e.g. utility, helpers) to avoid code duplication

**Comment by BillyWooo** [comment]
https://github.com/litentry/litentry-parachain/pull/1299
https://github.com/litentry/litentry-parachain/pull/1310

**Comment by Kailai-Wang** [comment]
I think there are still a few things worth doing, like mentioned in the topics:
- group the common utilities 
- better ways of handling test case execution in parallel (other than matrix) -> it might need research

**Comment by Kailai-Wang** [comment]
Closing it - we have done some improvements and so far happy with the current implementation
