### ISSUE TITLE
check security when register enclave on parachain 

### ISSUE THREAD

**Issue by zTgx** [litentry/litentry-parachain#1163]
### Context
on tee-worker side, it gets sig from intel service, then register on parachain. 
on parachain side, it just verify the sig, if success then add to enclaveregistry.

what if a tee-worker node from third party, verified by parachain, but it's a malicious node?
is there a defense mechanism to protect parachain from malicious enclave register?

like whitelist?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Do we need to provide "expected" MRENCLAVE when doing RA? If not, how can IAS issue a report saying the running enclave is the "desired" one?

But we probably need a whitelist anyway: #1177

**Comment by Kailai-Wang** [comment]
When we don't skip IAS-verify, the `register_enclave` can only be called by the attested enclave:

https://github.com/litentry/litentry-parachain/blob/abfa4c06c7a5c3f0437d11745c9b4dd9ac1bc11e/pallets/teerex/src/lib.rs#L440

Is this enough?

**Comment by jingleizhang** [comment]
> When we don't skip IAS-verify, the `register_enclave` can only be called by the attested enclave:
> 
> https://github.com/litentry/litentry-parachain/blob/abfa4c06c7a5c3f0437d11745c9b4dd9ac1bc11e/pallets/teerex/src/lib.rs#L440
> 
> Is this enough?

this is good enough.

**Comment by Kailai-Wang** [comment]
I think we need more than that.

Anyone with the same MRENCLAVE can register on chain, maybe we don't want that before we allow full decentralised tee-worker cluster.

See https://github.com/litentry/litentry-parachain/issues/1225

**Comment by Kailai-Wang** [comment]
We have max-allowed-enclave-count and allowed-mrenclave upon enclave registration, I think we are good for now
