### ISSUE TITLE
Sync upstream(integritee) changes on a monthly basis

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#1164]
### Context
sync upstream code 

- pallets   https://github.com/integritee-network/pallets.git
- worker  https://github.com/integritee-network/worker.git

Just leave the link comment below the PR and empty it once a month.

**Comment by Marky-Shi** [comment]
Jan:
https://github.com/litentry/litentry-parachain/pull/1158

https://github.com/litentry/litentry-parachain/pull/1165

**Comment by Kailai-Wang** [comment]
We can have a GHA that monthly creates a new issue for upstream syncing (if we should do it at a frequency of monthly)

**Comment by BillyWooo** [comment]
Not relevant any more.
