### ISSUE TITLE
kusama registrar status monitor

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1169]
Todo

- [x]  check service alive(the API is live, and the response data is good)
- [x]  check if the Kusama block synchronization has stopped (the synced block number is behind Kusama, for example, 100 blocks)
- [x]  send alerts
- [x] check every minute

**Comment by 0xverin** [comment]
It is better to add a rate limit of calls to the service

**Comment by niteshb3495** [comment]
Completed all the points. The script is setup in cron.
