### ISSUE TITLE
Should the IDGraph contain the main litentry identity?

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1174]
### Context
It will affect the identity vector that is passed into the assertion building.

Or is it assertion specific? Like when calculating the total amount of LIT tokens held, we should definitely include it.

Please share your opinions too @jonalvarezz @kaylawangnow

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jonalvarezz** [comment]
It makes sense to me for the IDGraph to always include the main identity. i.e., initializing the IDGraph with the main identity so it is the first one always.

Mutating the IDGraph on exec time to pass it into assertions could lead to errors; it'd be something we should remember.

**Comment by kaylawangnow** [comment]
Pls count the main account in as original Litentry users may tend to use informative Litentry address to sign up, and especially in the future we want to support EVM sign up it happens more.

**Comment by Kailai-Wang** [comment]
Set the priority to `High` -> such changes might affect the implementation in IDH, thus should be done as early as possible.

**Comment by jonalvarezz** [comment]
Thanks, Kai!
