### ISSUE TITLE
Enclave update [3] - handling of update_enclave in the worker

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1179]
The most difficult part.

The general goal of the handling is:
from the scheduled (sidechain) block number on, only the worker with the new MRENCLAVE can continue to author blocks. If the worker still has the old MRENCLAVE, it should only sync the blocks but not produce blocks. Similarly, if a worker with the new MRENCLAVE joins before the update point, it should only sync the blocks.

Remember a worker can join at any time, with old or new MRENCALVE. We need to provide handling for all cases.

**Comment by jingleizhang** [comment]
related issue: https://github.com/litentry/litentry-parachain/issues/1295

**Comment by Kailai-Wang** [comment]
Basically done in https://github.com/litentry/litentry-parachain/pull/1579

We still need cases for 2 workers though - but will open issues when needed
