### ISSUE TITLE
Switch to dtolnay/rust-toolchain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1196]
### Context
`actions-rs/toolchain` is unfortunately not maintained anymore: https://github.com/actions-rs/toolchain/issues/216.

`actions-rs` will stop working anyway later due to the deprecation of set-output and NodeJS 12.

Let's switch to other rust-toolchain GHA, e.g. `dtolnay/rust-toolchain` (or if you have better candidates).

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Marky-Shi** [comment]
Okay got it,I'll look for alternative `actions-rs/toolchain` tools, and if not, I'll replace CI's rust-toolchain with `dtolnay/rust-toolchain `and test it.

**Comment by Marky-Shi** [comment]
Found two similar repos, but personally feel inferior to `dtolnay/rust-toolchain` 
https://github.com/hecrj/setup-rust-action 

https://github.com/taiki-e/setup-cross-toolchain-action
