### ISSUE TITLE
Change credential assertions from String to Struct Logic

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1198]
Currently, the credential assertions are String, https://github.com/litentry/litentry-parachain/blob/ccc5abd2bca2d6aedb27f1e824e2460dfe9725fc/tee-worker/litentry/core/credentials/src/lib.rs#L299-L304

they need to be changed to Struct Logic inside Struct Credential

**Comment by DogLi** [comment]
I think [this example](https://gist.github.com/rust-play/a359a1aa96a26c7da8ea3f8e6998fce3) could help.
