### ISSUE TITLE
Limit the number of allowed workers

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1225]
### Context
related: #1163 

Even when we have a "whitelist of allowed enclaves", we might still want to limit the number of allowed workers and/or the worker accounts.

Extra workers could cause block syncing and production problems before it's thoroughly tested, even though they are running the same enclave.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by songzhouran** [comment]
What the the max number of enclave? @Kailai-Wang
