### ISSUE TITLE
No panic in enclave

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1227]
### Context
As in this comment: https://github.com/integritee-network/worker/pull/1134#discussion_r1083861780

Let's double-check the code and try to avoid panic as possible

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
Make sure that each workflow in TEE-worker returns an event, that would make IDH and ts-test' life easier.

**Comment by jingleizhang** [comment]
from @Verin1005 
``` extrinsic error code 1002: Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `RuntimeCall::IdentityManagement.0`:\n\tCould not decode `Call::some_error::error`:\n\t\tCould not decode `IMPError`, variant doesn't exist\n: RuntimeApi(\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `RuntimeCall::IdentityManagement.0`:\\n\\tCould not decode `Call::some_error::error`:\\n\\t\\tCould not decode `IMPError`, variant doesn't exist\\n\ ```

**Comment by DogLi** [comment]
```
[+] We are NOT the primary validateer
*** [+] Finished syncing light client, syncing parentchain...
[+] Found 548 block(s) to sync
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/linfeng/litentry-parachain/tee-worker/core-primitives/node-api/api-client-extensions/src/chain.rs:107:66
```

**Comment by Kailai-Wang** [comment]
Prioritise this - it's an important issue.

Do we have an automatic way to detect this? (code static analysis?)

**Comment by kziemianek** [comment]
We cannot prevent panics happening but we can definitely reduce the risk. 

I briefly evaluated two ways of making panic less likely:

1. Using third party library, eg. no-panic 
2. Using more restrictive clippy rules

[No-panic](https://crates.io/crates/no-panic) is rust lib that requires compiler to prove that functions marked with `#[no_panic]` can’t panic at all. It can definitely detect more paths leading to panics but I don’t think we need such restrictive control, at least now.

On the other hand clippy has few interesting [rules](https://rust-lang.github.io/rust-clippy/master/index.html#?groups=restriction
) that can spot lines potentially leading to panics. They should cover all cases described in issue and will analyze only our code.

Clippy rules we could apply:

- [ ] Clippy::arithmetic_side_effects
- [x] Clippy::expect_used
- [x] Clippy::indexing_slicing
- [x] Clippy::panic
- [x] Clippy::panic_in_result_fn
- [x] Clippy::string_slice
- [x] Clippy::unimplemented
- [x] Clippy::unreachable
- [x] Clippy::unwrap_used

We can start by gradually applying one-by-one rules listed above.
