### ISSUE TITLE
Build tee-worker image sometimes fails

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1233]
### Context

Due to test failure `graphql::tests::verified_credentials_total_transactions_work`.
E.g.:
https://github.com/litentry/litentry-parachain/actions/runs/4031797992/jobs/6931305403
https://github.com/litentry/litentry-parachain/actions/runs/4033276214/attempts/1

Can we try to stabilize it? Accessing remote HTTP service in cargo-test might not be a good idea anyway, or at least we should allow it to fail when it's just due to inaccessible server.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by ziming-zung** [comment]
It should be resolved after PR #1236 is approved

**Comment by Kailai-Wang** [comment]
> It should be resolved after PR #1236 is approved

Great, can we close this issue now?

**Comment by Kailai-Wang** [comment]
This is done - I haven't seen the errors for a while
