### ISSUE TITLE
Timeout in ts-tests for worker CI

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1237]
### Context
It happened a few times already, e.g. here: https://github.com/litentry/litentry-parachain/actions/runs/4035469718/jobs/6938004060

What's the reason? 15 blocks should be more than enough seeing that the successful ones normally take 4-5 blocks.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Verin1005** [comment]
This is probably a verify failure, did you start the Tee with mockserver?

**Comment by jingleizhang** [comment]
The related issue is https://github.com/litentry/litentry-parachain/issues/1227

**Comment by Kailai-Wang** [comment]
Happened again: https://github.com/litentry/litentry-parachain/actions/runs/4056307952

Have we misused the polkadot-js somehow? Because we don't see it in other tests where rust command-line tests are used.

**Comment by Kailai-Wang** [comment]
Change the priority to "High", it happened more and more often: https://github.com/litentry/litentry-parachain/actions/runs/4066168337/jobs/7004151828

**Comment by Kailai-Wang** [comment]
After investigation:
the root-cause is worker2 can't access `localhost:9527` (mock-server launched by worker1) in docker setup. Ts-tests only sends indirect calls, which means it's down to the slot proposer to actually execute the trustedCalls. If worker1 is selected to produce blocks, everything is fine; if worker2 is selected, it tries to retrieve the tweet content in the mock server but couldn't get it - hence timeout.
