### ISSUE TITLE
Restructure internal tech documentations

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1239]
Restructure and clean up internal tech documents, create the major entry/portal, keep contents updated, and add missing parts.

**Comment by Kailai-Wang** [comment]
Are we following up on this?

**Comment by Kailai-Wang** [comment]
friendly ping @cryptoade1  :)

**Comment by cryptoade1** [comment]
We’re currently working on this at the moment.

Thanks

**Comment by Kailai-Wang** [comment]
should be done
