### ISSUE TITLE
Bug: no `IdentityManagement.IdentityVerified` event returned

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1258]
On the Web2 Identity Linking workflow, there is no `IdentityManagement.IdentityVerified` event returned. 

The https requests might fail silently.

**Comment by Kailai-Wang** [comment]
Any (CI) links and/or more context? How to reproduce it?

**Comment by jingleizhang** [comment]
They were in SomeError, now fixed.
