### ISSUE TITLE
 ts-test should get shard from parachain instead of local worker node

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1260]
related PR is https://github.com/litentry/litentry-parachain/pull/1222

<img width="1162" alt="image" src="https://user-images.githubusercontent.com/7367842/216295525-3bb558b4-ed4c-49e6-9124-74776edc5580.png">

**Comment by Kailai-Wang** [comment]
Shard is the same as MRENCLAVE btw

**Comment by Kailai-Wang** [comment]
Is this done? I only see the linked PR was closed.

Let's always link a PR with an existing issue (if applicable), thanks!

**Comment by jingleizhang** [comment]
This is done, we can close this one.
