### ISSUE TITLE
Onboard governance v1.0 for Litentry parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1270]
### Context
Similar to https://github.com/litentry/litentry-parachain/issues/664

Tasks:
- [ ] Finalize and adjust collective members
- [x] Double-check the runtime parameters and configurations
- [x] Adjust baseCallFilters
- [x] Adjust origins -> e.g. `EnsureRootOrxxCouncil`
- [ ] build a runtime upgrade release

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
Code is ready. PR for view
https://github.com/litentry/litentry-parachain/pull/1279
