### ISSUE TITLE
Associate the errors with the request extrinsics

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1272]
### Context
Raised by IDH colleagues, we only return the error names/strings when some error happens (e.g. when creating or verifying identities), but there's no way to associate the error to a specific extrinsic request. This makes it difficult for F/E to tell which account/identity the error is regarded, which makes the error message sometimes useless.

How to solve it?

cc @jonalvarezz @kaylawangnow

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jonalvarezz** [comment]
I would like to understand the trade-off and our limitations here. 

Why can't we include the request extrinsic hash in the TEE emitted event? 

I noticed that `vcManagement.VCIssued` emits the unencrypted user account, and even though, this help filter by the user we would like to have more precision.

PD: Including the user account is a good start but may not escalate for more than one client.

**Comment by jingleizhang** [comment]
One account using by multiple clients at the same time, is this use case common or uncommon? 

IMHO: Generally, this is assumed as a very unusual use case.

**Comment by jonalvarezz** [comment]
As long as it is technically possible we should account for that. 

For example, having the same account in multiple Wallets Extension at the same time is totally possible and our Parachain shouldn't care about it.

I imagine the same for our protocol. Users should be able the export their shielding key + any other data from IDHub and import it into other clients.

**Comment by jingleizhang** [comment]
Understand. User shielding key + any other data can be exported elsewhere, or vice versa. 

Ideally, if there are many sync/async steps behind an extrinsic request, the call should be assigned a UUID/Hash at the beginning. But this is kind of overkill for us.

**Comment by Kailai-Wang** [comment]
> Why can't we include the request extrinsic hash in the TEE emitted event?

This is technically possible.
@jonalvarezz is it the only thing you need to differentiate between requests? Do we need to include the identity again? E.g. the `IdentityVerified` event currently has:
```
Event::IdentityVerified { account, identity, id_graph }
```

Do you want to replace the `identity` or append a field like `request_ext_hash`?

I self-assigned this issue btw.

**Comment by Kailai-Wang** [comment]
@jonalvarezz so I'd still need your input here before we continue our implementation :)

- which one serves you better in the error event? `request_ext_hash` or the `identity`?
- can you confirm you only need such adjustments in the error event? So for a "normal" event (e.g. `IdentityVerified`) do you want us to apply this change too, or keep the old implementation?

**Comment by jonalvarezz** [comment]
> which one serves you better in the error event? request_ext_hash or the identity?

I assume `request_ext_hash` doesn't add a significant impact to the Event size, so can we have both? 😄

> can you confirm you only need such adjustments in the error event? So for a "normal" event (e.g. IdentityVerified) do you want us to apply this change too, or keep the old implementation?

Let's also add `request_ext_hash` to the other events

**Comment by Kailai-Wang** [comment]
> I assume request_ext_hash doesn't add a significant impact to the Event size, so can we have both? 😄

Well 32 bytes, not trivial either 😋 can you safely discard `identity` if you have the ext_hash? The identity is actually bigger than the ext_hash 😂 

> Let's also add request_ext_hash to the other events

Same question above - other events have `identity` already, do you want both?

**Comment by jonalvarezz** [comment]
> Well 32 bytes, not trivial either 😋 can you safely discard identity if you have the ext_hash?

Yeh let's have ext_hash only and discard `Identity` for Errors

> Same question above - other events have identity already, do you want both?

For normal events, yes, let's please include the extrinsic hash

Thank you!

**Comment by Kailai-Wang** [comment]
Thank you @jonalvarezz 

I have a summary in https://github.com/litentry/litentry-parachain/issues/1442#issuecomment-1470058218

Once you confirm we'll start to create (sub)-issues and move on to it
