### ISSUE TITLE
StfError in trusted_call fails silently

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1274]
https://github.com/litentry/litentry-parachain/blob/ce0ff808b44c204149da4c395734e0dc10fbabe9/tee-worker/app-libs/stf/src/trusted_call_litentry.rs#L125-L126

The trusted_call doesn't return to Parachain when an error happens, as the StfError is just emitted into the worker log.

Parachain needs to know when there is a trusted_call error.

**Comment by Kailai-Wang** [comment]
Good catch, I think in general the error handling in trusted_call needs to be improved, even `ensure!` doesn't propagate the error properly.
