### ISSUE TITLE
Bug: when user applying web2/web3 VC, user's handler is exposed

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1277]
<img width="674" alt="image" src="https://user-images.githubusercontent.com/7367842/216886165-cee4159f-9a95-4528-b175-cf530fb272a0.png">

Those parameters aren't actually needed when applying a VC. 

Next PR will hide them.

**Comment by Kailai-Wang** [comment]
As mentioned, A2 and A3 originally had `channel_id` and `guild_id`, which are all public information - no user handle should be exposed whatsoever

https://github.com/litentry/litentry-parachain/commit/8b7f31b764f988b77bda6b27d4e4a796c95923bc#diff-73a8e97736ed30521f3443475da295cb3f0cc645a6f058c926ef6c800b624445

![image](https://user-images.githubusercontent.com/7630809/217207227-b77ff32f-7963-439d-ab93-ef37ba7345f0.png)

**Comment by jingleizhang** [comment]
Got it. Now it's wrongly used as `guild_id` and `user_id`.
