### ISSUE TITLE
Switch to docker compose v2

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1296]
### Context
Per https://www.docker.com/blog/new-docker-compose-v2-and-v1-deprecation/

`docker-compose` v1 will be deprecated, let's switch to v2 and make any needed adjustments, low prio.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
This is a minor update. Please assign it to me. I am taking care of it when doing #1153 .
