### ISSUE TITLE
Token bridge - investigate deployment of a new contract 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1309]
### Context
We'd like to check if it's worth replacing the current token bridge contract with newer versions so that:
- the timeout before a proposal is cancelled (100 blocks) can be re-initialised
- the logic of proposal execution is simplified: followed directly by the proposal pass. It doesn't have to be called explicitly and thus lower the commission

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/Parachain-Token-Bridge-2023-2-15-d08ceae243f943ffbd4b6e4a243046d5

**Comment by wangminqi** [comment]
New feature needed testing:
- [ ] Everyone can execute proposal if proposal passed.
- [ ] Extrinsic of relay is compatiable.
- [x] Expired can be changed with Admin power.
- [x] If changed, Expiry parameter will not trap proposal status.

**Comment by Kailai-Wang** [comment]
Done in the new token bridge
