### ISSUE TITLE
Token bridge:  a pop-up warning is needed when previous trxs are pending

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1311]
As there are already pending trxs sent by the bridge contract, a pop-up warning could notify users that their transfers will pending as a consequence.

bridge contract address: https://etherscan.io/address/0x97cb2a379bb6d66825a3df6a665b1ffe2392ed35

**Comment by Kailai-Wang** [comment]
Is there any update for this?

**Comment by Kailai-Wang** [comment]
Is this done? If so can you please close it? @Verin1005

**Comment by 0xverin** [comment]
> Is this done? If so can you please close it? @Verin1005

done!
