### ISSUE TITLE
Failed to transfer worker request response to o-call buffer

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1336]
### Context
Failed to transfer worker request response to o-call buffer: InsufficientBufferSize(33568, 56835)

**Comment by Kailai-Wang** [comment]
Shall we add more context? Otherwise it's hard for others to understand what it's all about (hence can't review the PR).

Like when did it happen, in local tests or CI? Any more links/screenshots/log records? Any solution directions/TODOs?

**Comment by jingleizhang** [comment]
`Failed to transfer worker request response to o-call buffer: InsufficientBufferSize(33568, 42549)`

reproduce: on tee-staging, when I rerun a worker from somewhere else to connect the parachain, the error would be there.

**Comment by outofxxx** [comment]
There're 4 entry points may produce this error:

1. `validateer_count`
https://github.com/litentry/litentry-parachain/blob/bfcc971b900b42fab297dc9bce5d2fc710c0f008/tee-worker/sidechain/validateer-fetch/src/validateer.rs#L60-L66

`775 Bytes` in my test result.

2. `execute_trusted_call_on_stf`
https://github.com/litentry/litentry-parachain/blob/bfcc971b900b42fab297dc9bce5d2fc710c0f008/tee-worker/core-primitives/stf-executor/src/executor.rs#L125-L128
 
`1 Byte` in my test result.

3. `update_states`
https://github.com/litentry/litentry-parachain/blob/bfcc971b900b42fab297dc9bce5d2fc710c0f008/tee-worker/core-primitives/stf-executor/src/executor.rs#L183-L186

`440 Bytes` in my test result.

4. `current_validateers`
https://github.com/litentry/litentry-parachain/blob/bfcc971b900b42fab297dc9bce5d2fc710c0f008/tee-worker/sidechain/validateer-fetch/src/validateer.rs#L43-L55

`3815 Bytes` in my test result.

---

As this issue's description, I think it's probably caused by `EnclaveRegistry` data from `current_validateers`. 
We have refactored enclave register to reduce the enclave registry size and doubled the BufferSize to 64K since this issue was submitted .

To re-produce this issue, We need more test.

**Comment by Kailai-Wang** [comment]
Thanks for the investigation @zhouhuitian 

Can it be caused by the size of IDGraph in the returning event? See #1442

**Comment by outofxxx** [comment]
the sizeof IDGraph issue: https://github.com/litentry/litentry-parachain/issues/1487

I think this issue can be closed.

**Comment by jingleizhang** [comment]
`this issue can be closed` +1
