### ISSUE TITLE
Store the exemplary VCs in repo

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1337]
### Context
For each assertion, we'd better have an exemplary VC in repo for reference.

Ideally we can have README about how these VCs are generated (with which commands/steps)

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
All examples are listed here: https://www.notion.so/web3builders/Credential-Interface-90f12a7d57ce40bcbda9894b05f4bd5a, and we are responsible for making them updated all the time.

**Comment by Kailai-Wang** [comment]
> All examples are listed here: https://www.notion.so/web3builders/Credential-Interface-90f12a7d57ce40bcbda9894b05f4bd5a, and we are responsible for making them updated all the time.

Thanks! Any commands that can generate these?

**Comment by jingleizhang** [comment]
Currently there are not any commands, but some explanation could be added to the above doc.

**Comment by jingleizhang** [comment]
close this issue, as the examples are available in the doc above.
