### ISSUE TITLE
Bug: wrong value of from_date and to_date in holder assertions

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1339]
now the assertion values are:

{
				"src": "$from_date",
				"op": "<",
				"dst": "2017-01-01,2018-01-01,2019-01-01,2020-01-01,2021-01-01,2022-01-01,2023-01-01"
			}, {
				"src": "$to_date",
				"op": ">=",
				"dst": "\\"2023-02-16\\""
			}

so here are two bugs:

- `from_date` should be one of "2017-01-01,2018-01-01,2019-01-01,2020-01-01,2021-01-01,2022-01-01,2023-01-01"
- `to_date` should remove \\"

**Comment by outofxxx** [comment]
hodler assertion description: [hodler](https://www.notion.so/web3builders/Assertion-hodler-2238ef0504ba43dab754be0f655c7ca1)
