### ISSUE TITLE
Expose vc signer pubkey to parachain

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1348]
### Context

to verify vc for frontend.

**Comment by 0xverin** [comment]
related to https://github.com/litentry/litentry-parachain/pull/1328

**Comment by zTgx** [comment]
sign vc method right now:

https://github.com/litentry/litentry-parachain/blob/d791364a28b42c9718688ccc1c58416d2855ebde/tee-worker/core-primitives/stf-executor/src/enclave_signer.rs#L129-L133

https://github.com/litentry/litentry-parachain/blob/d791364a28b42c9718688ccc1c58416d2855ebde/tee-worker/core-primitives/stf-executor/src/enclave_signer.rs#L80-L83

it's unsafe.
The users will derive vc signer private key depending on the shielding key from parachain.
