### ISSUE TITLE
Expose shielding pubkey only

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1349]
### Context
relevant pr https://github.com/litentry/litentry-parachain/pull/1222

**Comment by ziming-zung** [comment]
Now, we use these code to expose shielding key
https://github.com/litentry/litentry-parachain/blob/4d3f3fd135debf1464ad0f057723ea492f957de5/tee-worker/enclave-runtime/src/attestation.rs#L212-L217
It is not safe, beacause `GLOBAL_SHIELDING_KEY_REPOSITORY_COMPONENT ` is a key pair(private key). see 

https://github.com/litentry/litentry-parachain/blob/4d3f3fd135debf1464ad0f057723ea492f957de5/tee-worker/enclave-runtime/src/initialization/global_components.rs#L91

And 

https://github.com/apache/incubator-teaclave-sgx-sdk/blob/6ee75754f0343a1a2c70125ed907556048a0cbc4/sgx_crypto_helper/src/rsa3072.rs#L24-L40

**Comment by jingleizhang** [comment]
Why it is not safe?
