### ISSUE TITLE
Clean-up the token bridge relayer documentation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1363]
### Context
We have token bridge relayer documentation scattered in multiple places on notion, some have outdated information.

Let's clean them up and merge them into a single document:
- the document should be under `parachain -> documentation -> operations` (or replace the old ones)
- have all relayer information (old and new)
- have the commonly used contract address
- have the how-to guide to set up a relayer
- (ideally) have the records of all known problems and how we solved them:
   - skipped tx due to relayer downtime
   - nonce too low

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Is this done?

**Comment by BillyWooo** [comment]
It's done. Search 'Token bridge' in notion.
