### ISSUE TITLE
Reduce the number of ETH requests in relayers

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1366]
### Context

We have observed the problem that a massive amount of requests are sent to query the ETH contract address in the token bridge relayers, which causes the rate overflow and then the outage.

It's up to ~300 requests per minute when it's busy!

<img width="304" alt="image" src="https://user-images.githubusercontent.com/7630809/220982201-e2d177e2-93ef-49d4-a97f-a1e4d6e8efdd.png">

Can we find a way to:
- reduce the number of requests?
- or only start the relayers when necessary? ( = someone requests to do a bridge transfer)

Some alternatives if we can't reduce the amount:
-  switch to another API provider?
- or improve the code to support key rotation? (provide a set of keys and rotate keys when needed)
- or have a proxy inbetween that handles key rotation and provides query service to our relayers?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
I vote for **improve the code to support key rotation? (provide a set of keys and rotate keys when needed)**

If no other proper API provider choice.

**Comment by wangminqi** [comment]
The bottom cause of high usage is rooted. This issue is no longer needed.
