### ISSUE TITLE
Automate the tee-staging reset

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1367]
### Context

Due to instability, the tee-workers and parachain on staging need to be reset from time to time. We should be able to automate the deployment instead of doing it manually, in order to:

- save time
- be able to grant the reset permission to more people (e.g. IDHub colleagues). They can do it on demand, even when the parachain team is not there.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
Actually the current 'reset/restart', it's already quite straightforward. There is python launch script, which works well. The time consuming part is rebuild as new code changes.

**Comment by Kailai-Wang** [comment]
I think normally we should just pull the docker instead of building it locally - i.e. normally we shouldn't run any untested binary on it (there're exceptions though).

Maybe we only need to wrap it up with some clean-up beforehand and provide the script to IDH colleagues - then they can restart it on their own. They are the only users on the staging anyway (for the moment)

**Comment by BillyWooo** [comment]
Yes. Maybe I didn't make make myself clean. 
The python launch script pulls docker image and launch local worker binary. It also takes care of clean-up job. I think IDHub colleagues can use it. We need to grant them the access permission.

**Comment by Kailai-Wang** [comment]
I mean we need to pull the worker image as well :) 

(You don't have to launch the workers as docker containers, you can copy the binary out if you want, and then run python)

**Comment by BillyWooo** [comment]
Just for the record, in current tee-worker folder, we can easily execute: `./local-setup/launch.py local-setup/github-action-config-staging.json`

**Comment by jingleizhang** [comment]
Got it, Thanks! @BillyWooo

**Comment by jingleizhang** [comment]
+ @niteshb3495

**Comment by BillyWooo** [comment]
GHA service added: https://github.com/litentry/litentry-parachain/actions/workflows/dev-sgx-restart.yml
