### ISSUE TITLE
ts identity test should cover TEE IMP errors 

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1374]
Currently ts-test `test-identity` covers all happy paths in TEE Identity Management Pallet. 

In this issue, ts-test should make TEE IMP [errors](https://github.com/litentry/litentry-parachain/blob/7681fdea23c39d63e16fb4a9cebac3193b722e95/tee-worker/litentry/pallets/identity-management/src/lib.rs#L93) tested with specific Parachain event returned accordingly.

eg:

- verify two same identities to one account, get `IdentityAlreadyVerified` error
- verify an identity to an account but it isn't created before, get `IdentityNotExist` error
- remove a nonexistent identity from an account, get `IdentityNotExist` error 
- remove a challenge code before the code is set, get `ChallengeCodeNotExist` error
- etc

**Comment by 0xverin** [comment]
got it!

**Comment by 0xverin** [comment]
when verify two same identities to one account, don't get `IdentityAlreadyVerified` error,but get `code not found` error. 
![image](https://user-images.githubusercontent.com/104152026/222876670-e5df4816-242b-432c-9cbf-28dc44afc136.png)
<img width="1492" alt="image" src="https://user-images.githubusercontent.com/104152026/222876865-880bbadb-293b-4a89-a6ec-379f1779b3f5.png">

**Comment by jingleizhang** [comment]
> when verify two same identities to one account, don't get IdentityAlreadyVerified error,but get code not found error.

good catch! Will reproduce it and see whether it is a bug or not.

**Comment by Kailai-Wang** [comment]
Yes - this is actually expected behaviour according to the current code:
- a challenge code is removed when an identity is successfully verified. 
- to verify an identity, having an existing challenge code is the precondition
- if an identity is verified is checked **after** the challenge code check

so it will abort early once no challenge code is found. If you don't see such errors in parachain, it means this error is not properly handled.

If you want to check if an identity is already verified first, we can do that too - just need to change the logic

**Comment by Kailai-Wang** [comment]
About error handling of challenge code: https://github.com/litentry/litentry-parachain/issues/1274

**Comment by jingleizhang** [comment]
The issue is https://github.com/litentry/litentry-parachain/issues/1274. Changed its priority to High.

I have it reproduced: `verify two same identities to one account`, there is only the error `Stf execute failed: Dispatch("code not found")`, but not any error event returned to parent chain.

**Comment by Kailai-Wang** [comment]
#1274 is resolved now => please feel free to test it via ts

**Comment by 0xverin** [comment]
Therefore, challenge not found should be the first judgment. In the process of testing, I often get the result that `code not found`,right?
