### ISSUE TITLE
monitor and alert for tee-staging Error log

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1377]
It monitors the worker logs on `tee-staging`, and when there are some Error logs, it would send an alert to slack.

The bash example: https://stackoverflow.com/questions/51136881/bash-to-slack-error-log-report

**Comment by niteshb3495** [comment]
@Eric - as discussed, please share the example/word to grep from the log file.

**Comment by jingleizhang** [comment]
shared on the slack

**Comment by jingleizhang** [comment]
Close this issue since the alert is enabled.
