### ISSUE TITLE
Test upgrading of non-enclave part of workers only

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1379]
### Context

Theoretically it's compatible if we only update the non-enclave part of the worker while using the same enclave (e.g. ~~the indirect-call-executor handling logic~~ (it's inside the enclave)), is that case? 

This needs to be tested - a manual test is enough.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
It's tested manually, the upgrading works.
