### ISSUE TITLE
XCM v2 -> v3 

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#1384]
So the XCM will have V3 soon. The V2 Multilocation or XCM message format will be discorded in future.

It is neccessary to check if we need to implement new logic in runtime (for v3 adjustment), or if any storage containing a v2 content such that, a migration is needed.

**Comment by wangminqi** [comment]
https://github.com/open-web3-stack/open-runtime-module-library/pull/886

**Comment by BillyWooo** [comment]
For record: https://github.com/litentry/litentry-parachain/pull/1607
