### ISSUE TITLE
Enable pallet-identity on parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1390]
### Context

We need to:
- [x] double-check runtime configs
- [x] adjust baseCallFilter
- [x] runtime upgrade

Applied to both litmus and litentry (and rococo).

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
Instead of baseCallFilter, it seems to be more reasonable adding in normalFilter.
