### ISSUE TITLE
IDGraph in ts-test should reflect the accurate content

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1395]
### Context
Currently we only test if an expected identity _exists_ in the returned IDGraph:
https://github.com/litentry/litentry-parachain/blob/471faeea13cc4ccc1ccd8984abad0b468d59d942/tee-worker/ts-tests/identity.test.ts#L318-L322

This is not optimal: what if it contains more identities than it should have?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
resolved in #1577
