### ISSUE TITLE
assertion build panicked due to Uft8Error

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1397]
Error logs:

`<unnamed>' panicked at 'called Result::unwrap() on an Err value: Utf8Error { valid_up_to: 2, error_len: Some(1) }', /home/ubuntu/repo/litentry-parachain/tee-worker/litentry/core/assertion-build/src/a4.rs:[2023-03-02T15:21:08Z INFO  integritee_service::ocall_bridge::sidechain_ocall] Enclave produced sidechain blocks: [17032]`

`fatal runtime error: failed to initiate panic, error
thread 'thread '<unnamed><unnamed>' panicked at '' panicked at 'called Result::unwrap() on an Err value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)called Result::unwrap() on an Err value: Sgx(SGX_ERROR_ENCLAVE_CRASHED)', ', service/src/main.rsservice/src/main.rs::638499::8118
[2023-03-02T15:21:16Z ERROR integritee_service] Parentchain block syncing terminated with a failure: EnclaveApi(Sgx(SGX_ERROR_ENCLAVE_CRASHED))`

**Comment by Kailai-Wang** [comment]
Basically we shouldn't have any panics (unwraps) inside the enclave : #1227
