### ISSUE TITLE
Add a configurable "startBlock` for parentchain block importer

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1399]
### Context
I'm thinking maybe it's helpful to add a `--parentchain-start-block` parameter to the tee-worker, so that it doesn't have to sync the parentchain from the beginning. 

It will save a lot of time when we deploy the worker to the real chains (rococo/litmus/litentry)

Medium prior as it's nice-to-have.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
The initialization includes:

1. in service: https://github.com/litentry/litentry-parachain/blob/0fed9a4cefb0cc96d9c9e8e5b0c6bdaeadc0a838/tee-worker/service/src/parentchain_handler.rs#L85-L89
2. in enclave: https://github.com/litentry/litentry-parachain/blob/0fed9a4cefb0cc96d9c9e8e5b0c6bdaeadc0a838/tee-worker/core-primitives/enclave-api/src/enclave_base.rs#L268-L276

the `startBlock` or `startHash` should be added to above two function parameters.
