### ISSUE TITLE
run ts-test on tee-staging every hour or every two hours

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1417]
started by crontab on `tee-staging`

**Comment by Kailai-Wang** [comment]
Beware this might interfere with simultaneous IDH development on that host - what's the use case of this test? The images should be ts-test proof (otherwise CI won't pass)

**Comment by jingleizhang** [comment]
It's for external API testing. We can check their availability somewhere else, close this one.
