### ISSUE TITLE
Crowdloan token distribution script

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#142]
- [ ] Write a script to fetch crowdloan participants list and transfer & vesting_transfer the LIT rewards according to our plan
- [ ] Private key shall be managed in a safe way
- [ ] The script shall be able to handle failed transactions and gather failure events

**Comment by h4n0** [comment]
Thanks for the reviews by @Kailai-Wang and @chenzongxiong . Closed
