### ISSUE TITLE
Use `accountNextIndex` instead of `system.account.nonce`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1425]
### Context

See https://polkadot.js.org/docs/api/cookbook/tx/#how-do-i-take-the-pending-tx-pool-into-account-in-my-nonce

Current `get_nonce_of`:

https://github.com/litentry/litentry-parachain/blob/d9da36695553531b10209e8f6667e4e526c639aa/tee-worker/core-primitives/node-api/api-client-extensions/src/account.rs#L34-L36

We could also keep the original one 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
@Kailai-Wang If this issue is not particularly urgent, we can wait for the version polkadot v0.9.43 if possible. However, haerdib also provides helpful solutions for other versions.

**Comment by Kailai-Wang** [comment]
Upstream PR is merged: https://github.com/scs/substrate-api-client/pull/573

**Comment by outofxxx** [comment]
Wait for an update to the version that includes this method `get_system_account_next_index`

**Comment by Kailai-Wang** [comment]
> Wait for an update to the version that includes this method `get_system_account_next_index`

It's already there I think

**Comment by outofxxx** [comment]
> > Wait for an update to the version that includes this method `get_system_account_next_index`
> 
> It's already there I think

This method is currently on `polkadot-v0.9.39`  branch, and we are currently using `polkadot-v0.9.39-tag-v0.7.0`, just discussed with @BillyWooo , he is already upgrading, so have to wait a little

**Comment by Kailai-Wang** [comment]
Fixed by https://github.com/litentry/litentry-parachain/pull/2475
