### ISSUE TITLE
VC: A5 in ts-test

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1438]
A5 is still unavailable, waiting for Twitter’s new API policy.

**Comment by Kailai-Wang** [comment]
What's the status of this issue?

**Comment by jingleizhang** [comment]
short term:
- [ ] a minor bugfix: https://github.com/litentry/litentry-parachain/issues/1646
- [ ] then we can add a A5 test case in ts-test

long term:
- [ ] a twitter service wrapper needs to be added to tee-microservice: https://github.com/litentry/litentry-parachain/issues/1517

**Comment by 0xverin** [comment]
A5 has been removed.
