### ISSUE TITLE
Collective implementation

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#144]
- [x] Check how are the collective accounts selected in other projects (own account, or same as collator account?)
- [x] Use membership + collective for council and tech committee
- [ ] Fix parameters

**Comment by Kailai-Wang** [comment]
Summary of collective member counts for different chains:
https://www.notion.so/litentry/Collective-members-of-chains-cf151319bc7a4e3ebb38a34264db9522
@Satoshi-Kusumoto
