### ISSUE TITLE
Production deployment: automate instance setup, service deployment/start/restart

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1440]
as the title

**Comment by jingleizhang** [comment]
- [x] automate instance setup from bare metal OVHCloud
- [x] automate tee-worker service env setup and deployment
- [x] automate start
- [x] automate restart(with server access)

**Comment by BillyWooo** [comment]
Something valuable already existed: https://github.com/litentry/litentry-parachain/blob/dev/tee-worker/scripts/litentry/ubuntu_setup.sh

**Comment by Kailai-Wang** [comment]
But please bear in mind that the setup was originally for GHA and it was supposed only to support compilation and execution in SW mode.

**Comment by jingleizhang** [comment]
- [x] make sure the steps are ready
- [x] then upgrade them to some automate tools (e.g, ansible?)

**Comment by niteshb3495** [comment]
The recent servers were configured using ansible and they are running as expected. 
Ansible script is tested.
