### ISSUE TITLE
No trigger of IMPError:: RecoverSubstratePubkeyFailed, but it got executed.

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1446]
### Context
From the source code, IMPError:: RecoverSubstratePubkeyFailed is not triggered from anywhere.  But from the event log, there is `identityManagement.RecoverSubstratePubkeyFailed`. 
![image](https://user-images.githubusercontent.com/14319174/224747082-1338d3eb-595b-40ef-a7e6-cf6ce643285c.png)

Reference: `VerifySubstrateSignatureFailed` is triggered https://github.com/litentry/litentry-parachain/blob/7f33bd9aed424002d3af8a6dce17c4d9019a1137/tee-worker/litentry/core/identity-verification/src/web3/mod.rs#L80

### Task
Clarify the problem, and fix if applicable.
Way to reproduce: 
- checkout git hash: fe7c5b69b9bb1616ec4dd0078ef68cf61fa7b687
- run the worker with 'integritee-node' or 'litentry-parachain'
- run ts-tests: identity.test.ts (comes out from step 'verify identities')

Attention: the Alice address from substrateIdentity is wrong.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I think we need a bit more information :)

- how to reproduce it
- who should look at it
- the labels if possible (mainly the priority)

**Comment by BillyWooo** [comment]
> I think we need a bit more information :)
> 
> * how to reproduce it
> * who should look at it
> * the labels if possible (mainly the priority)

😂   Yes. Still working in the middle. Will update. Actually discussed with Verin before creating this issue.

**Comment by 0xverin** [comment]
This is a strange bug. It is unclear how `recoverSubstratePubkeyFailed` is triggered, it usually only triggers the `VerifySubstrateSignatureFailed` error according to the Rust code.

**Comment by BillyWooo** [comment]
After this [PR](https://github.com/litentry/litentry-parachain/pull/1516), the error doesn't exist any more. So let's close it.
