### ISSUE TITLE
CI flow bug

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1459]
### Context
There are three consecutive `General CI`. 
https://github.com/litentry/litentry-parachain/actions/runs/4417337177
https://github.com/litentry/litentry-parachain/actions/runs/4417412955
https://github.com/litentry/litentry-parachain/actions/runs/4417507004
![image](https://user-images.githubusercontent.com/14319174/225116668-2f74435f-0f84-4dd1-914e-a69837053758.png)

The first two CI failed. The last one passed. But the first two had some changes, which effected parachain docker image rebuilding/uploading. The third didn't upload anything. 

### Task
When there are sequential dev CI operations, make sure they pass one by one. 

### Acceptance criteria
all docker images are uploaded, if applicable.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
> When there are sequential dev CI operations, make sure they pass one by one.

This is very difficult - GHA doesn't have native solutions to keep the status of previous **workflow** runs. You probably need to write some action.yml (js) to achieve it.

And sometimes you do want to run the next workflow even if the previous one fails.

The third PR only modifies the tee-worker ts-tests, or neither parachain nor tee docker image will be rebuilt.
So far everything works as expected.

**Comment by Kailai-Wang** [comment]
We could still leave this issue to someone to do the research, in that case let's set the labels and possible assignees

**Comment by BillyWooo** [comment]
This is not urgent now. Also very rarely happen. Leave it there for the moment.

**Comment by Kailai-Wang** [comment]
Closing it as I don't see it happening
