### ISSUE TITLE
Add specific error words for monitoring

### ISSUE THREAD

**Issue by niteshb3495** [litentry/litentry-parachain#1464]
Add specific error words for monitoring on tee-staging and slack notification for the same. 
More [info](https://litentry.slack.com/archives/C01NT5M9HGR/p1678792066238599)

**Comment by niteshb3495** [comment]
I shared the steps with Eric to update the script on the tee-staging server with the script's location.

**Comment by Kailai-Wang** [comment]
btw the `log::error!` will have `ERROR` keyword already

**Comment by outofxxx** [comment]
We can maintain a list of keywords file to make updating more convenient.
