### ISSUE TITLE
Use clear names for the signer

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1470]
### Context

The current array like defaultSigner is very confusing. When I read something like: `context.defaultSigner[0], context.defaultSigner[1]...` it's hard to figure out which signer it is.

Would it make sense to change it to map-like structure? Like `defaultSigner['alice']`. Maybe it's even better to have something like `signer_alice()` or `get_signer('//Alice')` as it's constructed (globally) from the known account anyway - we don't have to pass them around all the time as `context` members.

@Verin1005 what do you think?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
Yes, I also plan to use the getSigner('name') in #1452,if use `[index]` will not be able to view the log clearly.
