### ISSUE TITLE
Support restart tee-worker only without pruning on staging

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1486]
### Context

Currently when restarting tee-staging, everything is reset (relaychain + parachain + workers).

Sometimes we only want to restart the workers without pruning the state, e.g. when there's a temporary network issue and the worker can't connect to the parachain (we once got DNS error), or when the non-enclave part panics out.

We'd like to provide an additional restart-option to only restart the worker **without pruning the sidechain database**. It helps test the worker resuming too.

Please mind the start parameter difference, if any.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by niteshb3495** [comment]
This requires some more configurations of systemctl scripts.
I was going through some documents, how I can do the same. And found that I need to have different systemctl service files to stop only the required service while keeping the other services running. 
I will make the changes in the systemctl scripts and update the status here again.

**Comment by niteshb3495** [comment]
After checking the script to launch the application, I found that the script itself it killing the process parachain and relaychain. 
To make the changes in systemctl, we first need to change the script to stop killing the process of parachain and relaychain by itself. Unless those changes, everytime I will kill the script, it will also kill the parachain and relaychain services with it.

**Comment by niteshb3495** [comment]
I am trying to make some changes in the systemctl, if I am missing anything here, please let me know.

**Comment by niteshb3495** [comment]
Yang, as discussed on slack, the script and docker containers are tightly coupled. We have to separate the same to stop the worker without stoping the parachain or relaychains.
