### ISSUE TITLE
Add test case for creating more than 20 identities

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1487]
### Context

Follow-up of https://github.com/litentry/litentry-parachain/pull/1478

Mainly to see:
- if IDGraph will be capped
- how large is the returned IDGraph

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
Using `integritee-node` & `parachain` 53515ecb7981f34a69695681076a68b8e61726d3

Creating 22 identities stats: 
`Took 582 secs`
`id_graph 13012 bytes `

Testcase:
https://github.com/zTgx/litentry-test-suit/blob/2d0ba6f558dc0c6774c2946c819c49c8958914ea/tests/test_corner_case.rs#L449-L455

**Comment by outofxxx** [comment]
Need add more tests:

- [x] 50+ / 100 + identites
- [x] using `batch_all` send every group of 10

**Comment by outofxxx** [comment]
🚩 Creating 60 identities stats: 

            >>> Took 34 secs 

            >>> id_graph 52980 bytes 

test tc_batch_all_create_more_than_100_identities_and_check_idgraph_size ... ok

 🚩 Creating 80 identities stats: 

            >>> Took 44 secs 

            >>> id_graph 70360 bytes 

test tc_batch_all_create_more_than_100_identities_and_check_idgraph_size ... ok

 🚩 Creating 90 identities stats: 

            >>> Took 46 secs 

            >>> id_graph 79050 bytes 

test tc_batch_all_create_more_than_100_identities_and_check_idgraph_size ... ok


 🚩 Creating 100 identities stats: 

           No event return.

[testcase](https://github.com/zTgx/litentry-test-suit/blob/908ef94809933bc9395bc34ac82d18bd0283c526/tests/test_corner_case.rs#L531-L537)

**Comment by Kailai-Wang** [comment]
Thank you for the effort 👍 

I just realised the calculation of IDGraph size is probably wrong. The returned IDGraph in the `IdentityVerified` event will contain the current IDGraph of **all linked identities**, capped by 20 (see `IDGRAPH_MAX_LEN` in `trusted_call.rs`). That means you only need to check it once when the last identity is linked.

**Examples:**
- link and verify 1st identity => the IDGraph in the `IdentityVerified` event contains 1 identity
- link and verify 2nd identity => the IDGraph in the `IdentityVerified` event contains 2 identities
- ...
- link and verify 20th identity => the IDGraph in the `IdentityVerified` event contains 20 identities
- link and verify 21st identity => the IDGraph in the `IdentityVerified` event contains 20 identities (latest, the first identity is excluded)
- ..
- link and verify 100th identity => the IDGraph in the `IdentityVerified` event contains 20 identities (81st - 100th)

**Comment by Kailai-Wang** [comment]
So I expect the IDGraph in a similar size starting from the 20th identity.

I'm also wondering why `no event returns` for 100 identities (maybe batch_all limitations?)

**Comment by outofxxx** [comment]
After correcting the calculation method, the current update is as follows:

Created 40 identities, last IdentityVerifiedEvent id_graph(Vec<(Identity, IdentityContext).len() == 20) `<920> bytes` 

[testcase](https://github.com/zTgx/litentry-test-suit/blob/662327b385cf8350c6d9dcdc7c8c2d47e8932621/tests/test_corner_case.rs#L542)
