### ISSUE TITLE
Consider adding more events to TEE-request lifecycles

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1488]
### Context

From the parachain's perspective we only have two events for a TEE request:
- `xxRequested`
- `xxDone` or `xxFailed`

More detailed lifecycle activities will only be printed in the worker logs.
Maybe it's beneficial (especially for ts-tests and later F/E monitor) to propagate the event to the parachain, like when it enters the tx pool, when the trusted call is executed, when the callback extrinsic is sent ...

Not the highest prio.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
@Kailai-Wang I think we want to reduce the amount of events propagated to parachain. Can we close this ?

**Comment by Kailai-Wang** [comment]
Yes let's close this - we only want to have a "final" event signaling the completion (success or failure) of user action
