### ISSUE TITLE
Add required security measures on TEE worker prod servers

### ISSUE THREAD

**Issue by niteshb3495** [litentry/litentry-parachain#1494]
As per the subject

**Comment by jingleizhang** [comment]
- [ ] ports
- [ ] process status monitoring

**Comment by jingleizhang** [comment]
a new subtask:
[] if the tee-worker exits due to panic or was accidentally terminated, a daemon should try to restart it (e.g, daemon will try to restart it 3 times in about 60 seconds. But if tee-worker continues to fail, the daemon will give up and sends alert).
