### ISSUE TITLE
Deliver automation on production env

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1501]
### Context
We need to prepare the automation for deliver process on production env. On production env, there will be only worker(s) running. And it will connect to remote Rococo(Litentry/Litmus) Network.

### Task

- [x] Prepare worker related executable, configs and etc. as a release package by `make release-pkg`. Take the current python script as reference.
- [x] Prepare the service script on production env instance:
    - (re)start the worker
    - stop the worker

### Acceptance criteria
- Launch two worker(s) from production env, sync with RococoNetwork.
- When error happens, workers can be restarted easily, and continue to sync with parachain based on history data.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
- hardware mode 
- with RA, without --dev, 
- binary,
- tee-worker-prod-parameters,
- prod-config,
- scripts

**Comment by Kailai-Wang** [comment]
Please bear in mind the parachain on the prod-env needs to be compiled without `tee-dev` feature, so need potentially a different docker image/binary for the deployment.

I could make it default (that it doesn't include `tee-dev` feature) but we'd still need it for dev env. So it seems that we nevitably need two variants.

**Comment by jingleizhang** [comment]
R1 deployment  was launched. This issue could be closed.
