### ISSUE TITLE
add introductions about teerex pallet on gitbook

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1519]
The pallet is [here](https://github.com/litentry/litentry-parachain/tree/dev/pallets/teerex)

**Comment by jingleizhang** [comment]
draft is [here](https://www.notion.so/web3builders/Teerex-Pallet-02a97296bdae4c038b82ed05fa1e53d4)

**Comment by Kailai-Wang** [comment]
Done
