### ISSUE TITLE
Create a script/GHA to tell if sidechain on staging works

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1522]
### Context

It's possible that we get error notifications from the staging-sidechain but it still functions.

Before we restart it, it's better to test if "it still works" in the first place. We need a script/GHA for that, similar to ts-test but more light-weighted and accurate.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by niteshb3495** [comment]
This is completed along with
https://github.com/litentry/litentry-parachain/issues/1545
