### ISSUE TITLE
Manual tests of removing the second worker during running

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1525]
### Context

Imagine both workers diverge like #1524 
How can we recover from that, or at least allow one worker to continue working?

We should at least test the following:
- stop the second worker when it's still running
- see if worker0 continues working (I assume yes)
- observe the block production interval (I assume 2x the itp setting, as worker1 can't claim the slot now)
- can we modify the registry to reduce worker0's block interval to be the same as the itp setting? Or in general we need some extrinsics to be able to manually modify that

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
We [added](https://github.com/litentry/litentry-parachain/issues/1124) this as a scenario in CI (which we apparently need to disable because our multiworker setup just ain't working).

**Comment by kziemianek** [comment]
Completed in #2316
