### ISSUE TITLE
VC's description, type and tag need to be finalized before release

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1527]
As the title, the actual content of `description`, `type` and `tag` need to be finalized before release.

cc @kaylawangnow @jonalvarezz

**Comment by jingleizhang** [comment]
the discussion is [here](https://litentry.slack.com/archives/C03KR96989G/p1679912815806429?thread_ts=1679652169.257579&cid=C03KR96989G)

**Comment by outofxxx** [comment]
Keeping pace with this page [Assertion requirements record](https://www.notion.so/web3builders/Assertion-GraphQL-data-requirements-record-c982aadb7a314cb58d3c172d6d7eb8e7)

**Comment by kaylawangnow** [comment]
ok
i will follow up

**Comment by kaylawangnow** [comment]
This is the first version cc @zhouhuitian 
https://www.notion.so/web3builders/Assertion-GraphQL-data-requirements-record-c982aadb7a314cb58d3c172d6d7eb8e7 
I think we need a call to re-confirm the requirement - description - implementation matches each other, will set up a call soon

**Comment by outofxxx** [comment]
cc @jingleizhang

**Comment by jingleizhang** [comment]
thanks, let's finish the sync call today. @kaylawangnow @zhouhuitian

**Comment by outofxxx** [comment]
Two questions:
1. Some of these `type` strings have an `Assertion` suffix, while others do not. Do we need to unify?
2. Which query networks does the A8 support?

**Comment by jingleizhang** [comment]
A4/A7/A10/A11 are not finalized, reopen this.

**Comment by outofxxx** [comment]
- [x] A8's description has an extra space

**Comment by Kailai-Wang** [comment]
What's the status of this one? Any assertion that hasn't been finalised?

**Comment by BillyWooo** [comment]
All assertions updated.
