### ISSUE TITLE
Remove duplicate code in TEE ts-tests

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1538]
### Context

I think there's quite some duplicate code in the current TEE ts-tests, like event listening, event creation, tx submission ...

It would be great if we could simplify it. Not in a hurry tho.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
The initial reason for raising this issue was the existence of too many duplicate event listening and tx submission methods. I believe these no longer exist. Can we close it?
