### ISSUE TITLE
Get notified when the staging sidechain doesn't produce blocks

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1545]
### Context

I accidentally logged onto the tee-staging server and found that worker0 hasn't been producing blocks for **1 h** and worker1 hasn't been producing blocks for **6 h**.

We would need at least some notifications for this.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
#1522 can be done together.

**Comment by jingleizhang** [comment]
Slack alert is done.
