### ISSUE TITLE
wrong nonce in tee-test (demo-indirect-invocation) 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1549]
### Context

Happened a few times as well, see https://github.com/litentry/litentry-parachain/actions/runs/4537333126/jobs/7996627645#logs

When sending 3 transfer requests back to back, the nonce is not continuously incremented:
```
integritee-indirect-invocation-demo  | * Send 3 consecutive 0.2 UNIT balance Transfer Bob -> Charlie
integritee-indirect-invocation-demo  | send trusted call transfer from 5CCimpxmFnUWgLZ1G996QMZ1JPqdfnQCYxtcZngjDKDvLrPi to 5H9J7K6HqKmshiLGWukPnVB2GMyaGyN8cSdVXKXekG7qgLfU: 200000000000, nonce: 0
integritee-indirect-invocation-demo  | send trusted call transfer from 5CCimpxmFnUWgLZ1G996QMZ1JPqdfnQCYxtcZngjDKDvLrPi to 5H9J7K6HqKmshiLGWukPnVB2GMyaGyN8cSdVXKXekG7qgLfU: 200000000000, nonce: 0
integritee-indirect-invocation-demo  | send trusted call transfer from 5CCimpxmFnUWgLZ1G996QMZ1JPqdfnQCYxtcZngjDKDvLrPi to 5H9J7K6HqKmshiLGWukPnVB2GMyaGyN8cSdVXKXekG7qgLfU: 200000000000, nonce: 1
```

Medium prio as it comes from direct calls

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
In the error cases, you would see 0-0-1 or 0-1-1 for the nonces of three consecutive balance transfers.

I thought it was some race condition regarding the top status (like you queried the nonce too early before the state was mutated), but that shouldn't be the case: it's a `direct` invocation, so it returns synchronously when the status watcher is triggered.

In the happy path, it would return when the top is included in a sidechain block: `InSidechainBlock`. By then the sidechain block should be imported already which contains the new state (hence the new nonce).

https://github.com/litentry/litentry-parachain/blob/eb988f41b6362fd27fc369bcd48186690e0d088f/tee-worker/cli/src/trusted_operation.rs#L329

We are only sending the request to one of the workers.

Currently I have no idea why it could happen, maybe the top status is somehow unexpected and the command-line returns earlier than expected - before the stf is executed and included in a block.

I'll keep this issue open and simply adjust the CI logs, hopefully we can have more info later.

**Comment by Kailai-Wang** [comment]
Happend again: https://github.com/litentry/litentry-parachain/actions/runs/4790199741

Unfortunately the log level was still too tight

[logs-demo-indirect-invocation.zip](https://github.com/litentry/litentry-parachain/files/11314579/logs-demo-indirect-invocation.zip)

**Comment by Kailai-Wang** [comment]
I believe the root cause is we mistakenly use offchain-worker mode in our tests:
https://github.com/litentry/litentry-parachain/blob/eab06f3b13d44189cab9beecde74b725f178a649/tee-worker/docker/demo-indirect-invocation.yml#L20

As a result, `CALLTYPE` will be empty, thus we are always sending indirect calls:
https://github.com/litentry/litentry-parachain/blob/eab06f3b13d44189cab9beecde74b725f178a649/tee-worker/cli/demo_shielding_unshielding.sh#L78-L84

We could have race conditions there:
- the command line will return as soon as the indrect call is processed by the worker, but that doesn't necessarily mean the state is changed (not to mention that sidechain block production could fail)
- the following command will query the nonce state which might be unchanged until a sidechain block is produced

Hence the unexpected nonce.

**Comment by Kailai-Wang** [comment]
cc @clangenb

If you occasionally see such nonce errors (0-0-1 or 0-1-1) in your `demo-indirect-invocation` tests, particularly with `offchain-worker` mode, then I assume it's caused by the race condition above. An easy way out is to wait a few seconds in between, or poll until the nonce has the correct value in the end.

**Comment by clangenb** [comment]
Hmm, I see, thanks for letting me know! Yeah, this makes sense. According to my understanding, the time window is quite small for this race condition to occur. Can you confirm that this happens only rarely?

**Comment by Kailai-Wang** [comment]
> Hmm, I see, thanks for letting me know! Yeah, this makes sense. According to my understanding, the time window is quite small for this race condition to occur. Can you confirm that this happens only rarely?

Yes it only happens rarely.
And it should _only_ happen under `offchain-worker` mode, not `sidechain` mode. If that's not the case somehow, we need to look into it

**Comment by clangenb** [comment]
I will keep track of it in our repo. Thanks for sharing. cc @OverOrion, @coax1d
