### ISSUE TITLE
Restarting worker should continue with parentchain syncing

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1556]
### Context

When restarting the worker, the parentchain block syncing should start with where it was left off.

That isn't the case for now, why? How to fix it?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
First try:

I used one worker.
Restarting seems to work: the worker can continue from where it was left and:
- sync further with the parentchain
- continue with sidechain block production

**Comment by jingleizhang** [comment]
good news!

**Comment by Kailai-Wang** [comment]
If you tested it and got the same result -> we can close the issue

**Comment by jingleizhang** [comment]
Tested it with one worker and '--skip-ra --dev', the `sync further with the parentchain` and `sync further with the parentchain` both continued.
