### ISSUE TITLE
Adjust restart worker GHA

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1560]
### Context

We need to make a few adjustments of `dev-sgx-restart.yml`
- differentiate between reset and restart
- discard python command
- better naming

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Hold on until @BillyWooo goes further with production deployment

**Comment by BillyWooo** [comment]
This is not valid any more. `dev-sgx-restart.xml` is removed. New deployment process will be [merged](https://github.com/litentry/litentry-parachain/pull/1526).
