### ISSUE TITLE
Script to move VCRegistry snapshot

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1564]
### Context

precondition: https://github.com/litentry/litentry-parachain/issues/1544

We need a script to move a snapshot of VCRegistries of a given chain to another:
- query the storage of the VCRegistry of a given chain (e.g. staging)
- store it as human-readable format, e.g. JSON, with timestamp
- generate an encoded extrinsic call which adds these entries to a new VCRegistry in another chain, using utility batch (so it should be one call).
- test the workflow.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
- [ ] implementation
- [ ] manually test

**Comment by 0xverin** [comment]
[VCRegistry](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L74) only return vcIndex and vccontext(subject,hash,status),but [`add_vc_registry_item`](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L394) needs an `assertion` parameter,where did this assertion come from, it seems impossible to know VCRegistry data belongs to which assertion.Am I mistaken? Please guide me.

**Comment by Kailai-Wang** [comment]
> [VCRegistry](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L74) only return vcIndex and vccontext(subject,hash,status),but [`add_vc_registry_item`](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L394) needs an `assertion` parameter,where did this assertion come from, it seems impossible to know VCRegistry data belongs to which assertion.Am I mistaken? Please guide me.

VC_Context does have the field `assertion`: https://github.com/litentry/litentry-parachain/blob/4565843211a5bb2550504434c16255e97117f5da/pallets/vc-management/src/vc_context.rs#L41

**Comment by 0xverin** [comment]
> > [VCRegistry](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L74) only return vcIndex and vccontext(subject,hash,status),but [`add_vc_registry_item`](https://github.com/litentry/litentry-parachain/blob/dev/pallets/vc-management/src/lib.rs#L394) needs an `assertion` parameter,where did this assertion come from, it seems impossible to know VCRegistry data belongs to which assertion.Am I mistaken? Please guide me.
> 
> VC_Context does have the field `assertion`:
> 
> https://github.com/litentry/litentry-parachain/blob/4565843211a5bb2550504434c16255e97117f5da/pallets/vc-management/src/vc_context.rs#L41

Thanks,I checked in the browser this afternoon and there is no such field,may be I should update code.

**Comment by 0xverin** [comment]
script:https://github.com/litentry/ID-HUB-launch-script/blob/main/move-vcregistry-snapshot-script.ts please review
