### ISSUE TITLE
Request A5 : Could not decode `Call::some_error::account`

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1566]
### Context

Request A5 with an invliad A5 Inputs:
```rust
    let original_tweet_id = ParameterString::try_from([].to_vec()).unwrap();
    let a5 = Assertion::A5(original_tweet_id);
```

[TESTCASE](https://github.com/zTgx/litentry-api-client/blob/afdbbc831197648d42964ab4796cc2f80d93566e/tests/test_vc_management.rs#L475)

outputs:
`[2023-04-04T04:22:06Z ERROR integritee_service::ocall_bridge::worker_on_chain_ocall] Could not send extrsinic to node: RpcClient(Extrinsic("extrinsic error code 1002: Verification Error: Runtime error: Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `RuntimeCall::VCManagement.0`:\n\tCould not decode `Call::some_error::account`:\n\t\tunexpected first byte decoding Option\n: RuntimeApi(\"Execution failed: Runtime panicked: Bad input data provided to validate_transaction: Could not decode `RuntimeCall::VCManagement.0`:\\n\\tCould not decode `Call::some_error::account`:\\n\\t\\tunexpected first byte decoding Option\\n\")"))`

**Comment by jingleizhang** [comment]
good catch, thanks!
