### ISSUE TITLE
Explore use of pallet-proxy for authorised identiy verification

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1604]
### Context

The substrate [standard proxy pallet](https://wiki.polkadot.network/docs/learn-proxies) provides a natural way of delegating another account to execute pre-defined actions on behalf of the real account.

It's better than passing live signature regarding efficiency - all state is already stored on chain.

Maybe it's enough to meet our requirements already

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/Parachain-Potential-Usage-of-Pallet-Proxy-fc87721219a34c4d8ac829cff58f093a

The document above is also linked in our old pallet doc.
https://www.notion.so/web3builders/Proxy-9842349bef944f8daa32a5c4d6c60718
