### ISSUE TITLE
Add monitor/statistics of block-import time consumption

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1611]
### Context

We are interested in:
- time that it takes to import a sidechain block
- time that it takes to import a parentchain block

Either of these taking too long could imply a network problem.

Our R1 setup got a such problem. There we experienced a lasting bad network: syncing and importing a single parentchain block took 10s+. This prevented sidechain from composing the block as the time was already used up. If the import took longer than the parentchain block interval (12s), it went from bad to worse as it increased the time diff and the sidechain fell behind further.

Maybe there are built-in histograms already?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by felixfaisal** [comment]
I think this is already present in the code, We just need to use a grafana dashboard to view the frequency, So closing this issue as completed.
