### ISSUE TITLE
Intel SGX whitelist registration 

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1618]
### Context
In order to work in production mode, SGX enclave signer must be added to Intel SGX whitelist.

### Task
Contact Intel and get the whitelist registration done.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
won't do - we switch to dcap
