### ISSUE TITLE
add new feature (command/extrinsic) to get full storage of IDGraph

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1619]
### Context
As title, currently this feature is missing. There is no chance to get full picture of all IDGraphs.
There is a command in CLI (get-storage). But it doesn't fulfill the purpose.

### Task
Add this new feature, and test.

- [x] impl `id-graph-stats`  in cli
- [x] add ci
- [x] test it on stagin env with @BillyWooo 

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
Can we get the number of identities in each IDGraph?Or better yet, can we get the identity content of each idgraph?

**Comment by BillyWooo** [comment]
> Can we get the number of identities in each IDGraph?Or better yet, can we get the identity content of each idgraph?

Unfortunately, not yet.

**Comment by Kailai-Wang** [comment]
Priorisite this - we need it to be able to finalise the closing of the staging
