### ISSUE TITLE
Have an automated release process for the worker and enclave

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1628]
### Context

We are still missing the release process for the TEE-related stuff:
- scripts to automate the release-build and packaging
- version and release cycle management
- differentiate between dev and prod version? (where to build it for HW mode?)

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
@felixfaisal you might be the best person for this - are you interested in it? :)

**Comment by felixfaisal** [comment]
Yup, I can take this up

**Comment by BillyWooo** [comment]
Just some comment during deployment:
- deploy binary package (no dependency with repo)
- save config file (key/tokens/etc.) to a specific location on server
