### ISSUE TITLE
Update upstream to commit `e78c314d`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1629]
### Context

As topic.
There are a few essential commits that we'd like to pull in.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Latest commit is `64703b8` now 

Edit: latest is `f6353f8`

**Comment by BillyWooo** [comment]
Edit: latest is `e78c314d`
