### ISSUE TITLE
ts-test filter events with extrinsic index

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#1630]
The current implementation of `listenEvent` (in `tee-worker/ts-tests/common/transactions.ts`) relies on the signer id to correlate events to their respective extrinsics when multiple calls are submitted concurrently; this works under the current assumptions of our testing environment but is not the ["proper"](https://polkadot.js.org/docs/api/cookbook/blocks/#how-do-i-map-extrinsics-to-their-events) way of doing this.

NOTE: we should be able to identify each extrinsic (once submitted) by its block height and index within the block (rather than by its hash or other markers, see [here](https://wiki.polkadot.network/docs/build-protocol-info#unique-identifiers-for-extrinsics)). We have yet to find a straightforward way to get this mapping when the extrinsics are grouped within a `batchAll` call.

**Comment by arieljbirnbaum** [comment]
Decided to leave this issue for later, after discussion with @Kailai-Wang. I'll flesh out the description to provide context for later.

**Comment by 0xverin** [comment]
This issue no longer seems to need to be implemented, as we use `req_ext_hash` as a flag for matching events.
