### ISSUE TITLE
Indicate F/E-breaking changes in PR tag

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1634]
### Context

Sometimes a PR could break the F/E usage (mainly IDHub right now).

It's better to:
- add a tag (category) for such changes, e.g. `F/E-breaking` (other names are welcome)
- auto-highlight them in the release log

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wli-pro** [comment]
Will close this one, once we verify the tags in next release note

**Comment by wli-pro** [comment]
will raise seperate issue if seeing issue during release.
