### ISSUE TITLE
Provide a list of achainable queries

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1638]
### Context

As topic, we mainly use it inside TEE assertion building.
It's a premise for the API upgrade

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
[achainable queries inside assertions](https://www.notion.so/web3builders/achainable-queries-by-assertion-building-inside-TEE-8772783cfed941fe820c68800d61c87c)

**Comment by Kailai-Wang** [comment]
> [achainable queries inside assertions](https://www.notion.so/web3builders/achainable-queries-by-assertion-building-inside-TEE-8772783cfed941fe820c68800d61c87c)

I think achainable needs a complete request (= query URL) that we use

**Comment by outofxxx** [comment]
Ok, updated.
Add full request URL.

**Comment by outofxxx** [comment]
I think this mission is done.
