### ISSUE TITLE
Refactor VerifiedCredentialsNetwork

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1639]
Related PR: https://github.com/litentry/litentry-parachain/pull/1534

There are two issues here that need to be refactored
- [ ] The name of `VerifiedCredentialsNetwork` is a bit unclear
- [ ] `VerifiedCredentialsNetwork` and `IndexingNetwork` are repeated, they should be one-to-one relationship, just keep one

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
Here's the releted issue https://github.com/litentry/litentry-parachain/issues/1654,  Can do it together.

**Comment by Kailai-Wang** [comment]
What's the status of it? It's been two weeks :(
