### ISSUE TITLE
bug: a wrong parameter in twitter /1.1/friendships/show.json

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#1646]
There is a bug during A5 credential generation:

`[2023-04-13T08:55:38Z DEBUG itc_rest_client::http_client] request: Request { inner: RequestBuilder { uri: Uri { inner: "https://api.twitter.com/1.1/friendships/show.json?source_screen_name=someuser&target_id=litentry", scheme: RangeC { start: 0, end: 5 }, authority: Some(Authority { inner: "api.twitter.com", username: None, password: None, host: RangeC { start: 0, end: 15 }, port: None }), path: Some(RangeC { start: 23, end: 49 }), query: Some(RangeC { start: 50, end: 100 }), fragment: None }, method: GET, version: Http11, headers: Headers({Ascii("user-agent"): "integritee/0.9.0", Ascii("Referer"): "https://api.twitter.com/1.1/friendships/show.json?source_screen_name=someuser&target_id=litentry", Ascii("connection"): "close", Ascii("Host"): "api.twitter.com", Ascii("authorization"): "Bearer xxx"}), body: None, timeout: Some(3s) }, connect_timeout: Some(3s), read_timeout: Some(3s), write_timeout: Some(3s), root_cert_file_pem: None }
[2023-04-13T08:55:40Z WARN  lc_assertion_build::a5] Assertion5 query_friendship error:RequestError("HttpError(403, \"Forbidden\")")`

We can see the above url is /1.1/friendships/show.json?**source_screen_name=someuser&target_id=litentry**, but the correct second parameter should be **target_id={litentry's twitter user id}** or **target_screen_name=litentry**.

**Comment by jingleizhang** [comment]
discussion is [here](https://litentry.slack.com/archives/C03KR96989G/p1681376234859149)

**Comment by Kailai-Wang** [comment]
It's always important to fix known bugs in the product, prioritise it.

**Comment by Kailai-Wang** [comment]
What's the status of this one?

Or maybe you know more about it regarding `target_name` or `target_id` :) @kziemianek

**Comment by kziemianek** [comment]
@Kailai-Wang I can confirm the bug exists.
