### ISSUE TITLE
Have a maximum length for IDGraph

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1648]
### Context

Currently we don't have an upper bound for IDGraph vector, but we do have a limit when pushing the it into `vec_identity` when building assertions.

It makes less sense if identities in IDGraph can't participate in the assertion building. IMO it's better to cap it on IDGraph instead of `vec_identity`

https://github.com/litentry/litentry-parachain/blob/93737c4164463966e99e937d78df50dd9d5837d8/tee-worker/app-libs/stf/src/trusted_call_litentry.rs#L217-L228

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
In the next commit I'll remove limit from the `request_vc` function
