### ISSUE TITLE
based on upstream, refactor indirect-call-executor 

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1649]
### Context
There is refactored code of indirect-call-executor from upstream. Need to apply it to our local worker.

### Task
based on upstream, refactor indirect-call-executor .
There is already some work done in branch: `update_upstream_worker_indirect_call`

Currently blocked at: filter_into_with_metadata and ParseExtrinsic::parser 
It's not easy to extend the current filter to include Litentry indirect calls.

### Acceptance criteria
Try to find a solution: either to change from upstream, or adapt/refactor local code. The target is to achieve the minimum difference between upstream and local. 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Upstream commit: https://github.com/integritee-network/worker/commit/6ea67f8529ba58d2586dbf6d4f83722d7c06ffea

**Comment by Kailai-Wang** [comment]
solved by https://github.com/litentry/litentry-parachain/pull/1738
