### ISSUE TITLE
Switch to new achainable REST API

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1654]
### Context

The graphQL APIs are deprecated.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
Is there an API reference doc or do we have to cobble it together by playing with https://app.achainable.com/labels/create ?

**Comment by Kailai-Wang** [comment]
There's no doc from achainable for now - so yea we have to play around it and ask them directly if we have questions.

Luckily we are only using two of their APIs at the moment

**Comment by outofxxx** [comment]
FYI: [achainable queries by assertion building inside TEE we are currently using](https://www.notion.so/web3builders/achainable-queries-by-assertion-building-inside-TEE-8772783cfed941fe820c68800d61c87c)
