### ISSUE TITLE
ts-test needs to delay the querying on the sidechain storage.

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#1667]
https://github.com/litentry/litentry-parachain/actions/runs/4901317838/jobs/8752534190?pr=1665

The CI error is caused by querying the state immediately after processing the event, while the storage has not been updated yet. Have previously checked this with @zhouhuitian . Therefore, when querying sidechain storage in ts-test, need to wait for a moment before querying.

**Comment by Kailai-Wang** [comment]
One sec, shouldn't the storage be updated already? The emission of parachain events should be after the state mutation in sidechain 🤔

**Comment by 0xverin** [comment]
I couldn't reproduce the issue with `parachain`. However, it can be reproduced with `integritee-node`(although the issue disappeared when I delayed the query by 6 seconds).Discussed with @zhouhuitian , it's possible that this issue is related to sidechain synchronization. Therefore, would it make sense to add a 6-second delay before every sidechain query? Although the issue has only occurred once in the CI, it is a real problem.
<img width="2177" alt="image" src="https://user-images.githubusercontent.com/104152026/236997831-ab8ca983-3905-43a0-a363-e6042343df20.png">

**Comment by Kailai-Wang** [comment]
It happened once today: https://github.com/litentry/litentry-parachain/actions/runs/5071810062/attempts/1

Logs attached.
[logs-lit-identity-test.zip](https://github.com/litentry/litentry-parachain/files/11558499/logs-lit-identity-test.zip)

It looks like worker0 had some network issues and couldn't connect to parachain or other sidechain workers - hence no sidechain block was imported => the storage was unchanged => query failed.

More like a random issue to me (and a delay won't help in this case)

**Comment by Kailai-Wang** [comment]
It's getting more often somehow -- can you take a look at it? :) @Verin1005 @higherordertech

**Comment by 0xverin** [comment]
`setShieldingKey` can reproduces this issue  when tested locally with the `integritee-node`. I noticed @grumpygreenguy  has already added a [delay](https://github.com/litentry/litentry-parachain/pull/1662/files#diff-7565f370728b7b374aac1f3439cdde21f46979cc112e9eee399724bb3bcb8700R107) here.

**Comment by 0xverin** [comment]
Since this issue is not limited to `setShieldingKey`, I added a [6-second delay](https://github.com/litentry/litentry-parachain/pull/1703/files#diff-4d8495b4fb8e1dfb6e030392f5001a7dc022138f1229f4f79ac4978aa9fa7a16R146) in all storage queries to ensure that the data is updated when performing the queries.I hope this can resolve the problem.
