### ISSUE TITLE
Dissect `tee-worker/ts-tests/common/utils.ts` 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1668]
### Context

`tee-worker/ts-tests/common/utils.ts` is only getting more bloated when we add more helpers. Maybe it makes sense to split it into smaller files depending on the applied areas, e.g.:
- crypto/enc/dec
- interaction with parachain
- interaction with sidechain
- ...

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wli-pro** [comment]
Hey @Verin1005, I will work on the PR for this issue.
