### ISSUE TITLE
Add GHA to set token-bridge webapp to maintenance mode

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1669]
### Context

A bit more automation to allow devs to set the token bridge webapp page under maintenance if something goes wrong and the maintainer (currently @Verin1005) is occupied.

We could have a few modes that will adjust the web page in different ways:
- with extra warning information, when e.g. the ETH is very crowded and significantly longer waiting time is expected (maybe this is integrated in the webapp already?)
- down for maintenance, when the token bridge service goes down or shouldn't be used
- back to normal

Additionally, we could set up webhook notifications (e.g. slack channel) for such events, so that e.g. community colleagues get informed.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
If the gas price and tx spending meet the conditions we set, then the website will be put in maintenance mode directly. If not, the website will be displayed normally. 

Currently, the trigger condition for the pop-warning is:

1. eth gas price > 35.

2. txs pending >= 10.

(The py service has not been deployed successfully and needs to be confirmed by @niteshb3495  again.)

Note:maintenance should only be triggered manually.

**Comment by 0xverin** [comment]
[Github Action](https://github.com/litentry/applications/actions/workflows/set-maintenance.yml)

I think this issue can be closed now.
