### ISSUE TITLE
Use latest `polkadot/*` packages in ts-test

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1679]
### Context

Follow-up task of https://github.com/litentry/litentry-parachain/pull/1675

both parachain ts-tests/ and tee-worker/ts-tests
The types need to be re-generated.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
`@polkadot/typegen` still cannot be upgraded,[this issue comment](https://github.com/polkadot-js/api/issues/5540#issuecomment-1469858228) has been mentioned.

**Comment by Kailai-Wang** [comment]
Deprioritise it.

We can live with `typegen 9.x`
