### ISSUE TITLE
Follow-up of DI: juxtapose DI with II for performance benchmarking 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1683]
### Context

We would like to have a quantitative comparison between direct and indirect invocation, so we can theoretically predict how much time we could spare.

We can start with simple scenarios like measuring the time spent on DI and II requests with the same parameters, repeating a few times and comparing the average.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Prioritise it

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang something along the lines of:

- [ ] Prepare a list of request scenarios to test
- [ ] Set up a fresh instance
- [ ] Spam the scenarios against the instance using II; measure latency & throughput
- [ ] Reset the instance and repeat the test using DI; compare results

?

**Comment by Kailai-Wang** [comment]
Yea something like that - eventually it can be one of the CI tests or a GHA that can be manually triggered

**Comment by arieljbirnbaum** [comment]
> eventually it can be one of the CI tests

In my experience, running performance tests on CI tends to end in tears ;D

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang is the II/DI comparison still relevant, or is it superseded by the DI stress tests?
