### ISSUE TITLE
Review the code difference to upstream once

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1687]
### Context

Recently we have realised some **patches** might be incorrectly applied. Hence we'd like to revisit the codebase difference to upstream once just to be on the safe side.

Basically we need to:
- generate the diff between upstream codebase and ours
- review the code difference to make sure all changes are litentry-specific, and we don't miss any critical parts from upstream

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
Let's do it together.
