### ISSUE TITLE
Feature request: validate user's shielding key on request transactions

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#1704]
### Context
For multiple reasons, a client's user shielding key can get out of sync with the Enclave's user shielding key. For example:

Using the IdentityHub
* In BrowserA, set your shielding key.
* In BrowserB, set your shielding key
* Link an identity using Browser A
* BrowserA (the client) now has a different user shielding key than the one the Enclave has.

Clients will realize this once the response comes back from the enclave and decryption fails. This involves high waiting times and fees for the user.

Since allowing clients to fetch the user shielding key from the Enclave is challenging and may compromise security, we want the Parachain to fail earlier under the above scenario.

### Suggestion
Accept an optional parameter in all requests. 
* This parameter is encrypted using the user shielding key in the client. 
* If included, the Parachain will try to decrypt it and reject the transaction if it fails.

Alternatively, we could require clients to encrypt the entire Payload using both the user and the enclave shielding key, but then it will require a joined release of IDHub and Parachain, and it will break any other client out there, if any.

### Other possible solutions from the client side 
Here are some other ideas we discussed to address this issue from our side. Happy to hear other ideas.

* Clients can remember when was the user shielding key set and, with the help of an indexer, check if the saved event data matches to the latest `identityManagement.UserShieldingKeySet` event emitted by the Parachain for a given user.

**Comment by Kailai-Wang** [comment]
I'll create an issue regarding trusted getter, which hopefully can cover the needs of this feature request.

**Comment by Kailai-Wang** [comment]
superseded by #1706
