### ISSUE TITLE
Follow-up of DI: public getter of account nonce

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1710]
### Context

To construct and sign a trusted call, we'd need to include the account nonce to avoid replay/double-spend attack.

We don't have such direct getter yet (or do we?) - if that's the case, we should implement it.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
Here already has a method to get nonce, can it meet the demand?

https://github.com/litentry/litentry-parachain/blob/e4984657c776807c329cad5a9755fb85baedfc83/tee-worker/app-libs/stf/src/getter.rs#L153-L158

**Comment by Kailai-Wang** [comment]
It's trusted getter - I'm thinking a public getter is better
