### ISSUE TITLE
Connect the worker to litentry-rococo parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1712]
### Context

Eventually (for R2) we'd like to use litentry-rococo parachain as the endpoint for tee-worker - we should test it out. If it works we should consider switching the staging or internal env to it.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Friendly ping :) this is important for us to migrate the parentchain to any production chain

**Comment by hanwencheng** [comment]
Any updates?

**Comment by felixfaisal** [comment]
So to do the above we have to perform the following steps: 

- [ ] Perform Runtime Upgrade for the litentry Parachain on Rococo (if we need latest logic changes present) 
- [ ] Check the Teerex Admin and whitelist `MRENCLAVE` 
- [ ] Update the configs for the `worker` and more precisely the `parentchain sync block` and `Parachain URL` 
- [ ] Which server will this worker run on? 

@Kailai-Wang @BillyWooo Let me know if I'm missing something here.

**Comment by Kailai-Wang** [comment]
Closed by #2400 - we'll switch to litentry parachain directly
