### ISSUE TITLE
Make sure (sidechain) metadata and types are up-to-date

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1716]
### Context

When making changes to parachain and sidechain, the metadata can be easily changed without much notice when we e.g. change an enum, or pallet events, errors etc.

This can easily cause codec error in ts-tests. Therefore:
- for parachain, we should always use the metadata from the live query
- for sidechain, we should either:
   - allow live query, which is unimplemented as of now, or
   - add a GHA to automatically update the metadata and generated types when something changes

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
Superseded by #2087
