### ISSUE TITLE
Create new assertions based on current new Achainable API (tag1: Account)

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1718]
### Context
Our data provider TDF's product [Achainable](https://achainable-stage.vercel.app/?achainableLabels=true&userLabels=true&searchText=&chain=All+chains&tag=All+tags&view=list) has developed new API to query data. There are quite many labels provided by Achainable. They are grouped by tags: Account, Balance,  Dotsama, Bridge, etc.

### Task
Covert existed labels into assertions. Start from tag: Account.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
Pay attention to the naming issue when replacing the new API, refer to the discussion here

https://github.com/litentry/litentry-parachain/pull/1721

**Comment by Kailai-Wang** [comment]
Have we done everything? Can we close this issue (and its siblings)?

**Comment by kziemianek** [comment]
@BillyWooo / @zhouhuitian what's the status of this issue ?

**Comment by BillyWooo** [comment]
As discussed [here](https://github.com/litentry/litentry-parachain/pull/1986#issuecomment-1667263786), we can close this issue for the moment. If further new assertion requirement comes, create new issue.
