### ISSUE TITLE
Weight and Fee implementation (cont.)

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#172]
After litentry/research-force#61
The next step is to determine weighToFee coefficients. 

- [x] runtime unit test for transaction fee
- [x] Colletct other projects fee of Transaction (in USD)
- [x] Get a formula of our fee of transaction (in USD) with weightToFee parameters
- [x] Discussion
- [x] implementation

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Transaction-fee-parameter-solutions-c1eb99dec018498fae90dc101fb666b1

For solution plans.
