### ISSUE TITLE
Failing tee-test lit-identity-direct-invocation-test

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1745]
We have got failing CI, example:
https://github.com/litentry/litentry-parachain/actions/runs/5111858175/jobs/9190401064

After a short investigation it seems that the return value of user_shielding_key trusted getter has changed

prev:
`{ value: '0x00', do_watch: false, status: 'Ok' }`
actual:
`{ value: '0x010400', do_watch: false, status: 'Ok' }`

this makes test fail on:
`assert.isTrue(k.isNone, 'shielding key should be empty before set');`

**Comment by outofxxx** [comment]
I think this pr https://github.com/litentry/litentry-parachain/pull/1744 will fix this error.

This is because obtaining the nonce has been moved from trusted to public getter, but it has not been modified in `interface/definitions.ts`, resulting in a request error.
