### ISSUE TITLE
ts-tests: use the derived types of LitentryPrimitivesIdentity to construct an identity.

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#1754]
Background:https://github.com/litentry/litentry-parachain/pull/1703#discussion_r1217690910

**Comment by 0xverin** [comment]
Note that this [PR](https://github.com/litentry/litentry-parachain/pull/1835) resolves the type merging for sidechains/parachains. In this issue, checking all custom types, and ideally, only using types generated by typegen. This includes the refactoring of the assertion type for VC.

**Comment by Kailai-Wang** [comment]
No longer a problem with type export, we can close it now.
