### ISSUE TITLE
The sidechain nonce getter should consider the pending tx

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1756]
### Context

Similar to what we did to [enclave_signer](https://github.com/litentry/litentry-parachain/blob/bdf982553a8f2477b81b4db059f0c5289f47d0de/tee-worker/core-primitives/stf-executor/src/enclave_signer.rs#L113-L120), we should take the pending tx into account when retrieving the "next" nonce for sidechain account.

It means we should make `accountNextIndex` as default for sidechain too: related https://github.com/litentry/litentry-parachain/issues/1425

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
We have the implementation already: https://github.com/litentry/litentry-parachain/blob/97f80f711e8ec308cbf230b9b35cd40b191d8217/tee-worker/cli/src/trusted_command_utils.rs#L49-L61

Just use `get_pending_trusted_calls_for` to get the pending txs.

Be sure to adjust `get_layer_two_nonce` once the public getter already covers it.

**Comment by songzhouran** [comment]
Calling System::account_nonce in RPC will cause websocket close.
