### ISSUE TITLE
Adopt and enforce naming convention in ts-tests code

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1769]
### Context

Mixed naming styles (e.g. `snake_case` for some variables and `camelCase` for others) add unnecessary friction when reading through the test code.

### Task

- Enable [this linting rule on the TS code](https://typescript-eslint.io/rules/naming-convention/)
- Configure the rule once consensus is achieved on the convention to adopt

### Acceptance criteria

- Lint checks pass with this rule enabled

### Questions/Blockers

- [ ] Discussion still ongoing on which convention to adopt

**Comment by 0xverin** [comment]
I'll work on this issue. @grumpygreenguy

**Comment by 0xverin** [comment]
Regarding naming conventions, here is how I currently define them:

- Variables: snake_case

- Types: UpperCamelCase

- Interfaces: UpperCamelCase

- Enums: UpperCamelCase

- Functions: lowerCamelCase

If you have any better suggestions, feel free to leave a comment. I believe that it doesn't need to be too complicated; simplicity and consistency are key.

**Comment by Kailai-Wang** [comment]
or google's ts style guide? https://google.github.io/styleguide/tsguide.html

**Comment by 0xverin** [comment]
> or google's ts style guide? https://google.github.io/styleguide/tsguide.html

Thank you. I think this one will work as long as we have a standard. It will help us reduce the time spent discussing this.

cc @grumpygreenguy @higherordertech

**Comment by kziemianek** [comment]
I came across [this](https://github.com/google/gts) while getting familiar with the topic, maybe it's worth taking a look .

**Comment by arieljbirnbaum** [comment]
tbh I'd go even lazier and just go with whatever the defaults are for `typescript-eslint` and `prettier` :sweat_smile: Tweak where required if and when we _really_ need it.
 
Went over the google guide; some of it looks sane but some of it doesn't look very relevant for us (e.g. do we care about compatibility below ES2015?).

**Comment by 0xverin** [comment]
> tbh I'd go even lazier and just go with whatever the defaults are for `typescript-eslint` and `prettier` 😅 Tweak where required if and when we _really_ need it.
> 
> Went over the google guide; some of it looks sane but some of it doesn't look very relevant for us (e.g. do we care about compatibility below ES2015?).

I don't think we need to consider ES2015 compatibility for now because this time I just want to standardize the naming. However, during the actual configuration process, there are indeed other ESLint issues that I need to address one by one, such as the proper use of const, let, var, and so on.

**Comment by 0xverin** [comment]
> I came across [this](https://github.com/google/gts) while getting familiar with the topic, maybe it's worth taking a look .

Thank you for your input. The issue is that the `GTS` configuration may come with some additional settings that could be redundant for our project. This time, we only want to focus on the variable naming issue.
