### ISSUE TITLE
Wrong mrenclave in the teerex registry for tee-internal

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1779]
### Context

As topic, it seems the MRENCLAVE in the teerex enclaveRegsitry differs from what `make mrenclave` suggests.

Something is wrong (maybe the build/compilation mode?)

This is a blocking issue for IDH right now, if we can't find out the reason soon, there're two alternatives:
- use SW mode to run the enclave
- provide extra PublicGetter for MRENCLAVE (it needs to be implemented anyway with or without this problem)

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
It's not valid any more. Maybe during reboot process, some mistakes happened. After I reboot `tee-internal`, this problem is gone.
