### ISSUE TITLE
Build polkadot-decoded assertions

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1785]
### Context

See the [notion doc](https://www.notion.so/web3builders/Get-Rewards-With-Your-DID-at-Polkadot-Decoded-2023-1eba74855d994540986e15a77d9606fe)

We can reuse some of the old assertions, but I'd suggest having a dedicated enum entry to make it more transparent for F/E, like 
```
pub enum Assertion {
A1,
A2,
...
Decoded2023_0,
Decoded2023_1,
...
},
```

Better names are welcome.

Scope:
- [x] Polkadot and Litentry twitter: #1789
- [x] #1791

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
We are going to reuse `A4`/`A7` for DOT/LIT token hodler assertion.

**Comment by kziemianek** [comment]
Closing as done.
