### ISSUE TITLE
DOT/LIT Token Hodler assertion

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1792]
- Assert that account have been consistently holding at least 10 LIT tokens from date 2023 Jan 1st 00:00:00 UTC till now on blockchain: Litentry.
- Assert that account have been consistently holding at least 10 DOT tokens from date 2023 Jan 1st 00:00:00 UTC till now on blockchain: Polkadot.

**Comment by Kailai-Wang** [comment]
@kziemianek if you are OK I'll close this issue and PR first 🙌

**Comment by kziemianek** [comment]
> @kziemianek if you are OK I'll close this issue and PR first raised_hands

sure 🙃

**Comment by Kailai-Wang** [comment]
We'll re-use A4/A7 - closing it now
