### ISSUE TITLE
lit-bulk-identity-test sometimes fails

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1804]
### Context

see e.g. https://github.com/litentry/litentry-parachain/actions/runs/5332867010/jobs/9664442766

```
litentry-bulk-identity-test  |   1) multiple accounts test
litentry-bulk-identity-test  |        test linkIdentity with multiple accounts:
litentry-bulk-identity-test  |      Error: the string "listenEvent error----Expect event:IdentityLinked but received unexpected event :LinkIdentityFailed" was thrown, throw an Error :)
```

Maybe a timing or race condition issue?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Looks like a nonce clash under multi-worker setup, needs further investigation

**Comment by Kailai-Wang** [comment]
How about deactivating it in CI? Or use single worker for now?

Haven't seen further updates on this

**Comment by 0xverin** [comment]
We have already removed the CI tests for `bulk_identity` in this [PR](https://github.com/litentry/litentry-parachain/pull/1956), so this issue can be closed.
