### ISSUE TITLE
lit-resume-worker fails occassionally

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1805]
### Context

See e.g. https://github.com/litentry/litentry-parachain/actions/runs/5332795556/jobs/9662533244

It's a timeout, looks like some disorder or race condition in the initialisation setup.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
Comparing the failed run to a successful one, the latter has a bunch of lines like this in the log:

```
litentry-worker  | ws://localhost:3000 current block: 2
```

These seem to come from a test method awaiting an RPC call for `sidechain_latestBlock`; apparently the latter is never yielding a successful result in the failed run. I don't know if there's a more detailed error in the response; will try to add a dump there :mag:

**Comment by arieljbirnbaum** [comment]
BTW the failed run _does_ seem to be able to spawn the RPC server:

```
litentry-worker  | worker0 [+] Untrusted RPC server listening on 0.0.0.0:3000
litentry-worker  | 
litentry-worker  | worker0 [+] Trusted RPC direct invocation server listening on 0.0.0.0:2000
litentry-worker  | [+] Untrusted RPC server is spawned on: 0.0.0.0:3000
```

**Comment by arieljbirnbaum** [comment]
One fishy thing about this test (though not necessarily related to this issue) is that we're checking the output from the worker process chunk by chunk; if there are several lines of output in a single chunk this is relatively benign (but it does make the logs more annoying to read :P), however AFAICT there's no guarantee that a single line won't be split across separate chunks  :mag:

**Comment by arieljbirnbaum** [comment]
> One fishy thing about this test (though not necessarily related to this issue) is that we're checking the output from the worker process chunk by chunk; if there are several lines of output in a single chunk this is relatively benign...

Looking more closely at the `launchWorker` logic, I have the suspicion that this is _exactly_ the culprit --- we look for the string `Successfully initialized shard` at the beginning of each chunk of data (without the `multiline` flag in the regex) and use that to determine the shard number, and then pass that as a param to `sidechain_latestBlock`; if the shard number is not the _first_ line of the chunk, the shard will be blank and the `latestBlock` call will fail.

Compare:
- [Failed run; shard number not in first line of chunk](https://github.com/litentry/litentry-parachain/actions/runs/5332795556/jobs/9662533244)
- [Successful run; shard number in first line of chunk](https://github.com/litentry/litentry-parachain/actions/runs/5398798886/jobs/9810929464)

**Comment by Kailai-Wang** [comment]
reopen as the error happened again after the fix: https://github.com/litentry/litentry-parachain/actions/runs/5580265954/attempts/1

Logs:
[logs-lit-resume-worker.zip](https://github.com/litentry/litentry-parachain/files/12091461/logs-lit-resume-worker.zip)

Can you please take a look? Do you need to add more logs for debugging?

**Comment by Kailai-Wang** [comment]
friendly ping :) ⬆️

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang the linked run seems to be a different issue; the log shows that the second worker died after initialization:

```
litentry-worker  | worker1 [+] Initialize the shard
litentry-worker  | worker1 Successfully initialized shard 0x2fbbc575178329dc9f2575658d7c9d051f41b3cb10769061ca43df79b63cc390
litentry-worker  | worker1 [+] Generate key files
litentry-worker  | worker1 [+] File 'enclave-signing-pubkey.bin' written successfully
litentry-worker  | worker1 [+] File 'enclave-shielding-pubkey.json' written successfully
litentry-worker  | worker1 thread 'main' panicked at 'Author of last finalized sidechain block could not be found: NoWorkerForShardFound(0x2fbbc575178329dc9f2575658d7c9d051f41b3cb10769061ca43df79b63cc390)', service/src/sync_state.rs:46:18
litentry-worker  | worker1 note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
litentry-worker  | worker1 close: 101
```

; that seems to come from this line at `fn sync_state()`:

```
	// FIXME: we now assume that keys are equal for all shards.
	let provider_url = match WorkerModeProvider::worker_mode() {
		WorkerMode::Sidechain =>
			executor::block_on(get_author_url_of_last_finalized_sidechain_block(node_api, shard))
				.expect("Author of last finalized sidechain block could not be found"),
		_ => executor::block_on(get_enclave_url_of_first_registered(node_api, enclave_api))
			.expect("Author of last finalized sidechain block could not be found"),
	};
```

though I can't tell which of the two cases was hit.

**Comment by Kailai-Wang** [comment]
We are using the `Sidechain` mode

**Comment by arieljbirnbaum** [comment]
Let's track the timeout issue in #1346
