### ISSUE TITLE
Twitter follower API with new v2 tokens

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1807]
### Context

Allegedly the follower(friendship) API has been deprecated with v2 tokens. Can you confirm it? Is there any alternative?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
I tried it with our v2 token but it responds with `403` HTTP code.

There is no similar alternative in twitter v2 api. We can try to replace one call with multiple calls to get paginated list of all user's followers to check wheter user is on list but in worst scenario that would cost us X api calls (iterate over whole list).

[Twitter API endpoint map](https://developer.twitter.com/en/docs/twitter-api/migrate/twitter-api-endpoint-map) says that similar to v1 endpoint is coming soon.

![image](https://github.com/litentry/litentry-parachain/assets/1838338/18ef6c4b-c363-4f15-b01e-68832f7ce240)

**If there is no urgent need I suggest to wait for new endpoint.**

**Comment by kziemianek** [comment]
I tried twitter v2 followers endpoint with our token but without a success:

```
curl --request GET 'https://api.twitter.com/2/users/2244994945/followers' --header 'Authorization: Bearer x'
{"client_id":"27342060","detail":"When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.","registration_url":"https://developer.twitter.com/en/docs/projects/overview","title":"Client Forbidden","required_enrollment":"Appropriate Level of API Access","reason":"client-not-enrolled","type":"https://api.twitter.com/2/problems/client-forbidden"}
```

The problem is described by community in more detail [here](https://twittercommunity.com/t/get-2-users-id-following-is-now-broken/197526/48)

In short it looks like twitter has removed this endpoint, see [changelog](https://developer.twitter.com/en/updates/changelog).

I see two ways of getting this working again:
1. keep on using  api v1.1 (if we can get the token)
2. wait for friendship endpoint in v2

**Comment by kziemianek** [comment]
We are not sure if we ever get working twitter frienship api again.
Let's remove this assertion, what do you think? cc: @BillyWooo , @Kailai-Wang

**Comment by BillyWooo** [comment]
> We are not sure if we ever get working twitter frienship api again. Let's remove this assertion, what do you think? cc: @BillyWooo , @Kailai-Wang

We just got confirmed that Twitter won't support the friendship info-query any more. V2 won't have such API. V1 is already deprecated and deactivated. 
So yes, let's remove it.

**Comment by BillyWooo** [comment]
Just noticed: [this](https://github.com/litentry/identity-hub/issues/857) is closed. We are safe to go.
