### ISSUE TITLE
Building wasm with srtool fails

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1819]
### Context

See https://github.com/litentry/litentry-parachain/actions/runs/5373385699/jobs/9747713246

Is it because of two low polkadot version, combined with the fact that upstream has been using stable rustc?

See https://github.com/paritytech/substrate/pull/13580

Or is it because srtool is using a too new rustc version? (`1.70`) Maybe we can solve it by downgrading the srtool image version.

It needs a bit of research.
The goal is we can successfully build wasm with srtools and the built wasm can be used for runtime ugprade.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by hanwencheng** [comment]
Updates?

**Comment by felixfaisal** [comment]
> https://github.com/litentry/litentry-parachain/actions/runs/5373385699/jobs/9747713246

Unable to run the srtools locally on my machine, I will be forking and testing the GHA
