### ISSUE TITLE
Create new assertions based on current new Achainable API (tag4: DeFi)

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1826]
### Context
Our data provider TDF's product [Achainable](https://achainable-stage.vercel.app/?achainableLabels=true&userLabels=true&searchText=&chain=All+chains&tag=All+tags&view=list) has developed new API to query data. There are quite many labels provided by Achainable. They are grouped by tags: Account, Balance, Dotsama, DeFi, etc.

Task
Covert existed labels into assertions. Tag: DeFi

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by hanwencheng** [comment]
What is the follow up for the new assertions?

**Comment by Kailai-Wang** [comment]
Is this done? @zhouhuitian

**Comment by outofxxx** [comment]
There will be a [new issue](https://github.com/litentry/litentry-parachain/issues/1944) to track the specific new assertions to be made. According to @BillyWooo 's suggestion, these Tag-series issues (including https://github.com/litentry/litentry-parachain/issues/1718 / https://github.com/litentry/litentry-parachain/issues/1719 / https://github.com/litentry/litentry-parachain/issues/1720) will be temporarily retained and will be discussed later.

**Comment by BillyWooo** [comment]
As discussed [here](https://github.com/litentry/litentry-parachain/pull/1986#issuecomment-1667263786), we can close this issue for the moment. If further new assertion requirement comes, create new issue.
