### ISSUE TITLE
Add `account` parameter to `set_scheduled_mrenclave` trusted cli command

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1827]
Right now this command is always executed in the context of Alice.
To make this command more flexible we need to add  a third parameter `account` in ss58check format.

**Comment by Kailai-Wang** [comment]
is it superseded by #1830 ?

**Comment by kziemianek** [comment]
Yes. As long as we cannot provide any usable fix for this issue let's close it.
