### ISSUE TITLE
Replace `set_scheduled_mrenclave` trusted call with worker direct api call

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1830]
In some circumstances `set_scheduled_mrenclave` trusted call cannot be executed, one of the examples is when `tee-worker` detects `mrenclave` mismatch and is not able to produce blocks anymore, thus cannot execute any trusted calls:

```
[2023-06-26T10:42:30Z WARN  aura] Skipping sidechain block 550 due to mismatch MRENCLAVE, current: Ok("cd104e995d478c063c0aa3cb1d02daa56c3008d0f336eeabcb771f2111f09823"), expect: Ok("456f56313143575432397376474d4259556a77597663764a6a61336779653561")
```

Because this call is altering only node's local state, we can move logic from trusted call to worker's direct api call.

Tasks:

- [ ] Remove `set_scheduled_mrenclave` trusted call
- [ ] Add `mrenclave__update_scheduled` rpc method available only in dev mode

**Comment by Kailai-Wang** [comment]
Would you like to take it @kziemianek ? As you are probably the most familiar with this call

**Comment by kziemianek** [comment]
Yes, I will do this once I finish more important tasks.
