### ISSUE TITLE
EVM support of parachain

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#1847]
After a careful discussion, we decide to support EVM in our parachain (at leaset from substrate aspect).
The true challenge of full compatible with Ethereum ecosystem tool is hard, and will not include in this issue for now.

We plan to have it together with a listener project before the end of this year.

**Comment by hanwencheng** [comment]
I and Minqi will provide further details for the listener project later

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/Contract-Event-Schema-V2-to-public-03a30886f8564f0cb7fd653fd76eeb50

https://www.notion.so/web3builders/Decentralized-Monitoring-Collator-Network-DMCN-v2-2f78eb0b0df242b7bf65a6f6eb00abbf

**Comment by Kailai-Wang** [comment]
This is done
