### ISSUE TITLE
Trusted CLI nonce command fails

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1851]
Apparently, after the latest changes to the nonce retrieval mechanism the nonce trusted command stopped working.

```
kziemianek@kziemianek:~/projects/litentry/litentry-parachain/tee-worker/target/release$ ./integritee-cli trusted --mrenclave 56kLvcE2kkxmNQ3Jii1SiPseXzmSUBWrZheomiUm1epG nonce //Alice
thread 'main' panicked at 'get nonce error!: MspcReceiver(RecvError)', cli/src/trusted_base_cli/commands/nonce.rs:39:31
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The worker dies with following message:
```
thread '<unnamed>' panicked at 'storage cannot be called outside of an Externalities-provided environment.', /home/kziemianek/projects/litentry/litentry-parachain/tee-worker/core-primitives/substrate-sgx/sp-io/src/lib.rs:131:9
```

**Comment by songzhouran** [comment]
<img width="563" alt="image" src="https://github.com/litentry/litentry-parachain/assets/3433393/bf69dcc7-618a-4b15-9ecd-b1ef8724af45">

**Comment by songzhouran** [comment]
It works on my local and there is no panic.

**Comment by Kailai-Wang** [comment]
Hmm I got panic too :( 

<img width="1303" alt="image" src="https://github.com/litentry/litentry-parachain/assets/7630809/46e8a6aa-b11b-40df-8bf8-42dd11144331">
