### ISSUE TITLE
Rename `ethereum...` to `evm...` in ts-tests

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1853]
### Context

As topic.
E.g. `ethereumValidations`, `ethereumSigners` ... the reason is they are not specific to ethereum and it needs to match `substrateValidations`, `substrateSigners`...

What do you think? @grumpygreenguy @Verin1005 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
At first, I remember using the name `evm`, but later I realized that `evm` refers to a virtual machine. So, I changed it to `ethereum`, which is a platform description. :p

**Comment by Kailai-Wang** [comment]
"virtual machine " -- I thought that's what we wanted, because all evm-compatible chains are based on that VM :/
