### ISSUE TITLE
Package binaries for deployment 

### ISSUE THREAD

**Issue by felixfaisal** [litentry/litentry-parachain#1856]
### Context
This issue was discussed during automating the deployment of worker and parachain [PR 1750](https://github.com/litentry/litentry-parachain/pull/1750)

### Task
There already exists a script for packaging some parts of the `integritee-service` binary in `prepare.sh` under `tee-worker/scripts/litentry/release`. The idea is to combine this logic to generate a package that can be run on any server. This is particularly helpful when we have a multi-worker setup which will be deployed over several servers. 

### Acceptance criteria
You should be able to perform successfull restarts and upgrade-worker.

**Comment by BillyWooo** [comment]
Just some comment during deployment:

deploy binary package (no dependency with repo)
save config file (key/tokens/etc.) to a specific location on server

**Comment by BillyWooo** [comment]
I think this is also important. It's better to have ASAP.

**Comment by Kailai-Wang** [comment]
Deprecated as we now use docker deployment
