### ISSUE TITLE
Reconsider the assertion inclusion in VC

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1859]
### Context

Requesting VC requires the parameter `assertion`.
However, given a generated VC, there's no way to tell which assertion this VC relates to retroactively. You can only try to pair it using the VC subject description, which is irrational and error-prone. This is the way how clients associate the VC with the requested assertion for the moment.

Todo:
1. Include the assertion in the VC - can be a field in VC with the key "assertion"
2. ~~Research and investigate the subject info in VC: are all these necessary? Description, type, tag.~~ covered in https://github.com/litentry/litentry-parachain/issues/1861

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by 0xverin** [comment]
This issue is also important in ts-tests.

**Comment by Kailai-Wang** [comment]
related: https://github.com/litentry/litentry-parachain/issues/1861

**Comment by Kailai-Wang** [comment]
~~Might be superseded by #1933~~

#1933 take time - we should implement this as short/mid-term solution

**Comment by Kailai-Wang** [comment]
closed by https://github.com/litentry/litentry-parachain/pull/2364
