### ISSUE TITLE
Replace old parachain-ci and tee-worker-ci badges with ci badge

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1864]
Old badges are not available anymore.
![image](https://github.com/litentry/litentry-parachain/assets/1838338/08b854f6-72fd-4338-890d-07251ed86af8)

**Comment by kziemianek** [comment]
This badge can be used instead https://github.com/litentry/litentry-parachain/actions/workflows/ci.yml/badge.svg?branch=dev

**Comment by Kailai-Wang** [comment]
related: #1434
