### ISSUE TITLE
Verify the correctness of VC content in ts-test

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1873]
### Context

So far we have only tested these:
- vc request works
- the vc result is in valid format
- the vc signature matches
- the vc hash matches

However, we never verify that the assertion is correctly computed - if the `value` or result of the assertion is right. This can be done by examining a few chosen accounts which match the assertion criteria or not, and comparing it against the expected result.

If having such test cases for all assertions is too much for a single PR, we can either
- do it via multiple PRs
- only do important ones first (especially those that require http responses)

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
> the vc result is in valid format

In light of [this discussion](https://litentry.slack.com/archives/C03KR96989G/p1689926953000869), we should also make sure to check the precise format of each type of credential subject, especially the information-carrying fields in the respective assertions.

**Comment by Kailai-Wang** [comment]
It's done, see the migrated Linear issue
