### ISSUE TITLE
Remote relay chain error

### ISSUE THREAD

**Issue by King-Charming** [litentry/litentry-parachain#1874]
I have been experimenting with the remote relay chain flag and got the following error after rebooting the server. The remote relay chain node is running on the same server as the Litentry collator node 

Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: 2023-07-12 02:56:14 [Parachain] Trying to connect to next external relaychain node. index=0 url=Url { scheme: "ws", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("localhost")), port: Some(9900), path: "/", query: None, fragment: None }
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: 2023-07-12 02:56:14 [Parachain] No valid RPC url found. Stopping RPC worker.
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: 2023-07-12 02:56:14 [Parachain] Essential task `relay-chain-rpc-worker` failed. Shutting down service.
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: ====================
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: Version: 0.9.16-unknown
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    0: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    1: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    2: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    3: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    4: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    5: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    6: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    7: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    8: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:    9: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   10: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   11: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   12: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   13: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   14: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   15: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   16: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   17: __libc_start_main
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]:   18: <unknown>
Jul 12 02:56:14 Ubuntu-2204-jammy-amd64-base Litentry[1748]: Thread 'main' panicked at 'Genesis block hash is always available; qed: RpcCallError("chain_getBlockHash")', /usr/local/cargo/git/checkouts/cumulus-59522f43471fa161/d6eef14/client/relay-chain-minimal-node/src/lib.rs:140

**Comment by King-Charming** [comment]
It fixed it self at the next retry

**Comment by BillyWooo** [comment]
Thank you @King-Charming for trying our product. 
If you don't find problem any more, could you please kindly close this issue? 
Let us know if it happens again. We will investigate on it. Thanks.
