### ISSUE TITLE
Check if manual definitions are really needed in parachain-api TS package

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#1878]
### Context

Following up from [this discussion](https://github.com/litentry/litentry-parachain/pull/1835/files#r1260761816).
Ideally, all type definitions for the parachain and sidechain API packages should be generated from the chain metadata via the typegen scripts. However, we still seem to need manual definitions for the `identity` module in the parachain API.

### Task
- Check if the manual definitions are _really_ necessary, or if we can do away with them.
- If we cannot get rid of them, document _why_ they are needed, and set a procedure to keep these up to date
  - If this is the case, we should consider making these API packages available to clients (e.g. IDHub) so they can stay up to date as well :)

**Comment by Kailai-Wang** [comment]
> we should consider making these API packages available to clients

Yes we need to start publishing packages for clients.

Btw, do we need to do this even for the metadata-generated types? I mean do clients know how to update the metadata and types, **which match a parachain release?**

**Comment by Kailai-Wang** [comment]
The type usage in the current ts-test is a mess 😂 so IMO this is an important task, at least _medium_, maybe even _high_

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang 

> Yes we need to start publishing packages for clients.
> 
> Btw, do we need to do this even for the metadata-generated types? I mean do clients know how to update the metadata and types, **which match a parachain release?**

_In theory_ each client should be able to do this process on their own, based only on the chain metadata. In practice, it can be a big [pain](https://github.com/litentry/litentry-parachain/pull/1835) to set up, as evidenced by the time @Verin1005 and I have sunk into this just now (not to mention the work the IDHub colleagues have had to do to do their own version of this integration). Hence I think it would still be more helpful to clients if we "centralize" that pain in one location :D

**Comment by Kailai-Wang** [comment]
Prioritise this - as we have more and more needs to use the correct types.

Will/IDHub colleagues asked about this. I noticed it when I wrote the code myself.

The longer we push back the issue, the more effort we'll need to take to rebuild/refactor everything when this issue is solved. 

We should start to use generated types as early as possible.

**Comment by 0xverin** [comment]
>Task
Check if the manual definitions are really necessary, or if we can do away with them.
If we cannot get rid of them, document why they are needed, and set a procedure to keep these up to date
If this is the case, we should consider making these API packages available to clients (e.g. IDHub) so they can stay up to date as well :)

Apart from these two tasks, our focus should be on being able to release a package - building the parachain-api and sidechain-api packages. We will install them using yarn when using,AFAIK, is this our ultimate mindset, right? @grumpygreenguy

**Comment by arieljbirnbaum** [comment]
To keep things focused; I opened #2087 to track the packaging work as such.
For the specific question in this issue, the answer is sadly "yes, we need them".
RPC method types are not included in the metadata, and everything seems to indicate that this will be the case for the foreseeable future.
