### ISSUE TITLE
Fix export issues ts-tests.

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#1881]
### Context
see [comment](https://github.com/litentry/litentry-parachain/pull/1835#discussion_r1261056367)

**Comment by arieljbirnbaum** [comment]
Note: this may or not have implications on which files should be committed from the `dist` folder; see [here](https://github.com/litentry/litentry-parachain/pull/1835#discussion_r1260913460)

**Comment by 0xverin** [comment]
This issue may have already been resolved casually, I will double-check it.

**Comment by Kailai-Wang** [comment]
What's the status of this one?
@0xverin @grumpygreenguy

**Comment by 0xverin** [comment]
This problem no longer exists now.
