### ISSUE TITLE
"./integritee-service test --all" crash

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1897]
### Context
As the title, after build the latest 'dev' branch, and execute "./integritee-service test --all", the error message will come out.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Sgx(SGX_ERROR_SERVICE_UNAVAILABLE)', service/src/main.rs:176:50
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Task
Fix the error.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
From which directory did you execute the command?
There is no problem in the `bin` directory. If it is in `target/release`, it is because there is no `enclave.signed.so` in the directory.

**Comment by Kailai-Wang** [comment]
It seems to be a false alarm.
I freshly compiled everything and it worked on my side:
```
test result ok. 70 tested, 70 passed, 0 failed
[+] unit_test ended!
[+] All tests ended!
```

**Comment by BillyWooo** [comment]
Sorry. It's false alarm.
