### ISSUE TITLE
IMP extrinsic removal/addition

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1900]
### Context

According to the EVM sign-in doc, we'd like to make some changes to IMP:
- remove `remove_identity` extrinsic => we disallow that for now
- add an `deactivate_identity` extrinsic => deactivated identities shouldn't take part in assertion building
- add an `activate_identity` extrinsic

This will be a **breaking change** for sure.

Apart from that, for indirect call filter, it may make sense to merge all IMP extrinsic handling into one single file.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
Hi @Kailai-Wang @felixfaisal I have this almost done as a third point from the scope described in #1715. It is described as _identity archiving_.

**Comment by kziemianek** [comment]
> Apart from that, for indirect call filter, it may make sense to merge all IMP extrinsic handling into one single file.

I'm addressing this one in #1912
