### ISSUE TITLE
A8 modification

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/litentry-parachain#1913]
### Context
Correct the implementation of A8

### Task
1. Change description into: "Gets the range of number of transactions a user has made for a specific token on all supported networks (invalid transactions are also counted)"

2. Define range of assertion results:
0, false
1-10, true
10-20, true
20-50, true
50-100, true
100-200, true
200-300, true
300-500, true
.. >500, true

### Acceptance criteria
correctly generates 1 false credential, 2 true credentials with different value of range

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
For the case of 0, we still keep the previous expression and only change value to false. @kaylawangnow
