### ISSUE TITLE
A11,A10,A4,A7 modification

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/litentry-parachain#1914]
### Context
Correct implementation

### Task
1. change description into: "The length of time a user continues to hold a particular token (with particular threshold of token amount) "
2. define range of query period to a half year period:
2017/01/01 0:00 UTC - 2017/06/01 0:00 UTC
2017/06/01 0:00 UTC - 2017/12/31 0:00 UTC
2018/01/01 0:00 UTC - 2018/06/01 0:00 UTC
2018/06/01 0:00 UTC - 2018/12/31 0:00 UTC
2019/01/01 0:00 UTC - 2019/06/01 0:00 UTC
2019/06/01 0:00 UTC - 2019/12/31 0:00 UTC
2020/01/01 0:00 UTC - 2020/06/01 0:00 UTC
2020/06/01 0:00 UTC - 2020/12/31 0:00 UTC
2021/01/01 0:00 UTC - 2021/06/01 0:00 UTC
2022/06/01 0:00 UTC - 2022/12/31 0:00 UTC
2023/01/01 0:00 UTC - 2023/06/01 0:00 UTC
2023/06/01 0:00 UTC - now

### Acceptance criteria
True: returns the longest range of period
False: when user doesn't meet any of these periods

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
A more accurate statement would be:

2017/01/01 0:00 UTC - NOW
2017/06/01 0:00 UTC - NOW
2018/01/01 0:00 UTC - NOW
.
.
.
2023/01/01 0:00 UTC - NOW
2023/06/01 0:00 UTC - NOW
