### ISSUE TITLE
Alert tasks

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1915]
### Context
some alert tasks noticed recently which needs to be done.

### Task
1. suspend CPU utilisation monitor for the instance . Because this `tee-prod1` machine currently is used for dev purpose. 
2. Setup monitor for `tee-staging` sidechain. Currently there is alert setup for ERROR messages. But `Enclave produced sidechain blocks: [####]` should also be monitored. If this message doesn't show up for more than e.g. 30s, something wrong must have happened. Normally it should come out every 6s. Depends on the monitor setup, we can give interval like 3 min, 5 min. Also be fine.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by niteshb3495** [comment]
1. done already. the monitoring of tee-prod1 is paused.

**Comment by niteshb3495** [comment]
2. completed last week. Interval set 1 min.

**Comment by BillyWooo** [comment]
Not valid any more.
