### ISSUE TITLE
Abort VC building in case of data provider errors

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1916]
### Context

It seems that we continue building VCs even when a data provider error is present. This would lead to wrong results in VC.

We should abort the process instead.

Can we have a test case for it?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
related issue: https://github.com/litentry/litentry-parachain/issues/1870
The refactor may affect the logic/structure. So take this into consideration.
