### ISSUE TITLE
Explore and implement non-public twitter verification

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1927]
### Context

At present, we require users to post the verification message as a public tweet. This can be a bit weird (imagine your friend suddenly posted a line of hex strings on twitter...).

Shall we provide a way to verify it privately? E.g. oauth + bot
Shall we allow users to decide on the verification method? (publicly or privately)

cc @kaylawangnow @jonalvarezz 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jonalvarezz** [comment]
That'd be fantastic if we can support both.

Technically speaking, how would the private verification work? Would it still happen in the Enclave?

**Comment by Kailai-Wang** [comment]
> That'd be fantastic if we can support both.
> 
> Technically speaking, how would the private verification work? Would it still happen in the Enclave?

We would need to host a service for oauth verification I believe.
Ideally this service can be put into enclave, but maybe not in the first step.

**Comment by Kailai-Wang** [comment]
We implemented oauth verification
