### ISSUE TITLE
Define the infrastructure of VC building systematically

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1933]
### Context

So far, we have been hardcoding stuff. As we move towards a more flexible and systematic integration solution, we need to define the "standard" integration flow of building VCs more systematically, including the infra. It means, we need to outline the following:

- how is assertion schema registered? (JSONSchema?) => instead of having `A*`, we should allow registration of VC type information from users, like:
   - a unique id
   - description
   - supported network types
   - field template
   - revision 
   - ...
   I'm not sure if JSONSchema covers all of these, related: #1860 
- how is assertion-building logic defined? The most challenging one, we need a smart-contract-ish way to be able to define the logic programmatically so that it's customisable
- how is the data provider integrated? Do we need to have something like dataProviderRegistry, which serves as a data source for:
  - endpoint URL and APIs
  - description and metadata
  - availability?
  - ...

A sharing session should be given after the initial idea is devised.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
At least part of the scope is delivered in #2695 , @Kailai-Wang can we close the issue or do you see anything left to do here ?

**Comment by Kailai-Wang** [comment]
This is done after the solidity impl
