### ISSUE TITLE
Linear processing of DI requests

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1935]
### Context

Following up on the discussion in https://github.com/litentry/litentry-parachain/pull/1920#discussion_r1272208657

Imagine there are 100 workers and we send a request to worker0, worker0 happens to just finish the its block production so the newly submitted request won't be included in the block for now. Since we have an aura authorship mechanism, the request can be processed after 100 blocks at the earliest, this sounds terrifying.

The root cause is the tx pool of sidechain is not synchronised among nodes, so a DI request can only be stored and processed by the node, to which the request was submitted.

It's a critical issue for multi-worker setup, but I don't think we have time to solve it soon, hence the medium prior.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
reported upstream too: https://github.com/integritee-network/worker/issues/1397

**Comment by kziemianek** [comment]
This will probably require some kind of DI response sync mechanism if the request work can be picked up by another node.
