### ISSUE TITLE
create new Ethereum related assertions

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1944]
### Context
After refactor of Achainable API with SystemLabel, we should be able to create some more new assertions. 
Ethereum:
- class of xxxx (year)
- ETH Holder (only check balance)
- Contract creator
- Uniswap User V2/V3

### Task
Create new assertions list as above (at least three of them)

### Related Issue

#1718 #1719 #1720 #1826 

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
* class of (xxx) year
Does the parameter here refer to querying any year?
 
Actually, it can query any time interval here, like :
```json
    "params": {
        "chain": "ethereum",
        "date1": "2020-11-01T00:00:00.000Z",
        "date2": "2020-12-31T23:59:59.999Z"
    }
```

**Comment by outofxxx** [comment]
* ETH Holder (only check balance)
What exactly does this mean? No matter how much, as long as the holding is found?

**Comment by kaylawangnow** [comment]
> * ETH Holder (only check balance)
> 
> What exactly does this mean? No matter how much, as long as the holding is found? 

the current balance of user
