### ISSUE TITLE
Sychronization of client side state of IDGraph

### ISSUE THREAD

**Issue by wli-pro** [litentry/litentry-parachain#1955]
### Context
What's the context and background of this issue?

It's mainly about a consistent way of handling the IDGraph synchronisation. 

User might have multiple devices connecting to IDH which cached the local version of the IDGraph.

Now if one device tried to mutate the IDGraph, how would the other devices know the IDGraph has been mutated?

There's no centralised cloud service to do the synchronisation and notification, yet the clients have the needs to know if the local copy is valid or not.

### Task
What needs to be done here?

There might be two ways to solve that:
1 the sidechain includes the IDGraphs (or its hash) in the response of each mutation (IDGraph write operation)
2 upon each mutation, the sidechain publishes the hash to parachain, so there's a "idgraph prime identity -> hash of idgraph" mapping.
Precondition is the hash is deterministic.

I prefer No. 2. The idea is similar to etag in http. Both the client (local browser) and sidechain keep a copy of IDGraph, and use hash to determine if the local copy is outdated or not.

So IDhub will need to determine when to check those hashes (e.g. when the user logs into a new browser). If the hash doesn't match, IDHub knows the IDGraph is out of sync, then it needs to fetch it from sidechain again.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Superseded and implemented by https://github.com/litentry/litentry-parachain/pull/2304
