### ISSUE TITLE
Programmatic stress test 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1966]
### Context

We'd like to perform some stress tests for the upcoming campaign.

Two directions:
- spike of user traffic (sending a large amount of requests within a short period)
- accumulated user count  (if the sidechain block would grow to an unacceptable size when we have 3K, 5K, 10K, 15K ... users/IDGraphs)

User action to test:
- user shielding key set
- VC request (worst case is e.g. LIT holder)
- (optional) twitter linking
- (optional) discord linking

Test aspects:
- if the service fails to handle them all
- if the service will be down
- if all requests are successfully handled, what's the largest delay 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
Done :heavy_check_mark:
