### ISSUE TITLE
update to upstream worker commit: 3443f154

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#1967]
### Context
As title, there are some difference between our local copy and upstream worker.

### Task
Sync and fill the gap.

### Acceptance criteria
What's the definition of done, if applicable?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
beware [d1b8cbe](https://github.com/integritee-network/worker/commit/d1b8cbefe9eb09228754063060a50d4c244727f4) is the latest commit
