### ISSUE TITLE
Add LIT/DOT holder assertion

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#1973]
Add 2 new holder assertions, as detailed in 
https://docs.google.com/spreadsheets/d/1k2ZvrLK5v_KO_tsCWJVtjbs8TS8PzM_idWv64z4ynSI/edit#gid=1065809408

* LIT holder
* DOT holder

**Comment by Kailai-Wang** [comment]
I'm a bit confused how this issue relates to https://github.com/litentry/litentry-parachain/issues/1944

Are they the same, or do we need to build two extra assertions, which add up to 6 assertions in total?

**Comment by outofxxx** [comment]
Yes, they are different. The previous one was `ETH holder`, but these two are new additions, so there are currently 6 assertons.
