### ISSUE TITLE
DI sync response account id

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1975]
Direct invocation synchronous responses contain account identifier in substrate format which is 32 byte long.
Because DI can be submitted both by substrate and evm accounts this identifier should contain original form of account id - not substrate format as it currently happens in both cases.

Pros: 
- easier for consumer to use returned id

Cons:
- not consistent with II parachain events which always hold account id in substrate format

**Comment by kziemianek** [comment]
Looks like both examples (evm,substrate) fails also with another error:

```
post verification msg to substrate:  0x051c72fe6497d646f2157307fac0fae5108386bc8b865eb11128500f90a7c942
Error: createType(LitentryValidationData):: Cannot map Enum JSON, unable to find 'registry' in web2validation, web3validation
```

**Comment by Kailai-Wang** [comment]
Can we include the `Identity` struct in the response instead?

**Comment by kziemianek** [comment]
@Kailai-Wang yes, but my personal impression is that this information is not necessary in response. The client already knows to which `account` this response relates because he sent the request.  But because there is this information in resposne (and probably some more)  we need to take care of it now and there will be probably some more potential work in the future.
