### ISSUE TITLE
Remove di-examples

### ISSUE THREAD

**Issue by kziemianek** [litentry/litentry-parachain#1987]
Since we have di tests we don't need examples anymore, the code can be deleted.

~~There is example ts-code showing how integration with sidechain through direct invocation can be implemented.
The code is unfortunately not checked every time we make breaking changes to our interfaces, thus very often it doesn't work.
If we want to keep this code we should add relevat jobs to run it on each PR.~~

~~Examples can be run by following commands in tee-worker/ts-tests :~~

~~EVM DI examples: corepack yarn workspace integration-tests evm-di-examples
Substrate DI examples: corepack yarn workspace integration-tests substrate-di-examples~~

**Comment by Kailai-Wang** [comment]
Actually I think once we (officially) have the DI ts-test, we can deprecate the sample code.

The DI ts-test should cover all cases in the example.

**Comment by Kailai-Wang** [comment]
Now that we have DI test - shall we close this issue? @kziemianek

**Comment by kziemianek** [comment]
@Kailai-Wang the example code is still there so I think we can close the issue once the code is removed.

**Comment by kziemianek** [comment]
@songzhouran the DI tests are complete #1682 .
Could you remove example code ?

**Comment by songzhouran** [comment]
The code has already been removed and the scripts in package.json is also been removed. Can I close the issue? @kziemianek

**Comment by kziemianek** [comment]
@songzhouran , we need to remove examples before we close the issue
https://github.com/litentry/litentry-parachain/tree/dev/tee-worker/ts-tests/integration-tests/examples/direct-invocation

There are also npm scripts in `integration-tests` workspace.
