### ISSUE TITLE
Latest `frame-metadata` version is incompatible

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1991]
### Context

If I try to update the rust deps by `make update`, I'll get the following errors:

```
error: failed to select a version for `frame-metadata`.
    ... required by package `itc-rpc-client v0.9.0 (/home/kai/litentry-parachain/tee-worker/core/rpc-client)`
    ... which satisfies path dependency `itc-rpc-client` of package `litentry-cli v0.9.0 (/home/kai/litentry-parachain/tee-worker/cli)`
versions that meet the requirements `*` are: 16.0.0

the package `itc-rpc-client` depends on `frame-metadata`, with features: `v14` but `frame-metadata` does not have these features.
```

So it looks some the `frame-metadata` is updated to an incompatible version.
We need to fix this by e.g. pinning the version or adjusting toml.

**Comment by Kailai-Wang** [comment]
I guess this is the problem: 

https://github.com/litentry/litentry-parachain/blob/d9cfb1d4e7759fb181459c5d09cf006eb6291304/tee-worker/core/rpc-client/Cargo.toml#L22

with `master` branch.

It's a bit chaotic that some `frame-metadata` come from `crates.io`, and others from the parity GH repo.

Strangely, pinning it against a fixed revision (e.g. https://github.com/paritytech/frame-metadata/commit/d6d22767e306549bf2f9aa7a0b66d95bec99ac62) didn't work either:

```
frame-metadata = { git = "https://github.com/paritytech/frame-metadata", rev = "d6d2276", features = ["v14"] }
```

It then complains about the non-implemented trait: 
```
error[E0277]: the trait bound `itp_api_client_types::Metadata: From<RuntimeMetadataPrefixed>` is not satisfied
   --> core/rpc-client/src/direct_client.rs:199:22
    |
199 |         Metadata::try_from(metadata).map_err(|e| e.into())
    |         ------------------ ^^^^^^^^ the trait `From<RuntimeMetadataPrefixed>` is not implemented for `itp_api_client_types::Metadata`
    |         |
    |         required by a bound introduced by this call
    |
    = help: the following other types implement trait `TryFrom<T>`:
              <itp_api_client_types::Metadata as TryFrom<frame_metadata::RuntimeMetadataPrefixed>>
              <itp_api_client_types::Metadata as TryFrom<itp_node_api_metadata::NodeMetadata>>
    = note: required for `RuntimeMetadataPrefixed` to implement `Into<itp_api_client_types::Metadata>`
    = note: required for `itp_api_client_types::Metadata` to implement `TryFrom<RuntimeMetadataPrefixed>`
```

The compiler even gave hints:
```
the following other types implement trait `TryFrom<T>`:
              <itp_api_client_types::Metadata as TryFrom<frame_metadata::RuntimeMetadataPrefixed>>
              <itp_api_client_types::Metadata as TryFrom<itp_node_api_metadata::NodeMetadata>>
```

So it seems that it can't get linked to the desired `frame-metadata` crate?

In the worker `Cargo.lock` it would then contain two copies of `frame-metadata`, one from `substrate-api-client` (branch  `polkadot-v0.9.39`), the other from the explicit `core/rpc-client/Cargo.toml`

```
[[package]]
name = "frame-metadata"
version = "15.1.0"
source = "git+https://github.com/paritytech/frame-metadata?rev=d6d2276#d6d22767e306549bf2f9aa7a0b66d95bec99ac62"
dependencies = [
 "cfg-if 1.0.0",
 "parity-scale-codec",
 "scale-info",
 "serde 1.0.175",
]

[[package]]
name = "frame-metadata"
version = "15.1.0"
source = "git+https://github.com/paritytech/frame-metadata#d6d22767e306549bf2f9aa7a0b66d95bec99ac62"
dependencies = [
 "cfg-if 1.0.0",
 "parity-scale-codec",
 "scale-info",
 "serde 1.0.175",
]
```

The source code is identical (as they point to the same revision), but still the compilation error, which I need help understanding.

Updating to `polkadot-v0.9.42` would incidentally solve this as the newer `substrate-api-client` depends on the `crates.io` now.

**Comment by haerdib** [comment]
Have you tried pinning the revision with `cargo update -p frame-metadata --precise d6d22767e306549bf2f9aa7a0b66d95bec99ac62` (both in worker and enclave) instead of pinning it in the cargo.toml? I think with this you should be able to avoid the version clash in the .lock

**Comment by Kailai-Wang** [comment]
> Have you tried pinning the revision with `cargo update -p frame-metadata --precise d6d22767e306549bf2f9aa7a0b66d95bec99ac62` (both in worker and enclave) instead of pinning it in the cargo.toml? I think with this you should be able to avoid the version clash in the .lock

That doesn't change anything unfortunately, because that's already the case :(

tee-worker/Cargo.lock:

```
[[package]]
name = "frame-metadata"
version = "15.1.0"
source = "git+https://github.com/paritytech/frame-metadata#d6d22767e306549bf2f9aa7a0b66d95bec99ac62"
dependencies = [
 "cfg-if 1.0.0",
 "parity-scale-codec",
 "scale-info",
 "serde 1.0.175",
]
```

The problem is I can't do `cargo update` freely as it would update this crate to a newer master commit, thus I need to somehow pin its revision.

**Comment by haerdib** [comment]
That's true. What we've often been doing in the worker is to pin it in the make file:
https://github.com/integritee-network/worker/blob/master/Makefile#L244-L246
E.g. run a `cargo update` (updating everything) and then do a downgrade with `cargo update -p ... --precise ...`.
Not sure if that's a feasible solution for you.

Either way, what about updating to the newest frame-metadata? v14 is still available, but with a different name: `current` instead of `v14` (check out: https://github.com/paritytech/frame-metadata/blob/main/frame-metadata/src/lib.rs#L70-L72)

**Comment by Kailai-Wang** [comment]
Thanks, `cargo update` already gives an error before I can downgrade to a specific version (see the issue description).

I tried to use `current` feature and latest frame-metadata, but then it complains that `substrate-api-client` needs a lower version, where I don't fully understand why this is even related.

The problem might be hidden in some entangled places I believe, maybe we should just update the `substrate-api-client` version and carry on 

```
error: failed to select a version for `frame-metadata`.
    ... required by package `substrate-api-client v0.10.0 (https://github.com/scs/substrate-api-client.git?branch=polkadot-v0.9.39#d872c2ca)`
    ... which satisfies git dependency `substrate-api-client` of package `itc-parentchain-indirect-calls-executor v0.9.0 (/home/kai/litentry-parachain/tee-worker/core/parentchain/indirect-calls-executor)`
    ... which satisfies path dependency `itc-parentchain-indirect-calls-executor` of package `itc-parentchain v0.9.0 (/home/kai/litentry-parachain/tee-worker/core/parentchain/parentchain-crate)`
    ... which satisfies path dependency `itc-parentchain` of package `itp-enclave-api v0.9.0 (/home/kai/litentry-parachain/tee-worker/core-primitives/enclave-api)`
    ... which satisfies path dependency `itp-enclave-api` of package `itc-rpc-server v0.9.0 (/home/kai/litentry-parachain/tee-worker/core/rpc-server)`
    ... which satisfies path dependency `itc-rpc-server` of package `litentry-worker v0.9.0 (/home/kai/litentry-parachain/tee-worker/service)`
versions that meet the requirements `*` are: 16.0.0

the package `substrate-api-client` depends on `frame-metadata`, with features: `v14` but `frame-metadata` does not have these features.
```

**Comment by haerdib** [comment]
Looks like it.. I also think, upgrading might be worth it. Sorry I couldn't help here.

**Comment by Kailai-Wang** [comment]
> Looks like it.. I also think, upgrading might be worth it. Sorry I couldn't help here.

All good, thanks for looking into it!

**Comment by Kailai-Wang** [comment]
The problem doesn't occur with 0.9.42 deps, at least I could do `cargo update` - it still doesn't compile as it requires a newer toolchain version, but that's another problem
