### ISSUE TITLE
zombienet implementation

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#1993]
Due to the natural case of Test purpose, Astar team using a [zombienet](https://github.com/paritytech/zombienet) tool to implement their RPC test. should we adapt this approach?

The issue is related to #1847. 
An old research issue #1070 has been posted before.

**Comment by Kailai-Wang** [comment]
Can you set the labels please? :) We need to check the priority and schedule it accordingly

**Comment by wangminqi** [comment]
We do not need so far.
