### ISSUE TITLE
Have a campaign stress test report/summary

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1994]
### Context

Follow-up task of #1966 - we are starting to get some numbers :)

It makes sense that we put them all together and compose a written summary in notion, including:
- a `TL;DR` section (for non-tech guys)
- test setup: hardware, parachain/enclave setup, test goal
- (optional) commands used for testing
- what gets tested exactly?
- the test result, including the datasheet (you can upload them in notion) as well as any diagrams

Test code should be cleaned up and committed to the repo: https://github.com/litentry/litentry-parachain/issues/1995

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
I can write the report once we're done with the spike run o7

About committing the scripts to the repo, I assume you mean merging them into `dev`? If so then we should clean them up a bit before that; let's give that task its own issue please :pray:

**Comment by Kailai-Wang** [comment]
I do - let me do it and edit the description

**Comment by arieljbirnbaum** [comment]
Done :heavy_check_mark:
