### ISSUE TITLE
Cleanup and commit the stress test code to the repo

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#1995]
### Context

Follow-up task of #1966 - the code can be inspirational/reused for the next stress test :) 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by arieljbirnbaum** [comment]
@Kailai-Wang thanks :raised_hands: 

We did a heap of quick and dirty duplication when setting up the stress scripts just to get it going quickly; we should take a moment to refactor that before merging it in.

Also, we should add a short step in CI to exercise the code (2-3 iterations should be enough) just to make sure it keeps up with subsequent API changes. To be clear though, I _wouldn't_ add stress testing as a CI step; this is only to make sure that the stress code stays in sync so we can run it when needed.

**Comment by Kailai-Wang** [comment]
Thanks for the heads-up.
No problem. This one is not so urgent, you can take your time :)

**Comment by kziemianek** [comment]
@grumpygreenguy can we close this issue ?
