### ISSUE TITLE
Update integritee-node  

### ISSUE THREAD

**Issue by felixfaisal** [litentry/litentry-parachain#2001]
### Context
Currently, The integrations and the tests are written in `TS` are tested against the `Integritee-node`, the reason being it's block target time is around 1s making it really fast and convenient for the devs. However, This node is not actively maintained because of which it has fallen behind and therefore there is a difference in metadata between the `litentry-worker` and `integritee-node` 

### Task
We should able to check the diff between the pallets and identify difference in any types and update accordingly, if possible to update or else we have to think of alternatives. 

### Acceptance criteria
We should be able to test integration-scripts against this node once spun up.

**Comment by Kailai-Wang** [comment]
Deprecated as we have standalone mode now
