### ISSUE TITLE
Explore the notion API access with authorisation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2006]
### Context

To see if we could retrieve the (private) page content programmatically.

Ref: https://developers.notion.com/docs/authorization

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by songzhouran** [comment]
As [this doc](https://developers.notion.com/reference/retrieve-a-page) shows, we can get page contect as long as we provide a notion apikey.

**Comment by songzhouran** [comment]
I tried to get a page using curl, and succeeded. Here is [doc](https://developers.notion.com/reference/retrieve-a-page) for retrieving a page. We can use this http request like this: https://api.notion.com/v1/pages/{page_id}

**Comment by outofxxx** [comment]
The notion data can now be read by using api key, and this issue can be closed.
