### ISSUE TITLE
Remove bounty system call filter

### ISSUE THREAD

**Issue by qiuhaiguo** [litentry/litentry-parachain#2019]

**Comment by Kailai-Wang** [comment]
Hi @wangminqi , can you please take this one?

Just check if the pallet is correctly configured, and remove the call filter if so - for litentry parachain :)

**Comment by wangminqi** [comment]
sure

**Comment by wangminqi** [comment]
https://web3builders.notion.site/Parachain-How-to-use-pallet_bounty-102454bb599f46f6b50c563810e5546f
As user guidance.
