### ISSUE TITLE
Launch errors(updating)

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#2028]
For this launch, various errors or failed events on the [parachain](https://polkadot.js.org/apps/?rpc=wss://tee-staging.litentry.io:443#/explorer) will be listed here for future analysis or review. If this issue is duplicated with other issue records, please close this issue.

1. [identityManagement.LinkIdentityFailed ](https://polkadot.js.org/apps/?rpc=wss://tee-staging.litentry.io:443#/explorer/query/0xf5983f5beea43a3d02fb1dbfeb7cbb430d7701755d4ca17d704d4a2e9fab0ca5)-> UserShieldingKeyNotFound

**Comment by outofxxx** [comment]
2. [identityManagement.LinkIdentityFailed](https://polkadot.js.org/apps/?rpc=wss://tee-staging.litentry.io:443#/explorer/query/0x191611c0837f02eb736bfd1571c6d095c07d4c22ddb23e0bf466376a73cb4198) -> WrongWeb2Handle

**Comment by outofxxx** [comment]
3. [identityManagement.LinkIdentityFailed](https://polkadot.js.org/apps/?rpc=wss://tee-staging.litentry.io:443#/explorer/query/0x0c2b085cdef6cdea64d00d46f465d01f937d2f98d881743678449e8b9178c6e9) -> RequestError("HttpError(429, \"Too Many Requests\")")

**Comment by kziemianek** [comment]
> 2. [identityManagement.LinkIdentityFailed](https://polkadot.js.org/apps/?rpc=wss://tee-staging.litentry.io:443#/explorer/query/0x191611c0837f02eb736bfd1571c6d095c07d4c22ddb23e0bf466376a73cb4198) -> WrongWeb2Handle

There is no known problem other than user sending either wrong handle or discord message link. We plan to change IdHubber responding strategy to reduce the risk of user's picking up wrong discord message link. For now there is no issue in the code on the parachain side.

**Comment by Kailai-Wang** [comment]
We should convert the bugs we found to issues if not already - these errors are not necessarily bugs (e.g. we haven't found problems with`WrongWeb2Handle` - so far it's been erroneous actions from clients)

**Comment by outofxxx** [comment]
close it
