### ISSUE TITLE
Revisit logs in the worker

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2040]
### Context

Things to check:
- log levels: `dev` vs `prod`
- logging of sensitive information: `dev` vs `prod`
- remove redundant logs: our worker log size grows rapidly

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by kziemianek** [comment]
I've opened pull request that at least removes sensitive data information logs being produced from our source code.
There is sitll a possibility that node operator can run sidechain node with different logging configuration leading to logs containing sensitive data for example in form of raw bytes produced by 3rd party crates.

**Comment by kziemianek** [comment]
I think we can force logger to not read env variables for production build. That could lead to exact same logging for sidechain nodes.
