### ISSUE TITLE
Too wild upper bound for VC request

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2045]
### Context

E.g. this is the "total tx count" VC that I got:
<img width="732" alt="image" src="https://github.com/litentry/litentry-parachain/assets/7630809/f9fe0b6a-420b-4170-a80c-038baadc5928">

The upper bound is obviously too large.
Is it from our code or data providers?

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
https://github.com/litentry/litentry-parachain/blob/90fa4c2281f077ff1f619076c0013c153b53c141/tee-worker/litentry/core/assertion-build/src/a8.rs#L87C1-L88C1

`500 	<= X < u64::Max		=> true`

This is the last interval of A8, which is the u64::Max

Alternatively, the last interval can be modified to only retain 500 without displaying the maximum number

```json
                   {
                        "src":"$total_txs",
                        "op":">=",
                        "dst":"500"
                    }
```

**Comment by kaylawangnow** [comment]
sounds good

**Comment by arieljbirnbaum** [comment]
@kaylawangnow Note that removing the upper bound clause will require a change in the client logic to cope with the special case (i.e. IDHub currently expects that clause to be there when parsing the assertion).
