### ISSUE TITLE
A11 VC request fails due to io error

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2047]
### Context

It happened sometimes.

We got 

```
[2023-08-14T12:25:00Z ERROR lc_assertion_build::a11] Assertion A11 request is_holder error: AchainableError("Achainable response error: Error: IO error")
```

Still can't reproduce it reliably, it might be related to the linked identities.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
This bug is difficult to reproduce, I will continue to track this issue.

**Comment by outofxxx** [comment]
Another `IO ERROR` in oneblock assertion: https://litentry.slack.com/archives/C03KR96989G/p1694479103267659?thread_ts=1694418168.198069&cid=C03KR96989G

**Comment by Kailai-Wang** [comment]
haven't received reports for a while, closing now.
