### ISSUE TITLE
Branch versions on staging env

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#206]
After we submit the genesis state/wasm, we have to think about how commits should be tested on staging env.

We are not doing runtime-upgrade for every single functionality change.

If the staging env pulls the release branch, only the commits between different releases could be tested (i.e. commits in a batch for runtime upgrade)
If the staging env pulls the dev branch, then we need to purge and restart the staging network frequently.

**Comment by Kailai-Wang** [comment]
Current idea:

- The dev network should be sufficient for testing "normal commit"
- In principle, the staging network will only be updated when a runtime-upgrade is committed, e.g. release-v0.9.0 -> v0.9.1
- If requested, the staging network could also be purged and restarted to test one single commit, but on the verge of runtime-upgrade it will be rolled back to the original state to test a "clean" runtime upgrade.

For the branching strategy in runtime upgrade with storage migration, see #224

**Comment by Satoshi-Kusumoto** [comment]
Close this because all the todos are shifted to #224
