### ISSUE TITLE
Create 3 notion assertions for OneBlock+ usecase

### ISSUE THREAD

**Issue by kaylawangnow** [litentry/litentry-parachain#2067]
### Context
OneBlock+ wants 3 credentials based on the data in this notion page they provide:
https://www.notion.so/28edcbda1ef24e0085ae606e8c6bc2a2

<img width="832" alt="image" src="https://github.com/litentry/litentry-parachain/assets/86393764/cdfb102f-072a-441e-b408-4ee208d270f9">

### Task
- Create 3 assertions based on the data in the table in that notion page
- OneBlock+ will give us finalized content for `type` & `description`, before we have that please use mock content in this ticket. The access control of that notion page is restricted, please provide one email address of our developer to get the access, for others to test, let's use a mock notion page table.

1. OneBlock+ Substrate Dev Undergraduate
`type`: OneBlock+ Substrate Dev Undergraduate
`description`: You are a undergraduate student of the OneBlock+ Substrate developer course.
Ruleset: if "yes", assertion valid; if "no", assertion invalid; if others, assertion invalid

2. OneBlock+ Outstanding Substrate Developer
`type`: OneBlock+ Outstanding Substrate Developer
`description`: You are an outstanding student of the OneBlock+ Substrate developer course.
Ruleset: if "yes", assertion valid; if "no", assertion invalid; if others, assertion invalid

3. OneBlock+ Substrate Dev Beginner
`type`: Substrate Blockchain Development Course Participation
`description`: Congratulations on completing the entire course jointly created by OneBlock+ and Parity:《Introduction to Substrate Blockchain Development Course》, Phase 12.
Ruleset: if data is "第六课", assertion valid; if data is "第一课"~"第五课", assertion invalid; if others, assertion invalid

### Acceptance criteria
- Assertions needs to be ready before Sept.7th

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by outofxxx** [comment]
The `type` and `description` of 2 and 3 are the same, is this intentional?

**Comment by kaylawangnow** [comment]
> The `type` and `description` of 2 and 3 are the same, is this intentional?

I updated it ty

**Comment by outofxxx** [comment]
If after querying the address, if found that `invalid`, which type and des should be displayed?

**Comment by kaylawangnow** [comment]
> 3\. Ruleset: if data is "第六课", assertion valid; if data is "第一课"~"第五课", assertion invalid; if others, assertion invalid

same type and des, 'value' is invalid

**Comment by kaylawangnow** [comment]
please update type and description based on excel file: https://docs.google.com/spreadsheets/d/1k2ZvrLK5v_KO_tsCWJVtjbs8TS8PzM_idWv64z4ynSI/edit?pli=1#gid=1065809408
ty
