### ISSUE TITLE
Define the correct Achainable type 

### ISSUE THREAD

**Issue by 0xverin** [litentry/litentry-parachain#2080]
### Context
Currently, we are unable to define the achainable type correctly. It seems that manual modifications are required after building in order to use it, which is not feasible. We need to discuss this.

Additionally, I've examined the code in IDHub:

1. They manually created the [achainable](https://github.com/litentry/identity-hub/blob/bcb04d90a7e2b42a65284e077f21044505098344/libs/chain-types/src/lib/interfaces/vcManagement/types.ts#L49) type. 

2. Here, [CorePrimitivesAssertion](https://github.com/litentry/identity-hub/blob/bcb04d90a7e2b42a65284e077f21044505098344/libs/chain-types/src/lib/interfaces/trustedCalls/definitions.ts#L66C59-L66C82) is declared, but it is changed to [Assertion](https://github.com/litentry/identity-hub/blob/bcb04d90a7e2b42a65284e077f21044505098344/libs/chain-types/src/lib/interfaces/trustedCalls/types.ts#L63) manually after building.

In any case, achainable should either be manually defined in the definitions or directly generated by the parachain for use, rather than being modified after building.

**Comment by Kailai-Wang** [comment]
resolved by https://github.com/litentry/litentry-parachain/pull/2275
