### ISSUE TITLE
Typescript packages for client API (parachain+sidechain)

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#2087]
### Context

Downstream projects have a hard time keeping up with API changes, especially changes in the runtime and RPC data types. We seek to alleviate that by publishing these in appropriate packages and setting up our build pipeline to keep these up to date.

Note: ideally, we would be able to generate these automatically from the parachain+worker code without any manual intervention. However, there are two limitations:

* The metadata (which we need for type generation) isn't generated statically on build; it has to be retrieved via a live query. That means we need to start a process, and then fetch the metadata from that process in order to proceed. Since the process may be running on non-default ports, we need to make sure these ports are passed to the generation process in order to get the correct metadata version.
* Even worse, the types for RPC methods are [_not_ exported with the metadata](https://github.com/litentry/litentry-parachain/issues/1878) (or anywhere else). As long as we have custom RPC calls, the types for these need to be maintained manually :sadpanda: 

### Tasks

This project involves several steps; individual issues are linked below:

- #2088 
- #2089
- #2090 
- #2091
- #2092
- #2093
- #2095
- #2096

### Acceptance criteria

This issue will be considered done once we have the first successful integration of the published packages with a downstream application.

---

**Comment by kziemianek** [comment]
@Verin1005 @grumpygreenguy is there anything to be done here or this can be closed ?

**Comment by 0xverin** [comment]
> can be closed

Thanks.Can be closed.
