### ISSUE TITLE
Publish API packages to Github npm registry

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#2089]
### Context

Part of #2087 
:warning: Blocked by #2088 

### Task

- Check we have the appropriate configuration for packaging and distribution (esp. package.json and tsconfig.json); refer to the appropriate documentation.
- Follow the Github documentation to publish the packages to the [npm registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-npm-registry)
  - :warning: Make sure to publish to Github packages rather than npmjs.com!
  - :warning: :rotating_light: Make sure to change the `version` in `package.json` to some unique value, e.g. `0.0.0-df234014`; any given version of a package can only be published _once_!.

### Acceptance criteria

_On a temporary branch_, change the ts-tests to point to the published packages. Check that `yarn install` works and the tests run successfully. **Do not merge this change to dev** before we've set up the rest of the pipeline (otherwise, changes to the Rust code will break the tests and would require manual publishing to fix).

**Comment by 0xverin** [comment]
Already published to github registry  and it worked for local. Close this issue now.
