### ISSUE TITLE
Github action for API package publication

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#2091]
### Context

Part of #2087 
:warning: Blocked by #2090 

### Task

- Create a Github action to trigger publication of the API packages with their given version.
  - If the given version was already published, check the checksum of the published version:
    - If it matches the current one, continue normally
    - Otherwise, fail with an error (the version number needs to be bumped)
  - Tag the given version with the current branch name
- NOTE: We should _not_ bump the version number automatically!
- The action will need to authenticate to Github using a token. We should set up a shared "CI/system" user for this (i.e. **not** an individual developer's token).
  - The token needs to be added to the repo secrets
  - the token needs to be written into the `~/.npmrc` file when running the action

### Acceptance criteria

A new version of the packages successfully published and tagged _by another team member_ via the CI action

**Comment by 0xverin** [comment]
> If it matches the current one, continue normally
>Otherwise, fail with an error (the version number needs to be bumped)

I don't quite understand this part. If the version we have given exists on the GitHub registry, shouldn't it be a failure?

>The action will need to authenticate to Github using a token. We should set up a shared "CI/system" user for this (i.e. not an individual developer's token).

We need to prepare this in advance and set it to `Action Secrets and Variables`, who has access to this at the moment?

**Comment by arieljbirnbaum** [comment]
> > If it matches the current one, continue normally
> > Otherwise, fail with an error (the version number needs to be bumped)
>
> I don't quite understand this part. If the version we have given exists on the GitHub registry, shouldn't it be a failure?

Consider a scenario like this:

* Make some changes on dev and bump the version to 3.4.5
* Merge the changes to dev and publish
  * The tag `dev` now points to 3.4.5 :heavy_check_mark: 
* Now we try to merge dev into staging and publish
  * The script fails because 3.4.5 already exists :sadpanda:

So the idea is, if this version has already been published, we should still be able to update a different mainline tag to point to it. To be fair tho, we can do that manually if the need arises --- especially since the script would have to make sure that the version we were trying to publish indeed matches the already published one (ie. not just the number but the _contents_). Let's leave that out for now then :P
