### ISSUE TITLE
Add package building step to CI

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#2093]
### Context

Part of #2087 
:warning: Blocked by #2092 

### Task

Instead of having build outputs committed to the repo, we should rebuild them when needed to run the tests.

- If possible: add one CI step before the ts-tests to build the packages and pass the build outputs as [artifacts](https://docs.github.com/en/actions/using-workflows/storing-workflow-data-as-artifacts)
- If the above is not possible, add the build as needed before running each ts-test (:sadpanda: because it makes the tests longer/heavier)

- Remove the committed metadata and build outputs from the repo (and .gitignore them)

### Acceptance criteria

- Build outputs and intermediate files are gone from the repo
- CI passes

**Comment by 0xverin** [comment]
>Remove the committed metadata and build outputs from the repo (and .gitignore them)

Do we need to temporarily retain the metadata commits because the CI requires fmt checks(client-api needs to build first)?
