### ISSUE TITLE
Publish API packages

### ISSUE THREAD

**Issue by arieljbirnbaum** [litentry/litentry-parachain#2096]
### Context

Part of #2087 
:warning: Blocked by #2093 
:warning: Blocked by #2091 

### Task

- Add basic usage documentation for downstream users
- Publish the first "official" release
- Coordinate integration with IDHub

### Acceptance criteria

IDHub imports the package successfully. NOTE: full integration (i.e. fully replacing custom IDHub code with the new packages) is beyond the scope of this issue.

**Comment by Kailai-Wang** [comment]
This is done
