### ISSUE TITLE
Create a new branch for next IDHub launch

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2130]
### Context

It might sound trivial, but we need to:

1. communicate with IDH about what's included in their next product launch
2. decide on the commit where the fork should be branched from `dev`
3. create a dedicated branch, something like `idhub-v0.4`?
4. cherry-pick commits to the new branch - this should match what's agreed in step 1

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by BillyWooo** [comment]
Conclusion and todo list from a discussion:
1. current branch `staging` (9c2a5d37) is good enough for next IDHub (v0.4) launch. It will be kept as it is.
2. create a new `next_staging` based on the current latest `dev` branch (1bec274b).
3. double check the difference between branches of `9c2a5d37` and `1bec274b`, and create a migration guideline doc about the breaking changes for IDHub team.

**Comment by arieljbirnbaum** [comment]
Branch: `release-p0.9.17-9170-w0.0.1-0100`
Current RC Tag: `p0.9.17-9170-w0.0.1-0100`

Draft changelog (between `staging` and RC): https://docs.google.com/spreadsheets/d/1SdBBnkNOabG2vOBkR8DX_qxxA_xm1UrTy9Vir2rQzoo/edit?usp=sharing

"Missing" changes appear on `staging` but not on the release branch :warning: 

"New" changes appear on the release branch but not on staging; "internal" changes (deployment, testing, etc) have been filtered out. Some changes have been left in where potentially relevant for development (e.g. cli changes).

**Comment by arieljbirnbaum** [comment]
Release draft job completed successfully: https://github.com/litentry/litentry-parachain/actions/runs/6906217504/job/18793212873
Simulate runtime upgrade [doesn't seem to find the runtime file](https://github.com/litentry/litentry-parachain/actions/runs/6909787406/job/18801755953#step:6:10); trying different params.

**Comment by arieljbirnbaum** [comment]
Completed by @Kailai-Wang
