### ISSUE TITLE
Try refactoring the achainable API

### ISSUE THREAD

**Issue by outofxxx** [litentry/litentry-parachain#2154]
Based on the current issues with the achainable API, @BillyWooo and I have a general discussion.

This is an experimental issue.

* Background:

The current process for creating a new assertion is as follows:

1. Obtain the requirements and find the API supported by `Achainable`

2. Implementation in Worker: 
> 1 Prepare data for the new assignment 
> 2 Implement a new assignment API
> 3 Send HTTP request
> 4 Generate VC 
> 5. Return to IDHUB

* Existing problems:
If we need to add a new Assertion every time, we must implement steps 1 and 2 on the worker side

For workers, it is tedious. 
For IDHUB, the new assertion needs to be implemented by the worker first.

* Solution:

Because `system-label` has already been implemented in the worker which is an atomic request, so steps 1 and 2 can be adjusted as follows:
1. Place the data structure of the new assertion on the IDHUB end for combination. (such as JSON format)
2. The worker passes parameters through the `system-label` interface and requests `achainable` data.

The subsequent steps remain unchanged.

What kind of assignment does `IDHUB` want to implement in this way, directly reference the `achainable` API to spell out the desired parameters, and directly request the `system-label` is sufficient, and there is no longer a need to wait for the worker to implement it.

More flexible and fast.

* Possible situations:

For example, situations like `A8` or `class of year` that require special handling require separate processing on the worker side.

**Comment by kziemianek** [comment]
Hi @zhouhuitian , do you mind posting an example request sent by IdHub and generated VC ?

**Comment by outofxxx** [comment]
> Hi @zhouhuitian , do you mind posting an example request sent by IdHub and generated VC ?

This is a previous discussion. I just started writing this small demo.

**Comment by outofxxx** [comment]
After [discussion](https://www.notion.so/web3builders/Trying-to-refactor-achainable-api-24749d4990334b1fb1b9e2522d6e4c10), We felt that the significance was not significant, so we cancelled this issue.
