### ISSUE TITLE
Deprecate `Currency` trait in favor of `fungible`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#2176]
### Context

A follow-up refactoring of v0.9.42 upgrade.

See: https://forum.polkadot.network/t/polkadot-release-analysis-v0-9-41-v0-9-42/2828

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
currently no need to change after 0.9.42 pr

**Comment by wangminqi** [comment]
Deprecate Currency trait in favor of fungible is referred to change user from old logic to latest.
Stuffs like if a user valid in old fashion (ED>free, but ED<free+reserve) should now transfer into new logic (The solution can be automatically give balance ED if meeting specific condition).

**Comment by wangminqi** [comment]
<img width="778" alt="image" src="https://github.com/litentry/litentry-parachain/assets/46511820/eceaf9ea-04cc-4f19-a7ea-dd304054a980">

**Comment by wangminqi** [comment]
We should patiently wait for parity providing a script for account upgrade.
