### ISSUE TITLE
Best practice of OnRuntimeUpgrade code

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#224]
For the future runtime upgrade:
- if no storage migration is involved, we could just update the code and compile the wasm
- if storage migration is required, we need to figure out:
  - how the code should be committed
  - in which branch the code should be committed (feature-branch/dev/release-branch)
  - how does the code need to be cleaned up (or if at all)

Possible ways to find it out:
- study substrate (historical) code
- study other projects

This issue is only about research and design.
For the real testing we need another issue.

**Comment by Satoshi-Kusumoto** [comment]
Generally if we understand how can we clean up the migration code, it's done

**Comment by Kailai-Wang** [comment]
Doc:
https://www.notion.so/litentry/Storage-Migration-in-runtime-upgrade-7b8adaab7f1c4c8c82793d10b5854254#ae90d0c383554d99b5dfbf6604cddf2f

**Comment by Kailai-Wang** [comment]
Added code examples
