### ISSUE TITLE
Set up a load balanced RPC node network for production env

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#227]
Follow up of #218 

We need to:
- [x] setup 2 RPC nodes
- [x] acquire domain names for both RPC nodes, e.g. `rpc0.parachain.litentry.io` and `rpc1.parachain.litentry.io` - just a suggestion.
- [x] generate p2p keys for both RPC nodes
- [x] change the chain-spec so that only RPC nodes are defined as bootnodes
- [x] setup an LB for both RPC nodes and provide a domain name to submit to polkadot, e.g. `rpc.parachain.litentry.io`. This is the endpoint for polkadot-js.
- [x] adjust the ansible deployment scripts to include RPC nodes

**Comment by Kailai-Wang** [comment]
We need:
- a load balancer for 2 RPC nodes (current plan)
- optional: a domain name (gateway) for LB access, e.g. `rpc-parachain.[staging.]litentry.io` - just a suggestion.
- add these RPC nodes to bootnodes?

**Comment by Kailai-Wang** [comment]
In review.
Ansible scripts updated in another repo.

Load-balanced entry point for our production network:
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.parachain.litentry.io#/explorer
