### ISSUE TITLE
Failing container when accessing /bin/sh

### ISSUE THREAD

**Issue by shanithkk** [litentry/litentry-parachain#2279]
### Context
i was trying to automate the building and creating build spec and genesis wasm from inside the container so im getting error like missing /bin/sh in the image.
```docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "bin/sh": stat bin/sh: no such file or directory: unknown.```

There is any other reason to remove the shell from the container 

### Task

Can you remove the statement in the docker file for removing the /bin/sh file 

### Acceptance criteria

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Thanks for the report

The binaries are intentionally removed to shrink the image size as well as reduce the attack interface, see

https://github.com/litentry/litentry-parachain/blob/a486e784eb0da1508c7973bbbd58c49c46db37bc/docker/Dockerfile#L38-L39

If you want to have them, you can simply comment the line out and rebuild the docker

**Comment by shanithkk** [comment]
> If you want to have them, you can simply comment the line out and rebuild the docker

Thank you @Kailai-Wang for the reply. if you could do it, its very helpfull to us.otherwise we again need to maintain the docker image with your future updates

**Comment by Kailai-Wang** [comment]
We can do that.

I have a PR that reverts the removal : )

**Comment by shanithkk** [comment]
@Kailai-Wang , can you update the docker image also

**Comment by Kailai-Wang** [comment]
> @Kailai-Wang , can you update the docker image also

Hi @shanithkk I believe `litentry/litentry-parachain:latest` contains the change already

**Comment by shanithkk** [comment]
Hi @Kailai-Wang , Thank you so much for helping us out here
