### ISSUE TITLE
Consider remove automatically remove branch after merged

### ISSUE THREAD

**Issue by geastwood** [litentry/litentry-parachain#262]
There is a setting controlling this. If it makes sense, consider turning on this flag.

**Comment by Kailai-Wang** [comment]
As far as I understand @h4n0 , there was a round of discussion a long time ago and the result was to **not** activate this.

If we decide to enable this later, we need to take care that **no** `release-*` branch will be deleted in this way (even after it's merged/backported)

**Comment by Kailai-Wang** [comment]
close it as not in the current round of discussion
