### ISSUE TITLE
Implement `pallet-drop3` with unittests and benchmarking

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#273]
- [x] Implementation `pallet-drop3` according to [SW requirements](https://www.notion.so/litentry/Drop3-Software-Requirement-a4f17c322add40db832c0cbe75bad065)
- [x] Unittests
- [x] Optional benchmarking
- [x] Update/deploy the drop3-testnet with this pallet

**Comment by Kailai-Wang** [comment]
Current status: in review.
