### ISSUE TITLE
Onboarding Nitesh

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#287]
What have been done:
- show around notion pages
- show around Github repo/rundeck/grafana/..
- send links/read materials for starting

TODO:
- [x] add Nitesh to parachain repo and devops repo
- [x] pass the devops ssh key to Nitesh
- [x] rundeck account setup
- [x] grafana account setup
- [x] alert mixer invitation
- [x] AWS account setup
- [x] docker.hub account setup
- [x] setup element account and add to groups

**Comment by Kailai-Wang** [comment]
All the accounts/information are handed over.

**Comment by geastwood** [comment]
Awesome, thank you @Kailai-Wang and @chenzongxiong
