### ISSUE TITLE
Submit litmus parachain-metadata to polkadot

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#295]
We are going to need to submit the following metadata for our kusama-parachain to polkadot:

- [x] [SS58Prefix registry](https://github.com/paritytech/ss58-registry)
- [x] color of parachain-banner 
- [x] Entrypoint (rpc-node) of parachain network

**Comment by Kailai-Wang** [comment]
SS58Prefix registry PR submitted: https://github.com/paritytech/ss58-registry/pull/70

**Comment by chenzongxiong** [comment]
PolkadotJS dashboard PR: https://github.com/polkadot-js/apps/pull/6849

**Comment by Kailai-Wang** [comment]
Submitted.

SS58Prefix setting is still waiting for approval, others are merged.
