### ISSUE TITLE
Add code/test coverage support upon PR creation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#315]
It would be good to have an automated test coverage report, especially for our own pallets.

Tools:
- https://about.codecov.io/
- https://github.com/xd009642/tarpaulin
- https://github.com/actions-rs/tarpaulin

A sharing session is worth it.

**Comment by Kailai-Wang** [comment]
An example of the codecov report from Acala:

![image](https://user-images.githubusercontent.com/7630809/150673913-f21cb89f-e5d8-4655-86cf-37e30d8d65d4.png)

**Comment by Kailai-Wang** [comment]
This ticket needs to be resolved in the near future as well

**Comment by BillyWooo** [comment]
https://codecov.io/github/litentry/litentry-parachain/commit/1976048b10a79e6ff809bf9bada35126ac6a1f8a

https://github.com/litentry/litentry-parachain/pull/658
