### ISSUE TITLE
Differentiation between different cargo profiles

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#326]
It's mentioned here that using LTO flag would compile into a more efficient binary at the cost of longer compilation time:
https://github.com/paritytech/polkadot/issues/4311
https://github.com/paritytech/substrate/issues/10608

We might want it to build the releasing binary instead using the default release profile.

**Comment by geastwood** [comment]
Is it still experimental, or is it for production?

**Comment by Kailai-Wang** [comment]
> Is it still experimental, or is it for production?

For production, at least moonbeam is already using this in their released binaries.
If polkadot/substrate decides to follow, we could do that too.

**Comment by ggwpez** [comment]
> If polkadot/substrate decides to follow, we could do that too.

Already the case, see https://github.com/paritytech/polkadot/issues/4311#issuecomment-1020983745

**Comment by Kailai-Wang** [comment]
> > If polkadot/substrate decides to follow, we could do that too.
> 
> Already the case, see [paritytech/polkadot#4311 (comment)](https://github.com/paritytech/polkadot/issues/4311#issuecomment-1020983745)

Thank you for letting us know, will follow up

**Comment by Kailai-Wang** [comment]
https://github.com/paritytech/polkadot/pull/4778

**Comment by Kailai-Wang** [comment]
Extended to 2 days as it involves a differentiation between different cargo profiles
see:
https://doc.rust-lang.org/cargo/reference/profiles.html
https://github.com/paritytech/polkadot/blob/master/Cargo.toml

**Comment by Kailai-Wang** [comment]
locally it took me 78min to compile the `litentry-collator` binary with production profile
