### ISSUE TITLE
Drop3 Milestone 2 Design & Req. Analysis

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#335]
In this story, milestone 2 of the drop3 pallet will be discussed in detail.

- [ ] Design doc.
- [ ] Requirement doc.

**Comment by jingleizhang** [comment]
For reference: https://github.com/litentry/drop3/issues/2

**Comment by Kailai-Wang** [comment]
- Do we have a doc?
- When to start to implement it?
- Who should do it?

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Drop3-Software-Requirement-a4f17c322add40db832c0cbe75bad065

**Comment by h4n0** [comment]
Blocked by https://github.com/litentry/drop3/discussions/68

**Comment by Kailai-Wang** [comment]
What's the status of this ticket? Any decision-making needed?
