### ISSUE TITLE
Launch a rococo parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#346]
**Update:** we will launch a rococo parachain, with the setup 2 collators + 1 rpc node.

---
Santiago reminded me of the possibility of having a long-lasting parachain testnet on rococo (we would have only 3 days lease period if we don't have a kusama/polkadot parachain):

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/7630809/153628041-7907de6b-1232-407b-a2ff-dc980957d2b0.png">

https://docs.substrate.io/tutorials/v3/cumulus/rococo/

I think the pros and cons are palpable:

➕ more public
➕ closer to real relaychains for testing/upgrading
➕ don't have to maintain relaychains
➕ potential XCMP testing

➖ resource and maintenance overhead

**Comment by Kailai-Wang** [comment]
Webapp colleagues ask for a stable public testnet too, I think rococo-net is the best place for it.
We should get this done either this sprint or the next one at its latest.

**Comment by h4n0** [comment]
This sounds great! Let's have a discussion about our future plan of Rococo and staging networks.

**Comment by Kailai-Wang** [comment]
paraId reserved: 2075

**Comment by Kailai-Wang** [comment]
new paraId: 2002

**Comment by Kailai-Wang** [comment]
PR to adjust upstream metadata: https://github.com/polkadot-js/apps/pull/7287

**Comment by Kailai-Wang** [comment]
Update: parity requires that the paraId is the same as Litmus for maintenance reasons.
So new paraId: 2106
