### ISSUE TITLE
Refine the basic monitoring system for litmus

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#347]
What we already have:
- a generic monitoring template for substrate-based chains in grafana
- AWS-based alerting system for host information

What we need:
- for monitoring the machine info of litmus collators, decide whether to use `prometheus-node-exporter` or AWS
- install `prometheus-node-exporter` on collators (if we go this way)
- alerting for basic abnormities, e.g. when connected peers are too few when blocks production takes too long..

**Comment by Kailai-Wang** [comment]
We probably need to step up on this, ideally it can be done within 1-2 weeks as the Litmus is LIVE now

**Comment by niteshb3495** [comment]
Defined a couple of important alerts.
1. Blocks Average per min - when the average blocks per min is less than 1 the alert will get triggered on the #alert slack channel
2. Peers count - when the peer count is less than 3 will trigger an alert in #alert slack channel

Please let me know if this looks good. Also, let me know if any other basic alerts needs to setup.

**Comment by h4n0** [comment]
Completed.
