### ISSUE TITLE
Rethink the standard workflow of runtime upgrade in prod env

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#348]
After the parachain is onboarded, we'd like to have a standardized workflow of testing/simulation before actually doing the runtime upgrade in the production env.

The main problem is how to simulate it based on the current on-chain state?

In my imagination, we should make use of one or multiple ways in the following:
- `try-runtime` command
- fork-off-substrate with the local trial run?
- staging? Do we need to re-deploy the network with the matching on-chain state?
- rococo?

It would be good if we can document this.

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Runtime-Upgrade-Requirement-c67fed490cbe4aeaad628ac5c484ca02

**Comment by Kailai-Wang** [comment]
Thank you, I'll create a follow-up issue based on this research
