### ISSUE TITLE
TokenBridge integration test before activation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#351]
Before tokenBridge pallet is officially enabled on parachain, we shall test it thoroughly. This might require cooperation of multiple parties: frontend, parachain, devops, setup for ETH nodes

we also need documentation about how to use this bridge.

**Comment by Reminiscense** [comment]
Do we have ETA activation of the token bridge ?

**Comment by Kailai-Wang** [comment]
All tasks done, token bridge went online, closed.
