### ISSUE TITLE
Initial population of parachain gitbook

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#354]
The current documentation status of parachain in litentry gitbook is very raw and far from completion.

We need to start to populate things.
As the first step, we shall write a preliminary skeleton, as for content we either put short descriptions, attach links or just leave an announcement that it will be added soon

Not yet sure how urgent it is but I have the impression that the deadline is very close.

**Comment by wangminqi** [comment]
Our current parachain skeleton:
   parachain:
         --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --Token Bridge
                   --Drop3
                   --NFT pallet
         --Developer Document
                   --how to run local parachain
                   --token bridge
                   --Drop3
                   --NFT pallet

I suggest we change it into:
   parachain:
         --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --TEE? :
                          -- (introduce TEE here)
                   --Token Bridge:
                          -- (introduce token bridge here)
                   --Drop3 :
                           -- (introduce drop3 reward / staking mechanism here)
                   --NFT pallet (remove it?)
           --developer document:
                 --parachain:
                      --how to run local parachain
                      --litentry/litmus parachain setting, network id, wss url etc
                      -- rpc document?
                 --Token bridge:
                      --LIT ethereum token address, token bridge contract address,etc (related to token bridge)
                      --Token Bridge (introduce the step of cross chain action)
                 --TEE ?

**Comment by wangminqi** [comment]
Our current parachain skeleton:
   parachain:
         --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --Token Bridge
                   --Drop3
                   --NFT pallet
         --Developer Document
                   --how to run local parachain
                   --token bridge
                   --Drop3
                   --NFT pallet

I suggest we change it into:
   parachain:
         --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --TEE? :
                          -- (introduce TEE here)
                   --Token Bridge:
                          -- (introduce token bridge here)
                   --Drop3 :
                           -- (introduce drop3 reward / staking mechanism here)
                   --NFT pallet (remove it?)
           --developer document:
                 --parachain:
                      --how to run local parachain
                      --litentry/litmus parachain setting, network id, wss url etc
                      -- rpc document?
                 --Token bridge:
                      --LIT ethereum token address, token bridge contract address,etc (related to token bridge)
                      --Token Bridge (introduce the step of cross chain action)
                 --TEE ?

**Comment by wangminqi** [comment]
Our current parachain skeleton:
   parachain:
             --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --Token Bridge
                   --Drop3
                   --NFT pallet
         --Developer Document
                   --how to run local parachain
                   --token bridge
                   --Drop3
                   --NFT pallet

I suggest we change it into:
   parachain:
         --Litmus rollout plan
         --Litentry rollout plan
         --Modules:
                   --TEE? :
                          -- (introduce TEE here)
                   --Token Bridge:
                          -- (introduce token bridge here)
                   --Drop3 :
                           -- (introduce drop3 reward / staking mechanism here)
                   --NFT pallet (remove it?)
           --developer document:
                 --parachain:
                      --how to run local parachain
                      --litentry/litmus parachain setting, network id, wss url etc
                      -- rpc document?
                 --Token bridge:
                      --LIT ethereum token address, token bridge contract address,etc (related to token bridge)
                      --Token Bridge (introduce the step of cross chain action)
                 --TEE ?

**Comment by wangminqi** [comment]
Our current parachain skeleton:
   parachain:

-          --Litmus rollout plan

-          --Litentry rollout plan

-          --Modules:

                   --Token Bridge
                   --Drop3
                   --NFT pallet

-          --Developer Document

                   --how to run local parachain
                   --token bridge
                   --Drop3
                   --NFT pallet

I suggest we plan this:

   parachain:

-          --Litmus rollout plan

-          --Litentry rollout plan

-            --developer document:

                 --parachain:
                      --how to run local parachain
                      --litentry/litmus parachain setting, network id, wss url etc
                      -- rpc document?
                 --Token bridge:
                      --LIT ethereum token address, token bridge contract address,etc (related to token bridge)
                 --TEE ?

add one extra "Tools" in "Products":
-           --Token Bridge:
                          -- (introduce token bridge here, introduce the step of cross chain action)
             --Drop3 :
                          -- (introduce drop3 reward / staking mechanism here)
             --NFT pallet (remove it?)
             --TEE?

**Comment by Kailai-Wang** [comment]
I have something like this in my head:

- Introduction # one page of background information about the chains that we have (litmus/litentry)
- Technical overview
   - Litmus network
      - rollout plan
      - collation
      - full node
   - Litentry network #TBA
   - TEE #TBA
 - Pallets
   - token bridge
   - drop3
   - NFT
 - User documentation
   - how to interact with parachain
   - how to claim crowdloan rewards
   - how to interact with drop3
 - Developer documentation
   - build
   - launch a local dev network

What do you think? @wangminqi 
The title names can be changed, this just serves as a basic outline

**Comment by wangminqi** [comment]
Looks good.
I modify a little. Let's sync later

**Comment by Kailai-Wang** [comment]
Litmus rollout plan rework: https://app.gitbook.com/o/cVDw6U3xy2McEmnvJTMT/s/qZamGXeNdPKNQXKBWxz5/parachain/get-started/litmus-network/rollout-plan

**Comment by Kailai-Wang** [comment]
ready to be published.
I removed most of the "coming soon" section and added more content:
https://app.gitbook.com/o/cVDw6U3xy2McEmnvJTMT/s/qZamGXeNdPKNQXKBWxz5/parachain/introduction
