### ISSUE TITLE
Figure out the prometheus metrics for web3go

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#360]
As requested by web3go, we shall figure out the following two prometheus metrics in parachain node output:
- Avg processing time for transaction
- Avg block time

**Comment by Kailai-Wang** [comment]
https://www.notion.so/litentry/Prometheus-metrics-for-web3go-017ceab404ac4e6c978a041c137c4dda

@Moehringen 

Summary:
- Avg block time is clear
- Avg processing time for transaction is ambiguous, I suggest asking moonbeam for a more accurate definition

**Comment by Moehringen** [comment]
Avg processing time for transaction is ambiguous, I suggest asking moonbeam
for a more accurate definition

give me some hint?

Kai ***@***.***> 于 2022年2月23日周三 23:11写道：

**Comment by Kailai-Wang** [comment]
It's in the notion doc above @Moehringen
