### ISSUE TITLE
Automate runtime upgrade simulation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#371]
### Context

A follow-up task of #348 , after getting it working manually, we'd like to automate it via scripts or GAs.

### Task

This should be an Epic and include the following tasks at least:

- [x] #376
- [x] #372
- [x] #377
- [x] #378

And optionally
- [x] Script to build and run the try-runtime for each runtime release

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
all tasks are completed
