### ISSUE TITLE
Fork and adjust `fork-off-substrate` for our own purpose

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#372]
See the parent Epic description.

**Comment by wangminqi** [comment]
Besides, I think we should include a binary file for our each release. Just for convenience.

**Comment by Kailai-Wang** [comment]
> Besides, I think we should include a binary file for our each release. Just for convenience.

We do, see https://github.com/litentry/litentry-parachain/releases/tag/v0.9.3

The `0.9.3-1` release doesn't have it just because it's a runtime-only release (so you can still use the latest binary for it). Besides, the docker image is always there

**Comment by Kailai-Wang** [comment]
I think it's basically done:
https://github.com/litentry/fork-off-substrate/tree/adaption-for-litmus

The injection of the `Alice` as collator is not needed as long as the FORK_CHAIN is set correctly.

We should be able to close this issue.

**Comment by wangminqi** [comment]
Nice!
