### ISSUE TITLE
Build a token bridge relayer server monitoring and alerting system

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#399]
### Context
Relayers of token bridge need to be monitored to guarantee a sufficient journal is available when servers/processes run into errors. 

### Task
- [x] Collect logging data of all relayers
- [x] Alert (e.g. in a slack channel) when severe errors occur (e.g. process has been terminated)

### Acceptance criteria
The monitoring and logging system works normally on all relayer servers or separate servers.

**Comment by Kailai-Wang** [comment]
Is it possible to monitor the emitted metrics of this binary? The token bridge has native support for prometheus [metrics](https://github.com/ChainSafe/ChainBridge/blob/main/docs/metrics.md), I believe these 4 are all very important, especially `<chain>_latest_processed_block` and `<chain>_votes_submitted`.

`chain` should be either `eth` or `sub` depending on our config.
To have this we need to add `--metrics` onto the command line too.

It would be great if we could monitor this too (e.g. in grafana, similar to the blockrate in parachain), and alert for any abnormalities, like when latest_processed_block hasn't grown for a few minutes etc.

**Comment by Kailai-Wang** [comment]
Tagging @niteshb3495

**Comment by Kailai-Wang** [comment]
The relayer service is monitored.

Ideally we can monitor the metrics too but that's nice-to-have. Will open another issue if we need it, close this ticket for now.
