### ISSUE TITLE
Build a testing env for XCM with Moonriver parachain and Litmus parachain or two Litmus parachains

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#413]
### Context
XCM support.

### Task
Build a testing env for XCM with Moonriver parachain and Litmus parachain
There should be 3 relayer nodes at least.

### Acceptance criteria
Test env works, and both parachains produce blocks.

**Comment by h4n0** [comment]
First communicate with Moonriver for a testing solution.

**Comment by Kailai-Wang** [comment]
Update:
we are launching a testnet-parachain on moonbase relaychain network.
paraId: 2106
genesis state and wasm were [released](https://github.com/litentry/litentry-parachain/releases/tag/v0.9.5-1) and handed over to moonbeam

**Comment by Kailai-Wang** [comment]
Up and running: https://polkadot.js.org/apps/?rpc=wss://moonbase-parachain-sg-0.litentry.io#/explorer

**Comment by h4n0** [comment]
Bi-directional HRMP channel has been established, and LIT token has been registered on Moonbeam Alpha testnet.

**Comment by h4n0** [comment]
Bi-directional HRMP channel has been established, and LIT token has been registered on Moonbeam Alpha testnet.
