### ISSUE TITLE
Transfer total crowdloan reward amount into an official account

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#415]
### Context
The total crowdloan reward amount has been minted on Litmus (the eact tx see [here](https://litmus.subscan.io/extrinsic/117388-2)), and the same amount needs to be transferred and locked in an official account.

### Task
- [x] Transfer the same amount of LIT ERC20 token to a specific account
- [x] Tag this account as official locked account

**Comment by Kailai-Wang** [comment]
This is still valid.

To make it more generic, we need to lock as many tokens as those were issued/minted on Litmus + Litentry.
Maybe we could do this after litentry-parachain is onboarded and crowdloan reward is distributed.

Alternatively, we could do it in two steps: Litmus first and then Litentry.

**Comment by Kailai-Wang** [comment]
We should make sure we don't forget this, especially if we are going onto CEX 
cc @qiuhaiguo @geastwood

**Comment by qiuhaiguo** [comment]
Thanks Kai, I will discuss it with Fei later.

**Comment by qiuhaiguo** [comment]
We need to create a multi-sign wallet.

**Comment by Kailai-Wang** [comment]
I don't think this is done, please correct me if I'm wrong @qiuhaiguo

**Comment by qiuhaiguo** [comment]
Transferred 2.5M LIT to the token bridge contract([0x11bce4536296c81d1a291b1ffbe292fdd55a3a89](https://etherscan.io/token/0xb59490ab09a0f526cc7305822ac65f2ab12f9723?a=0x11bce4536296c81d1a291b1ffbe292fdd55a3a89))
