### ISSUE TITLE
Distribute crowdloan rewards for Bifrost contributors

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#419]
Distribute crowdloan rewards for Bifrost contributors.

Steps:
1. setBalance jcPn3TCtTzq5mnmoudFLCTuU4W43DHEKBY5xiKg3GVXxqXAfs (Bifrost crowdloan account) to 0.1 LIT (100000000000)
2. setBalance jcMeQeePbWkeSt3yqp2p7bA1gnReydg9mtHBUvL3dowy6xbZZ (crowdloan distribution account) to 25917.9661 (current balance of this account) + 61938.9857 (current bifrost crowdloan balance - 0.1) = 87856.9518 LIT
3. Distribute rewards to Bifrost contributors by running https://github.com/litentry/crowdloan-distributor/blob/litmus-bifrost/encoded_call.txt#L83

**Comment by geastwood** [comment]
Done.
