### ISSUE TITLE
Technical draft of identity linking workflow and ID-graph verification

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#427]
### Context
Following the [workshop](https://www.notion.so/litentry/Identity-Linking-Pallet-Workshop-410ebcb2a4834c21b32fbde39e60c934) and know-how that was collected so far, an architecture design of the linking and verification of identities should be proposed.

### Task
Ideally the design should contain the following aspects:
- part 1: how to generate the linked data - identity linking workflow (web2/web3)
- part 2: how to use and verify the linked data - data flow of request/attestation/VC..
- part 3: milestones and roadmap

### Acceptance criteria
The architecture design is drafted and aligned with parachain team and @hanwencheng @geastwood 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
doc:
https://www.notion.so/litentry/Technical-draft-of-Litentry-protocol-d46b8d2576ee44ad90e9b5b81ea6e0d3
still WIP

**Comment by h4n0** [comment]
Completed.
