### ISSUE TITLE
xcm fees too high?

### ISSUE THREAD

**Issue by gilescope** [litentry/litentry-parachain#452]
It's currently using identity fee for xcm:

type Trader = UsingComponents<IdentityFee<Balance>, ..>;

This is likely to mean the same fees as the relay chain. In all likelyhood parachains don't need as high fees.

https://github.com/paritytech/cumulus/issues/920 - we noticed this on statemint. Encointer have also recently tweaked their code to not use `IdentityFee<Balance>`. I suspect you might want to do the same.

**Comment by Kailai-Wang** [comment]
Thanks for letting us know @gilescope, we'll definitely look into it.
Tagging @wangminqi

**Comment by wangminqi** [comment]
Hi, our transactionPayment weightTofee implementation is IdentityFee too.
We will double check our further implementation.

Thanks for your suggestion!
