### ISSUE TITLE
Litentry Parachain rollout plan

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#461]
Finish the feature list for Litentry on Polkadot network.

**Comment by Kailai-Wang** [comment]
double-checked with Mel, they don't necessarily need the full rollout plan, but "what does the onboarding of litentry parachain mean to the community", or a list of functionalities that they could expect after litentry is onboarded.

I'm going to provide such a list this week.

**Comment by h4n0** [comment]
Thanks for clarifying it. Please close this ticket once this is done, and the roll out plan will be completed before Litentry parachain goes onboard.

**Comment by Kailai-Wang** [comment]
https://www.notion.so/litentry/list-of-planned-features-on-Litentry-7c66c053d4ea4e749ae31538d44142ef

In review.

**Comment by Kailai-Wang** [comment]
adjusted according to Hanwen's suggestions and handed over to Mel
