### ISSUE TITLE
Interface definitions (P1:M1)

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#466]
We need to define the following:

Extrinsics to identity linking and management pallet
ECALL/OCALL between enclave and teerex pallet
Events to be emitted

**Comment by Kailai-Wang** [comment]
Initial documentation:
https://www.notion.so/litentry/Identity-management-interface-proposal-P1-M1-846bb6bdb9214d93828c114d31e415cb

We'd need an internal discussion about it.

**Comment by Kailai-Wang** [comment]
This is deprecated / already covered by the implementation.
