### ISSUE TITLE
Draft a document outlining the data structure stored within TEE

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#468]
Please a document that outlines the data structure and types which will be stored within the TEE sidechain.

- Outline the initial data we will store in the TEE
- Include and document the data types
- Please document this as a comment on this ticket or alternatively provide a link to the related document

**Comment by h4n0** [comment]
https://www.notion.so/litentry/Proposal-Data-Structure-in-Enclave-0653ffa166cb481b9094c3cb1ce97a7c

**Comment by Kailai-Wang** [comment]
Can be closed
