### ISSUE TITLE
MCP to review parachain TEE data structure proposal

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#469]
We require the MCP team to review the proposed data structure within the TEE

- Review the proposal provided by the parachain team
- Provide feedback and highlight any additional data you wish to be stored within the TEE (including metadata)
- For visibility please provide feedback as a comment on this issue/ticket

**Comment by Kailai-Wang** [comment]
This is deprecated / already covered by the implementation.
