### ISSUE TITLE
Define the Web2 Verification JSON Message

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#470]
The shape of the JSON message when posting a post or message on a Web2.0 platform
(e.g. Twitter, Github, Discord).

- Needs to consider Twitter, Github, and Discord on the initial draft
- Document in Notion and link within comments
- Documentation should include valid properties, and example JSON messages for each platform

**Comment by Kailai-Wang** [comment]
https://www.notion.so/litentry/Web2-Web3-JSON-signed-messages-b9a4b543537f4699afb64054887ac15d
