### ISSUE TITLE
Define the interface and extrinsics for identity pallet for F/E

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#475]
We need to define how the F/E will interface with our identity pallet. (e.g. link, unlink)

- Please could the proposal be drafted and attached to this ticket as a comment/link.

**Comment by Kailai-Wang** [comment]
please check the doc in the [parent epic](https://github.com/litentry/litentry-parachain/issues/466)

**Comment by Kailai-Wang** [comment]
This is deprecated / already covered by the implementation.
