### ISSUE TITLE
Define events which will be emitted from our identity pallet (parachain)

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#478]
Please define which events will be emitted from our **identity pallet** within our parachain.

- Document each event, describe what it emits and when it is triggered e.g. status of linking
- Please provide a link to the document within a comment on this ticket

**Comment by Kailai-Wang** [comment]
please check the doc in the [parent epic](https://github.com/litentry/litentry-parachain/issues/466)
