### ISSUE TITLE
Integration tests for TEE

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#482]
- Create an integration test to test HTTPS request/response works correctly within TEE

**Comment by suinuj** [comment]
https://github.com/litentry/litentry-parachain/pull/600 and https://github.com/litentry/worker/pull/78
used to test.

**Comment by suinuj** [comment]
not found the compatible for integration testing now. @Kailai-Wang pls help to test it after compatible version between worker and parachain could be found easily.
