### ISSUE TITLE
Investigate how we need to generate shielding key pairs in TEE

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#483]
We need a public/private key pair to handle encryption and decryption of data so that the TEE only understands submissions.

- Needs investigation
- Needs documentation and explanation
- Please include a link within the comments to the related Notion document

**Comment by StamfordDigital** [comment]
Still investigating. Jun requires further time on this.

**Comment by suinuj** [comment]
https://www.notion.so/litentry/Keys-in-TEE-73d2aba8a0344ce1a7086b866f4f8451
