### ISSUE TITLE
Test HTTPS request/response within the TEE enclave

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#484]
Write a test to check HTTPS requests/responses work correctly. We want to ensure we can communicate with the outside if required.

- Add code to TEE enclave which calls https://litentry.com
- Check for response code 200

**Comment by suinuj** [comment]
The debug process could be tracked via the issue https://github.com/litentry/worker/issues/74.

**Comment by suinuj** [comment]
close it since https works in TEE and verified in https-test-2 branch via hard-coded request/response check.
