### ISSUE TITLE
Test read/write of persisted data within the TEE enclave

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#485]
We need to test that data will be persisted within the TEE enclave.
e.g. We are checking to ensure that linked identities do not get lost.

- Add code into the TEE enclave directly which adds data into the TEE side-chain
- Stop the TEE implemention
- Restart TEE and check the data still exists

**Comment by StamfordDigital** [comment]
@suinuj to discuss this with Integritee

**Comment by suinuj** [comment]
1. investigate if we can open file directly in TEE, not found such operation. But we can put the encrypted file in the host and decrypt it in TEE, to guarantee data not exposed. We have the support from Intel SDK https://www.intel.com/content/www/us/en/developer/articles/technical/overview-of-intel-protected-file-system-library-using-software-guard-extensions.html and rust wrapper in Integritee https://github.com/integritee-network/worker/blob/master/core-primitives/sgx/io/src/lib.rs. 
2. we can follow the file used in Worker like sidechain db, to store off chain data directly into file in host.
3. data still exists after worker restart, I tried the created accounts.

**Comment by suinuj** [comment]
close with experiment and conclusion on how to open/read/write the encrypted files.
