### ISSUE TITLE
Token bridge integration test

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#490]
Implement a test to simulate relayers interacting with the token bridge pallet.

The following steps could apply:
1. Use sudo (Alice) to set relayer to Bob
2. Use Bob to simulate relayer extrinsic sending and verify the result of token migration tests

**Comment by Kailai-Wang** [comment]
Is this ticket still valid?

**Comment by StamfordDigital** [comment]
This can be closed.
