### ISSUE TITLE
Identity Pallet (P1:M2)

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#498]
We require an Identity pallet for our parachain.

- The pallet will be developed in Rust
- Extrinsic implementation examples include **linking**, **unlinking** and **verfifcation** of Web2.0 platforms (TBC) and Web3 addresses (TBC)
- Please note that there is also a requirement for extrinsic implementations which allow a user to be able to **manage** their identities.
- The pallet needs to be able to interface and communicate with the **teerex** pallet also within our parachain implementation

**Comment by Kailai-Wang** [comment]
This is deprecated / already covered by the implementation.
