### ISSUE TITLE
TEE pallet (P1:M2)

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#499]
We require a new pallet within the TEE implementation

- This pallet must be able to communicate with the **teerex** pallet within our parachain

This pallet must have the following functionality:

- Block synchronization from teerex and decryption
- Challenge code generation
- Verification logic
- Storage of the **id-graph**

**Comment by Kailai-Wang** [comment]
This is deprecated / already covered by the implementation.
