### ISSUE TITLE
Investigation to see if f/e can interface directly with teerex pallet within parachain

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#530]
We need to investigate and confirm the direction on if the f/e interfaces directly with the teerex pallet or with a layer between (identity pallet)

We believe it is technically possible for the f/e to interface directly with the teerex pallet. However, we have a design decision to make:

- Should we directly interface with the teerex pallet?
- Add report/thoughts in comment
- What will this mean for the f/e
- Meeting or async decision on how to proceed with team members

**Comment by suinuj** [comment]
Should we directly interface with the teerex pallet?
No, will implement a pallet in parachain.

Add report/thoughts in comment:
Solution A: directly interface with teerex (0.5 vote)
Solution B: add new identity linker pallet in parachain (2.5 vote)

Advantage of A:
1. no pallet in parachain, less code, easier to maintain

Advantages of B:
1. front will be clear to see what's extrinsic
2. can support plaintext accounts very well
3. avoid teerex as single point for all transactions
4. except our UI, other developers can wrap tx by themself.
5. if change the solution in the future.
   easy: from B to A, just remove the pallet in parachain
   hard: from A to B, lots of efforts in design and implementing pallet in parachain

What will this mean for the f/e
much easier to understand the transaction

Meeting or async decision on how to proceed with team members
can schedule another meeting to sync up with the team if necessary.

**Comment by StamfordDigital** [comment]
Great that you reached a decision quickly on this. Closing the ticket.
