### ISSUE TITLE
XCM documentation for front-end

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#532]
Prepare the document for front-end team in order to perform the cross chain transfer of LIT with Moonriver.

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Parachain-XCM-front_end-document-473e99ca460a44f3bfa30982ce762308

**Comment by StamfordDigital** [comment]
@StamfordDigital to schedule a meeting with f/e team and @wangminqi
