### ISSUE TITLE
Calculate crowdloan reward distribution

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#537]
We need to calculate the reward distribution ahead of our Litentry Polkadot parachain being onboarded.

The reward distribution needs to be calculated by two people. To help avoid errors, each person should calculate the reward independently and then compare each other's work/results.

The reward calculation needs to take into consideration people who have previously contributed via the channel **Parallel**.

**Calculation tasks**

- A script is required to build the distribution list and calculate the reward associated with each address
- The script needs to keep in mind that it should be applying the tiered rewards system and the reward amount is time-sensitive (based on when the block was created)
- We need to reward **12 LIT per contributed DOT** to any addresses who contributed via **Parallel** for **Batch 2** _AND_ contributed via **Parallel** for **Batch 3**

@qiuhaiguo is able to provide you with a list of these contributors.

- We need to reward **12 LIT per contributed DOT** to any addresses who contributed via **Parallel** for **Batch 2** _AND_ contributed directly via **PolkadotJS** for **Batch 3**

For this particular instance, we will need to ask the community to come forward and submit a claim for the reward. [Please see this ticket for further information.](https://app.zenhub.com/workspaces/parachain-61027060a728e4000efc3d8b/issues/litentry/litentry-parachain/545)

**Referrer Bonus**
Parallel contributors are entitled to the 5% referral bonus.

**Comment by h4n0** [comment]
This is a summary after the discussion with @qiuhaiguo 

- We agree to reward **12 LIT per each contributed DOT** to the lucky guy who contributed across tier 1 and tier 2 (across the line of 500k DOT)
- I'll calculate the rewards with the contribution list provided by Web3Go, and @StamfordDigital will use the data source from litentry-graph, to avoid errors from data sources

There is a TODO list for crowdloan rewards contribution:

- [ ] For those who contributed via Bifrost and Parallel, we need to identify the MultiSig wallet and distribute it to the corresponding user wallets according to the contribution lists provided by Bifrost and Parallel.
- [ ] We need to clarify the way to distribute rewards with Equilibrium
- [ ] For those who contributed via Kucoin and Kranken, we may need to record how many DOTs in tier 1 contributed, and how many in tier 2 contributed.
- [ ] We need to clarify the referral bonus for Kucoin, Kranken, Bifrost, Parallel, and Equilibrium contributors.
- [ ] When is the end of the referral registration? We should stop it before our distribution! (lessons learned from Kusama crowdloan)

**Comment by h4n0** [comment]
This is a notion page of the points above for internal discussions
https://www.notion.so/litentry/Polkadot-Parachain-Crowdloan-Distribution-550d3fbde38242d09079f4a21e24ad96

**Comment by StamfordDigital** [comment]
Crowdloan has been distributed. Closing this ticket.
