### ISSUE TITLE
Crowdloan claim reward form

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#545]
We need to reward a fixed, single amount of **12 LIT** to any addresses who contributed via **Parallel** for **Batch 2** AND contributed directly via **PolkadotJS** for **Batch 3**.

In order to reward these addresses, we need to reach out to our community and ask them to submit a claim.

We need to data capture the following information:

- **Address**
- **TX ID** for the user's DOT to Parallel transaction (Batch 2)
- **TX ID** for the user's DOT contribution transaction via PolkadotJS (Batch 3)

This data should then be factored into our reward calculation.

The form could be created with Google Forms or we could quickly create a UI within our Polkadot Crowdloan app.

**Comment by Kailai-Wang** [comment]
Looks like it's announced:
https://twitter.com/litentry/status/1522133468100001799
