### ISSUE TITLE
Token bridge upgrade and test on Litmus

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#547]
We will upgrade token bridge implementation on Litmus, and do basic testings.

- [x] Upgrade token bridge and related filter on Litmus
- [x] Align command params of relayer 
- [x] Connect Litmus bridge with UI 
- [x] Test transfer functions manually
- [x] Transfer Ethereum contract ownership to the multisig wallet
- [x] Make sure we can get notification if relayer down
- [x] Update the gitbook to populate the token bridge tutorial

**Comment by Kailai-Wang** [comment]
We also need to update the gitbook (not sure if we already have an issue for it)

**Comment by suinuj** [comment]
https://etherscan.io/tx/0x7b1c8dd5df095b8c41225a58638395b05d2a450f8356f3aa44c54056191f1510
The ownership of token bridge is now under Multisig contract 0x172d9C88B5a15217D45a1bbC3Ec489Ca2F589Ff0

**Comment by suinuj** [comment]
all sub-tasks are done, just waiting for the announcement.

**Comment by Kailai-Wang** [comment]
I believe it was announced on Friday already: https://twitter.com/litentry/status/1527712921865793536

Close the ticket now.
