### ISSUE TITLE
Consider using polkadot telemetry

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#548]
### Context
Currently, we are using our own telemetry backend: telemetry-backend.parachain.litentry.io. It's not working (somehow) and I actually don't see a point in using it so far.

### Task
change code and chain spec to use telemetry.polkadot.io
we could start with rococo/moonbase first and if it works - extend it to litmus/litentry parachain.

### Acceptance criteria
- chain spec is adjusted
- telemetry.polkadot.io shows litentry parachain

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
The test with `litentry-moonbase parachain` looks good:
https://telemetry.polkadot.io/#list/0x4decfd421755d9008781d00ce40ea4cf47ec24a3717a34ca995126fc4a78c4f8

<img width="1365" alt="image" src="https://user-images.githubusercontent.com/7630809/169012344-8533930e-a756-4128-a3b4-ab3a362d349f.png">

**Comment by geastwood** [comment]
We probably can recycle the server which run our own telemetry

**Comment by Kailai-Wang** [comment]
> We probably can recycle the server which run our own telemetry

Exactly - or to reuse it as another development server for TEE, see https://github.com/litentry/worker/issues/63

**Comment by geastwood** [comment]
Perfect, do we know where this is hosted? On Hetzner?

**Comment by Kailai-Wang** [comment]
> Perfect, do we know where this is hosted? On Hetzner?

yea on hetzner
