### ISSUE TITLE
on_initialize and on_finalize called twice in collator node

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#55]
In the collator node, the on_initialize and on_finalize will be called twice. it may impact the pallet like off-chain worker dependent on the hooker functions. Need find a method to disable them in collator runtime.

**Comment by geastwood** [comment]
What is the game plan? Can we already confirm this is gonna be a problem?

**Comment by suinuj** [comment]
definitely, it is a problem, but not impact the final result of the off-chain workers for now. we need investigate how to fix it and make all those hook functions just called once.

**Comment by Satoshi-Kusumoto** [comment]
Is this a problem from upstream (then where is it introduced) or our collator (then why)

**Comment by Kailai-Wang** [comment]
Is it still a problem? Can we close this issue now? @suinuj

**Comment by suinuj** [comment]
After parachain upgrades to v0.9.16, we can't see the issue anymore.
