### ISSUE TITLE
Investigation - We need clarification on how we distribute rewards for some channels.

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#560]
We need to clarify how we distribute rewards for:

- [x] Equilibrium
- [ ] Kucoin
- [ ] Kraken

**Comment by qiuhaiguo** [comment]
Equilibrium will give us a contribution list tomorrow(12.05.2022).

**Comment by qiuhaiguo** [comment]
The contribution list from Equilibrium: https://docs.google.com/spreadsheets/d/1ypMNCE4w3rwT9S3g-DQ1pBxvE8wQJzHNQKEMtyHvatw/edit#gid=398406998

**Comment by qiuhaiguo** [comment]
For Kucoin and Kraken, we just distribute the rewards directly to their proxy address. And figure out how much DOTs have 12 LIT and the timeline of Tier 1.
