### ISSUE TITLE
Investigation - We need to clarify the channel referral bonus 

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#561]
We need to clarify how we distribute the referral bonus for Kucoin, Kraken, Bifrost, Parallel, and Equilibrium contributors.

- [ ] Kucoin
- [ ] Kraken
- [ ] Parallel
- [ ] Equilibrium

**Comment by qiuhaiguo** [comment]
Move comment to the notion. https://www.notion.so/litentry/Polkadot-Parachain-Crowdloan-Distribution-550d3fbde38242d09079f4a21e24ad96
