### ISSUE TITLE
Investigate and Run M6 Test on TEE Server

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#564]
- [ ] Investigate the M6
- [ ] Run the M6 test on TEE Server
- [ ] Screenshot and document a comment on this ticket

**Comment by BillyWooo** [comment]
https://github.com/litentry/worker/tree/litentry/scripts

**Comment by BillyWooo** [comment]
https://www.notion.so/litentry/TEE-integrate-test-M6-M8-eecf15b1b25f41cca3449e5f7a477fce
