### ISSUE TITLE
Investigate and Run M8 Test on TEE Server

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#565]
- [x] Investigate the M8
- [x] Run the M8 test on TEE Server
- [x] Screenshot and document a comment on this ticket

**Comment by BillyWooo** [comment]
https://github.com/litentry/worker/tree/litentry/scripts

**Comment by BillyWooo** [comment]
https://www.notion.so/litentry/TEE-integrate-test-M6-M8-eecf15b1b25f41cca3449e5f7a477fce
