### ISSUE TITLE
Investigation - public key encryption with SR25519

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#584]
### Context
In the protocol design we would need to pass back information that's only decryptable by the user (e.g. challenge code, VC). We thought parachain public key (SR25519) would suffice but it seems to be not so easy.

polkadot-js doesn't provide a matching API either - you can only sign and verify message.

### Task
Look into details if public key encryption works with sr25519:
- if yes, how?
- if no, any other alternatives? As fallback, we can always use a plain RSA key pair, but that would need to be generated and stored either by user or MCP extension.

### Acceptance criteria
A conclusion is made about the possibility and guide if applicable.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by suinuj** [comment]
1. The ed25519 is not secure for used in data encryption and the sr25519 is based on the ed25519. it is not good idea to use it this way.
2. Check the interface and code implementation in the sr25519, we need wrap some math method to encrypt data. It is not easy and may introduce serious bug.
3. not sure the procedure about RSA encryption, but is not efficient. 
4. I suggest we use a random value from user work as symetric key to encrypt and decrypt data.

**Comment by suinuj** [comment]
https://www.notion.so/litentry/SR25519-encryption-cfec89b4bde2475dacf9ca4f29f1ccb1 for further discussion. Comments are welcome

**Comment by Kailai-Wang** [comment]
Thanks. We'll use RSA asymmetric encryption for now. If we observe any drawbacks (performance, encryptable text length etc) we'll switch to symmetric encryption like AES (but we'd need to use RSA encryption to exchange the symmetric key anyway).
