### ISSUE TITLE
Refactor source code in ts-tests

### ISSUE THREAD

**Issue by chenzongxiong** [litentry/litentry-parachain#59]
The source code in `ts-test` is messy.  We need to refactor it for easier maintenance.

1. putting testing code in a standalone source file
2. reading all sensitive information from environment variables for encrypted files instead of putting them in source code
3. removing useless comment lines.
4. resolving configuration error, e.g. changing parachain id from 1984 to 2022

**Comment by chenzongxiong** [comment]
I will run this script in our staging chain to check the performance of our parachain.  This is a critical step before we onboard  our parachain to kusama network

**Comment by geastwood** [comment]
@h4n0 would you be able to squeeze some time out to take a look at this?

**Comment by h4n0** [comment]
Let me try to work on this later this week.
