### ISSUE TITLE
Investigation of fleet to accelerate rust compilation

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#597]
### Context
https://github.com/dimensionhq/fleet is said to be up to 5x faster than `cargo`.
For production we may still want to use `cargo` as it's more standard, but it would be great if `fleet` can save some time in our daily CI.

### Task
Investigate, try out fleet and compare it with `cargo`.

### Acceptance criteria
The steps and results are documented.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/Parachain-Fleet-VS-Cargo-build-8e0f685f4fa84b59852e32ff16829866

**Comment by wangminqi** [comment]
Fleet requires at least 28 GB temp storage for building. And the functionality of clearing after the building is not implemented. The overall efficiency will increase 20% (8min compiling compared to 10 minutes cargo build), but the cost is not worthy. At least for now we should not include it in CI.

Issue close.
