### ISSUE TITLE
Create Failure Compensation list

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#599]
We need to create a Failure Compensation list for addresses who contributed during Batch 1 or 2 of the Polkadot parachain crowdloan.

- [x] Create list
- [x] Adapt script for Litmus/distribution for sudo
- [x] Run distribution list

**Comment by StamfordDigital** [comment]
@h4n0 further details here: https://www.notion.so/litentry/Failure-Compensation-Batch-1-and-2-37a29ca470a14c3fa289ce88b30adafd

**Comment by Kailai-Wang** [comment]
Failure compensation distribution is done
