### ISSUE TITLE
[Genesis] Fix tokenDecimals & tokenSymbol in system.properties 

### ISSUE THREAD

**Issue by chenzongxiong** [litentry/litentry-parachain#60]
There is no **token-related** information displayed on **subscan** since the response of the ` system. properties` is empty. We need to define the following metadata.

https://litentry.subscan.io/

![image](https://user-images.githubusercontent.com/8354165/125749394-9baf88cf-c726-44cc-b83a-edfc591acf92.png)

**Comment by chenzongxiong** [comment]
@hanwencheng @geastwood @qiuhaiguo @juniuszhou 
1. token decimal: 12
2. token symbol: LIT

**Comment by Kailai-Wang** [comment]
I think a bit more research needs to be done here, it seems different parachains have their own settings.
Beside that, ss58Format needs to be considered as well, so a typical property looks like this (take KILT as example):
```
pub fn get_properties(symbol: &str, decimals: u32, ss58format: u32) -> Properties {
	let mut properties = Properties::new();
	properties.insert("tokenSymbol".into(), symbol.into());
	properties.insert("tokenDecimals".into(), decimals.into());
	properties.insert("ss58Format".into(), ss58format.into());

	properties
}
```

And they are using different values:
KILT : "KILT", 15, 38
Shiden: "PLM", 18, 5 (dev)
Khala: "PHA", 12, 30
....

I understand they might newly create parachain-specific tokens, but it's worth double-checking it
@chenzongxiong @Satoshi-Kusumoto @h4n0

**Comment by Kailai-Wang** [comment]
Conlusion: use "LIT", 12, 31
