### ISSUE TITLE
Revamp the tags in this repo

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#612]
### Context
The current tags for issues in this repo sometimes get confused and/or don't fit so well with the intention of the issues, we may want to reconsider the classification of the tags.

Aside from that, we have multiple parachains now: **litentry/litmus/rococo**, it might be beneficial to have tags for each chain so that we know which chain is regarded for a certain issue, and perhaps `common` or `all` tag when it should be applied to all chains.

We should encourage the use of the tags for issues too.

### Task
- check the issues that we created and think about the possible categories
- devise a series of tags
- apply the settings for this repo

We may refer to e.g. polkadot's repo for their tagging system (doesn't have to be identical though) and/or other projects' tags if that helps.

### Acceptance criteria
Tags are revamped and introduced to the team.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
The explanation of this current tagging system: https://www.notion.so/litentry/Github-labels-for-parachain-7d377ccbabe849bcab4b67711b71dbe8

**Comment by Kailai-Wang** [comment]
Hi @StamfordDigital , you have a document somewhere about this if I recall correctly, could you please post the link again? Thanks!

**Comment by StamfordDigital** [comment]
Litentry-Parachain Repo Labels: https://www.notion.so/litentry/Litentry-Parachain-Repo-Labels-3f7ee3fa259c4429bd22587b7d20d0c4
