### ISSUE TITLE
Investigation of identity verification for discord

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#613]
We learned from MCP colleagues that identity linking verification for discord and discourse is required. We need look for ways to do that from parachain's perspective.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I added [another chapter](https://www.notion.so/litentry/Part-1-identity-management-pallet-on-parachain-IMP-e3fad9d10c9547919ebac10799d0b26d#ea2847df5b634737b74ce7383d6e71b5) in IMP section.

**Comment by jingleizhang** [comment]
I have ported JDK11 to TEE, rebuilt LITBot, and made it run inside TEE. 

- The detailed doc is here: https://www.notion.so/litentry/Discord-Bot-Verification-1a4a63e001834bf6ace2e00117d579c4 . 
- The original issue for LitBot in ID-Hub [https://github.com/litentry/my-crypto-profile/issues/531](https://github.com/litentry/my-crypto-profile/issues/531)
- The original discussion on Notion: [https://www.notion.so/litentry/Drop3Bot-MCP-LitBot-603f960d6bb144458f36b65600ea1f1a](https://www.notion.so/603f960d6bb144458f36b65600ea1f1a)

**Comment by jingleizhang** [comment]
created a new issue https://github.com/litentry/litentry-parachain/issues/810 for discourse verification.

I will mark this issue as `done` for discord verification.

**Comment by jingleizhang** [comment]
The investigation is completed.
