### ISSUE TITLE
Integrate NFT pallet into parachain

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#63]
Deadline: Aug. 4

**Acceptance Criteria**
- [x] NFT pallet can be built with parachain 
- [x] (WONT DO) Integration test should be added for NFT testing (This can be done later for not blocking frontend devs)
- [x] Deployment

**Comment by chenzongxiong** [comment]
@Satoshi-Kusumoto Is the first task finished? If so, please let me know.
