### ISSUE TITLE
Resolve the vague alerts from the litmus 

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#650]
### Context
We changed IPs of Litmus nodes, and the grafana dashboard was adjusted accordingly, but somehow we still got no data from the litmus metrics and the alerts have still been spammed.

### Task
Find out the reason and fix the alert system on grafana for Litmus.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by niteshb3495** [comment]
The false alerts were because of the misconfiguration after the IP change. I have changed the configurations to match the requirement.
