### ISSUE TITLE
DB backup for litentry-parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#651]
### Context
Similar to litmus, we'll need to deploy and enable the db backup script on to Litentry-parachain nodes.

### Task
deploy the db backup script on Litentry-parachain nodes.
We may need to launch the subscan instance first if we decide to deploy the script there

### Acceptance criteria
script deployed and works

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
This ticket is still valid.
@niteshb3495 can you take it?

**Comment by jingleizhang** [comment]
Could we close this issue? @niteshb3495

**Comment by Kailai-Wang** [comment]
ping again :) @niteshb3495

**Comment by niteshb3495** [comment]
I forgot to close the issue. This was completed on the 15th of December 2022. 
Please find the notion for more details.
