### ISSUE TITLE
Test/trialrun of motions/proposals on rococo, along with governance-apps

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#668]

**Comment by Kailai-Wang** [comment]
rococo updated with governance enabled.

**Comment by Kailai-Wang** [comment]
A short summary of what we tested and action points:
https://www.notion.so/litentry/Governance-1-0-Test-a2486311005c4074b5b9d0b588800ae7

**Comment by StamfordDigital** [comment]
Governance is now live on Rococo. Closing ticket.
