### ISSUE TITLE
Shutdown amixr and update alert callbacks

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#682]
### Context
Amixr has stopped working since June 30.

### Task
- [x] shutdown/unregister amixr so that our information is removed
- [x] update the callback endpoints in grafana so that the alerts go directly in #alert channel 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by StamfordDigital** [comment]
@chenzongxiong needs to research alternative solution to Amixr.
Do we need to support onCall feature @Kailai-Wang?

**Comment by Kailai-Wang** [comment]
> @chenzongxiong needs to research alternative solution to Amixr. Do we need to support onCall feature @Kailai-Wang?

I don't think so 😂 
We (at least I) have never had a chance to use this feature.

Normally slack notification should do its job. If we really want real-life notifications an SMS would be more than enough..

**Comment by chenzongxiong** [comment]
I deactivated all users in the amixr, we have no permission to edit amixr console anymore.
contact point **Grafana-Slack-Alerts** will forward altering message to `#alert` channel in slack

**Comment by Kailai-Wang** [comment]
Cool, please feel free to close this ticket if you think it's done.

**Comment by niteshb3495** [comment]
Sorry, I didn't get chance to look after this ticket. 
@chenzongxiong - thank you for looking into this. 

As you mentioned, yes, Grafana-Slack-Alerts will send notifications to the #alert channel. 
I will be making some changes in the alert rule to get the proper notifications. (Currently we are not receiving exact instance ID/Name in the alert).
