### ISSUE TITLE
Test of XCM with karura

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#712]
### Context
In 2 -3 days the channel opening request from Karura should be approved. After that, we should test the transfer of LITs to Karura via XCM (xtokens::transfer)

### Task
- [ ] test of LIT transfer from Litmus to Karura
- [ ] test of LIT transfer from Karura to Litmus, if applicable (is it?)
- [x] #726 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
@wangminqi please provide the extrinsic details to @jonalvarezz

**Comment by jonalvarezz** [comment]
Extrinsic details can be found at https://www.notion.so/litentry/Parachain-XCM-front_end-document-473e99ca460a44f3bfa30982ce762308

Frontend ticket: https://github.com/litentry/project-litmus-webapp/issues/78

**Comment by montogeek** [comment]
Frontend is done, but the network is disabled in the UI, please let me know when you want to test it :)

**Comment by wangminqi** [comment]
Acala USD hacked. Waiting for their update.
