### ISSUE TITLE
Add identity support on Runtime

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#73]
** Acceptance Criteria ** 
- [x] Add identity into runtime

**Comment by bdmason** [comment]
We need to ensure registrars exist (like we do in `setup.ts` in the registrar JS app).

I was going to add that we need the dev accounts with test tokens but that looks to be in place already here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain.staging.litentry.io#/accounts.

**Comment by h4n0** [comment]
> We need to ensure registrars exist (like we do in `setup.ts` in the registrar JS app).
> 
> I was going to add that we need the dev accounts with test tokens but that looks to be in place already here: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fparachain.staging.litentry.io#/accounts.

Registrar is part of pallet identity, so this will be done once identity is integrated.
