### ISSUE TITLE
Extra archive node for litentry-parachain

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#737]
### Context
To enable DB backup and have an extra copy of parachain-DB from archive node, I'm thinking to launch another instance as archive node.
@chenzongxiong do you think it's necessary? If so:

### Task
- [ ] launch a new instance from hetzner
- [ ] domain and network setup
- [ ] ansible setup

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by chenzongxiong** [comment]
will check later.

**Comment by jingleizhang** [comment]
FYI @niteshb3495,  do you think the ansible setup is needed or completed?

**Comment by niteshb3495** [comment]
Completed! More details on Notion.

**Comment by Kailai-Wang** [comment]
Can you post notion link again please? @niteshb3495
