### ISSUE TITLE
Weight indicator improvement

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#746]
We see the implementation of weight hint where extrinsic directly digest weight hint for weight counting.
Is weight function capable of directly taking on-chain states as input?

**Comment by Kailai-Wang** [comment]
It's related to staking pallet

**Comment by Kailai-Wang** [comment]
I assume this can be closed? @Jinsipang 
As mentioned let's link PR with issues next time :)

**Comment by Marky-Shi** [comment]
Of course, the relevant code has been merged

> I assume this can be closed? @Jinsipang As mentioned let's link PR with issues next time :)
