### ISSUE TITLE
The extrinsic order checker seems to be broken

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#747]
### Context
see https://github.com/litentry/litentry-parachain/issues/745

It seems the script somehow used a very old runtime for metadata comparison:
```
spec_version: 9083 -> 9020
spec_version: 9090 -> 9000
```

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by chenzongxiong** [comment]
@Kailai-Wang 
I checked the runtime version of litmus on the polkadot-js/app, it's **9083**

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.litmus-parachain.litentry.io#/rpc

![image](https://user-images.githubusercontent.com/8354165/184090477-c1f26816-2d90-4b1c-813e-f58e0e88c1f5.png)

Results from Subscan https://litmus.subscan.io/block/762658
![image](https://user-images.githubusercontent.com/8354165/184092484-aec8da70-e7e2-4963-9b12-efe9597c2752.png)



>>>>>>>>> It's litentry results from polakdot-js/app, it's **9090**

![image](https://user-images.githubusercontent.com/8354165/184090683-1d5faf7f-6051-4700-b34d-4c4084a93df8.png)

rococo's version is also correct.

**Comment by Kailai-Wang** [comment]
Are you interested in this topic? @Jinsipang

**Comment by Jinsipang** [comment]
> Are you interested in this topic? @Jinsipang

No problem, by then the spec_version:9120 running in the actual env now seems to have been running for a while, according to the link sent by zongxiong before, it is also 9120 after comparison.

When doing the simulation runtime upgrade, the verification method is to obtain the runtime-version  by calling RPC and then compare it, I'm not sure if I can reproduce this problem locally.

**Comment by Marky-Shi** [comment]
It's really interesting and I'm happy to do it.   
`[Spec] name: litmus-parachain
spec_version: 9120 -> 9020
transaction_version: 1
`
https://github.com/litentry/litentry-parachain/issues/1062#issuecomment-1338125372

block(1487150) : 0x0994cd9e89612c3f5f951158dc2a8e4d840baafbbb056f3b3cd7cc8ac35d6e88

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/87012234/208345457-b49ec06b-1f56-43e1-9d2a-d321b888592b.png">


I used RPC to get the runtime version of block 1487150 on Litmus and got 9115, while the runtime version compared by our release bot is 9020, so I guess if there is a problem with the locally started chain during the comparison, resulting in incorrect spec_version.

**Comment by Jinsipang** [comment]
It's really interesting and I'm happy to do it.   
`[Spec] name: litmus-parachain
spec_version: 9120 -> 9020
transaction_version: 1
`
https://github.com/litentry/litentry-parachain/issues/1062#issuecomment-1338125372

block(1487150) : 0x0994cd9e89612c3f5f951158dc2a8e4d840baafbbb056f3b3cd7cc8ac35d6e88

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/87012234/208345457-b49ec06b-1f56-43e1-9d2a-d321b888592b.png">


I used RPC to get the runtime version of block 1487150 on Litmus and got 9115, while the runtime version compared by our release bot is 9020, so I guess if there is a problem with the locally started chain during the comparison, resulting in incorrect spec_version.

**Comment by Marky-Shi** [comment]
It may have something to do with [these lines](https://github.com/litentry/litentry-parachain/blob/dev/.github/workflows/create-release-draft.yml#L221), and then I will verify this guess.
