### ISSUE TITLE
pallet_bounty research

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#754]
A pallet document which brief the techinical structure of bounty function

**Comment by Kailai-Wang** [comment]
Can we please add a bit of context here? What exactly needs to be researched? What are the acceptance criteria (or to what extent is the research considered "done")? 👀

**Comment by wangminqi** [comment]
@Jinsipang please add your document link here and close the issue.

**Comment by Marky-Shi** [comment]
The document link:https://www.notion.so/litentry/substrate_bounties_pallet-dcc597d8a552476f8382f3533f19fdc4
