### ISSUE TITLE
Create mock extrinsic/functions within the Parachain IMP

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#765]
Please create some mock extrinsic/functions within the Parachain IMP to enable the front-end to start integration and testing.

Please create a mock extrinsic for the following:

- [x] Link a Credential (Identity)
- [x] Unlink a Credential (Identity)
- [x] Verify a Credential (Identity)

**Each** extrinsic should omit an event that can be listened to by the front-end.

**Comment by Kailai-Wang** [comment]
We could write a separate pallet for that, e.g. `identity_management_mock` which has exactly the same interfaces (extrinsics) as the real IMP.

Please note this pallet doesn't connect with TEE at all.

To further simplify it, we could store the state in parachain storage (e.g. ID-graph, public keys, challenge codes ...)
