### ISSUE TITLE
Create mock extrinsic/functions in TEE level

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#768]
Similar to #765 , to achieve better decoupling and modularized testing, we'd like to try out different mocking levels:
- in #765, the frontend will directly extrinsics within the mock pallet
- in this issue, the frontend will call the real extrinsics, which will be forwarded to TEE. However, we are mocking the TEE handling, which means inside TEE, we omit the business logic of handling those extrinsics (e.g. data fetching from data provider) and directly return the fake result instead (e.g. a hardcoded challenge code, a hardcoded sample VC) and post the result back to the parachain. 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I'm concerned if we have enough capacity to do this, maybe not

**Comment by Kailai-Wang** [comment]
Maybe this is too much with the current engineering power, consider closing it

**Comment by jingleizhang** [comment]
Since we will switch from mock pallet to real pallet on staging env, I think we can close this issue.

**Comment by Kailai-Wang** [comment]
Yes let's close it
