### ISSUE TITLE
Notion documentation of the bi-directional token bridge

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#769]
### Context
This is the internal documentation.
We should complete the information about the token bridge deployment including:
- various smart contract addresses
- token bridge binary compilation and deployment
- parameter configurations (e.g. threshold, resourceId, fee...)
- any link to F/E guidance

Notion links:
https://www.notion.so/litentry/Token-bridge-ETH-Litmus-dc2b307b3aa4441996520833bcfb44c6
https://www.notion.so/litentry/Token-bridge-Litmus-ETH-815382739a3640f68e9dd159c9b52968

Alternatively we could merge them into one page

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
Done.
