### ISSUE TITLE
Use gasprice in relayer config to send contract calls

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#776]
### Context
We observed a problem in bi-directional token bridge that the gas price seems to be dynamically calculated, which might result in a big difference regarding the time when the calls from different relayers are included in the blocks.

https://etherscan.io/address/0x97cb2a379bb6d66825a3df6a665b1ffe2392ed35

Given that the expiry period is set to 100 blocks (= ~ 20min), it's quite possible that the proposal will get cancelled due to time out => the transfer will fail.

To mitigate the risk, we'd like to modify the chainbridge's code to make sure we always use the same gas price estimation for all relayers (e.g. always use the config value). 

This would ensure that the `VoteProposal` calls will be included at a similar timepoint.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by ziming-zung** [comment]
solve at: https://github.com/litentry/ChainBridge/commit/33fd2d175fed6f9564a3212b4e9e79e53142f49a, please check.

**Comment by Kailai-Wang** [comment]
Looks good, thank you. We still need to test it against rococo though

**Comment by Kailai-Wang** [comment]
Tested OK on the ETH main net, e.g. here: https://etherscan.io/tx/0x0e225185d783a6f874df926e6de15c39c7204ddbdefb8d8b2d0bca9bc967c199

Close it.
