### ISSUE TITLE
Make public the bi-directional token bridge on Litmus

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#777]
### Context
A first-step test in the production env showed it basically worked, meanwhile, we were able to identify a few problems.

Here is a list of TODOs before we make public the bridge -- just to not forget:
- [x] #776 => re-compile and deploy the binary
- [x] Set fee for production
- [x] Set MaxIssuance for production
- [x] Fund bridge with the same amount of balance as current issuance on Litmus
- [x] Runtime upgrade and make public

Small TODOs for frontend:
- [x] show the current commission in LIT
- [x] optionally show the amount of LIT to be expected on the receiving end, pop up an error if (transfer amount < commission) 
- [x] show a text hint that "the receiving time of the LIT balance on ETH depends on the Ethereum network status"
- [x] show a very rough estimation by comparing the gasFee in config and realtime gas status on ETH

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by qiuhaiguo** [comment]
After talking with @hanwencheng, we suggest that MaxIssuance for Litmus parachain is 5M, and MaxIssuance for Litentry parachain is 35M. 
CC @Kailai-Wang

**Comment by qiuhaiguo** [comment]
For each cross chain transfer(Litmus=>ERC 20), we need two `vote proposal` transactions and one `execute proposal` transaction. The fee for each `vote proposal` was 0.00197ETH(based on the gas price 20gwei), and for `execute proposal` was 0.00157 ETH(based on the gas price 17gwei). 
The total fee was:  0.00197x2x(17/20)+0.00157 = 0.00491ETH (based on the gas price 17gwei).
The last 30 days average gas price is : 17 gwei
The last 30 days average LIT/ETH is: 0.0004865
The fee for cross chain transfer should be: 0.004919/0.0004865 = 11 LIT
cc @Kailai-Wang

**Comment by Kailai-Wang** [comment]
Thanks @qiuhaiguo I believe we'd always send 3x `voteProposal` and 3x `executeProposal`, but only 2 and 1 execution will succeed, respectively. I believe a small transaction fee will also be charged for the failed execution. Is it considered too?

e.g. successful tx: https://etherscan.io/tx/0x2558dca1e6a7b3c7ebe88dc3c65350b0d418952fe7b0962170c3d9f9d6aacba5
failed tx: https://etherscan.io/tx/0x7167e50c5201a111ae6ff9d08b7c2f2182b68176215a4e930c8acfaec1cbec3a

Btw is 20GWei a good initial setting?

**Comment by qiuhaiguo** [comment]
Thanks Kai for the update. I have made a google sheet to calculate the cross-chain transfer fee, please follow [this link](https://docs.google.com/spreadsheets/d/1fi6y6I_xGXTjG_VRXgQkmIrd5oWKf9DaKt61bFYUjfI/edit#gid=0)

**Comment by Kailai-Wang** [comment]
It's LIVE on Litmus now.
