### ISSUE TITLE
Refactor out the fee transfer in `bridge::transfer_fungible`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#778]
### Context
In the current token bridge implementation we transfer the commission fee from the sender account to treasury using `Currency::transfer`:
https://github.com/litentry/litentry-parachain/blob/5249614eb56efb795274af3b04434f68677e9a7c/pallets/bridge/src/lib.rs#L685

While it works, it can create misleading records in the block explorer. An example: https://litmus.statescan.io/extrinsic/838218-2

Maybe we can consider some alternatives, e.g. `burn` + `deposit_into_existing`
The tests shouldn't be broken.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
I think either @Jinsipang or @zhizming-zhong can take this

**Comment by Kailai-Wang** [comment]
After it's done we should also add integration test for it

**Comment by Kailai-Wang** [comment]
Is this done? @Jinsipang 
Let's use [keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in PR so that the issue can be auto-linked and auto-closed when the PR gets merged

**Comment by Marky-Shi** [comment]
> Is this done? @Jinsipang Let's use [keyword](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests) in PR so that the issue can be auto-linked and auto-closed when the PR gets merged

Yes, this has been completed at the source level, and the tests have all passed

**Comment by Kailai-Wang** [comment]
Thanks, this can be closed now
