### ISSUE TITLE
Staking rollout phase 4 - activate delegation on Litentry

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#799]
Activating delegation (nomination) should allow normal users to stake to specific collators to share the block production reward, things to consider:

- [x] configuration and parameters finalisation 
- [x] documentation about how to use it
- [x] runtime upgrade to enable it

**Comment by jingleizhang** [comment]
This issue was completed last weekend. Let's verify it this week.

**Comment by Kailai-Wang** [comment]
Runtime updated and staking is LIVE now
