### ISSUE TITLE
Research about the logic and code of token issuance of other parachains

### ISSUE THREAD

**Issue by Satoshi-Kusumoto** [litentry/litentry-parachain#80]
To have concrete result like
Genesis 10k token, claim pallet 1k token (minted), bridge module preminted 1k token from genesis...

**Comment by qiuhaiguo** [comment]
Phala as example
1. In Genesis block, they set sudo account and create about 1K Khala for sudo account（https://github.com/paritytech/substrate/blob/master/bin/node-template/node/src/chain_spec.rs#L141）
2. After parachain launch, they use sudo and set_balance function to create Khala token manually
（https://khala.subscan.io/extrinsic/0xd54c824c4f55780d403e5bc4f30bbe3431e75d64e88aeb80e6114db65ccc909c）
3. They will create enough token in the Bridge pool before they remove sudo
