### ISSUE TITLE
Keep track of Weight v1.5 and Weight v2 from Substrate

### ISSUE THREAD

**Issue by BillyWooo** [litentry/litentry-parachain#803]
### Context
New version of Weight will be introduced in new Substrate release. 

Follow this [PR](https://github.com/paritytech/substrate/pull/12138) and forum [discussion](https://forum.polkadot.network/t/weight-v2-discussion-and-updates/227).

### Task
Keep track of new release and update accordingly.

### Acceptance criteria
As usual, CI should pass after the update.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
This issue can be served as the epic and we can add subtasks as bullet points into it (e.g. changes needed to fix the compilation due to v1.5 introduction later).

We might need a sharing session about these too.

**Comment by Marky-Shi** [comment]
The [PR](https://github.com/paritytech/substrate/pull/12322)  that some basic arithmetic operations are impl for weight.
The [PR ](https://github.com/paritytech/substrate/pull/12277)  that add storage size component to weights.
The [PR](https://github.com/paritytech/substrate/pull/12383) that set the max proof size weight on defaults and tests.
The [PR](https://github.com/paritytech/substrate/pull/12183)  that remove ord impl for weight V2 and use comparsion fns instead.
Then we can pay attention to the progress of this [issue](https://github.com/paritytech/polkadot-sdk/issues/256), it basically covers all the progress of weight V2 development.
