### ISSUE TITLE
Rpc node stalled but undetected

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#807]
### Context
@qiuhaiguo tried the token bridge transfer after it's activated on Litmus and it failed.
`transfer_native` extrinsic [succeeded](https://litmus.subscan.io/extrinsic/869235-2) but no tokens were received on ETH.

Checking the bridge contract showed it only got a `voteProposal` from one relayer.

<img width="1461" alt="image" src="https://user-images.githubusercontent.com/7630809/188004784-a7c8ee06-3a5a-43ba-b098-6bd093338efc.png">

However, the relayers were not dead (otherwise we would have got the alerts), and I double-checked it -- they were indeed alive.

The problem was one of our RPC nodes was stuck -- it couldn't sync new blocks at some point: reason unclear (network problems) but this was the first time (that we noticed it happened) since Litmus' launch.

In this case AWS LB won't consider it dead as it still responds to the ping request. However, the relayers couldn't get the latest blocks, instead, they would get the block where the rpc node was stuck and therefore missed the events -- or were not there yet to process it. It can be verified after RPC node was restarted and the relayer start to process the event, unfortunately the proposal expired already and the user couldn't get the tokens on ETH anymore, it needs to be fixed manually.

Things to check/consider:
- check the logs of rpc0 for any hints
- consider how to prevent that from happening next time:
   - monitor the block sync for rpc nodes
   - possible to change the AWS availability check to consider the block sync as well?
   - maybe third-party rpc node hosting and relayers should connect to different rpc endpoints?

Mainly @niteshb3495 needs to look into it

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
added this issue to https://github.com/litentry/litentry-parachain/issues/911

**Comment by Kailai-Wang** [comment]
We can close it for now - it didn't happen again.
