### ISSUE TITLE
Adjust start parameters for integration test

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#81]
Currently our CI test starts two relaychain nodes (alice and bob) and two parachain collators (litentry-collator):

args for collator 0:
`--collator --tmp --parachain-id 1984 --port 40333 --ws-port 9844 --alice --execution native -- --execution wasm --chain ./rococo-local-cfde-real-overseer.json --port 30343 --ws-port 9977`

args for collator 1:
`--collator --tmp --parachain-id 1984 --port 40334 --ws-port 9845 --alice -- --execution native --chain ./rococo-local-cfde-real-overseer.json --port 30344 --ws-port 9978`

IMHO this is suboptimal:

- We would only need 1 collator, as this CI mainly focuses on the functionality of the parachain, not the consensus between parachains. Furthermore, [substrate recommends n + 1 validators with n parachains](https://github.com/substrate-developer-hub/substrate-parachain-template#start-relay-chain). 

   In our case two collators had to be started as otherwise no blocks could be generated because of single-node-network for parachains. However this can be overcome via `force-authoring`.

- execution strategy seems to make less sense. According to https://substrate.dev/docs/en/knowledgebase/advanced/executor, I'd prefer to either use default, or both wasm.

**Comment by chenzongxiong** [comment]
I'm refactoring CI code at this moment. It will be changed a lot. Please don't change before I fixed. 

The startup command should be discussed definitely.  

I prefer to using `--execution wasm`.

**Comment by Kailai-Wang** [comment]
> I'm refactoring CI code at this moment. It will be changed a lot. Please don't change between I fixed.
> 
> The startup command should be discussed definitely.
> 
> I prefer to using `--execution wasm`.

OK then I delay the PR.

**Comment by Satoshi-Kusumoto** [comment]
Then I have the idea to test two node, one with `--execution wasm` and another with `--execution native`
Why not?

**Comment by Kailai-Wang** [comment]
> Then I have the idea to test two node, one with `--execution wasm` and another with `--execution native`
> Why not?

In my original thought:  as we are now only testing the functionality of our pallets and not the consensus between parachain nodes (which should be assured by substrate low level impl).

And if we really want to test it later (due to runtime upgrade for example), do we need to test all combinations considering each parachain starts a relaychain node which could have its own executor strategy?

**Comment by Kailai-Wang** [comment]
Talked with @chenzongxiong , we'd prefer to wrap it up for this issue now and, if we actually need to test multiple nodes with different execution modes, open another issue and perform dedicated commitment there: that's easier for tracking and we know exactly why we make the changes.
