### ISSUE TITLE
Write a JS e2e test for the IMP mock

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#813]
### Context
Follow-up of #765 , we'd like to have a JS e2e test for the mock pallet to:
- test the basic logic of the mock pallet
- demonstrate its usage from the F/E side:
   - how to construct the TrustedCall, encrypt it and send extrinsics
   - how to listen to blocks to retrieve event and decrypt it

The TEE and user keys are hardcoded for testing.
The mock pallet also has the storage to verify if the state change is successful.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Maybe this issue should be handed over to @zTgx

**Comment by jingleizhang** [comment]
We are working on the JS e2e tests for web2&web3, e.g this issue https://github.com/litentry/litentry-parachain/issues/1054.

Should we close this one as well?

**Comment by jingleizhang** [comment]
will close this one
