### ISSUE TITLE
Create a Verify Credential Mock extrinsic

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/litentry-parachain#817]

**Comment by Kailai-Wang** [comment]
Hi @StamfordDigital do you mean a verify_identity mock extrinsic?

**Comment by StamfordDigital** [comment]
Hi @Kailai-Wang, yes that's corrrect. Is this a duplicate ticket? Thanks.

**Comment by Kailai-Wang** [comment]
It's actually done in the [last PR](https://github.com/litentry/litentry-parachain/pull/805/files#diff-397f3a4147435a96c505f8ed92042b7e936c381cfd7884632c03538a2dbc1538R325)

There're still some tweaks required, but I'll do it in another PR which will resolve https://github.com/litentry/litentry-parachain/issues/809

So I think this ticket can be closed
