### ISSUE TITLE
Add third validator to staging parachain deployment

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#82]
In current staging parachain deployment we start:

- 2 validators (relaychain nodes): alice and bob
- 2 parachain collectors.

According to https://github.com/substrate-developer-hub/substrate-parachain-template#start-relay-chain:

> We need n + 1 full validator nodes running on a relay chain to accept n parachain / parathread connections

So we'd need **at least** a third validator.

**Comment by chenzongxiong** [comment]
Please check the startup command in parachain. I think we can assign a validator in parachain node.  See [devops-scripts/issues/1](https://github.com/Litentry-Dark/devops-scripts/issues/1)
Moreover, you can try to add a new validator from poladotjs/app

`validatorManager.registerValidators`

<img width="1691" alt="image" src="https://user-images.githubusercontent.com/8354165/129229442-be9d0af0-74f9-47fe-8b25-17dd267c5c40.png">

**Comment by Kailai-Wang** [comment]
@chenzongxiong 
It should be done now, please have a look at it if it's OK:
https://polkadot.js.org/apps/?rpc=wss://relayer-sg-3.staging.litentry.io#/explorer

At least in alice's logs there're 4 peers now:
```
Aug 20 22:17:42 ip-172-31-28-190 polkadot[421016]: 2021-08-20 22:17:42 ✨ Imported #564902 (0xd792…2339)
Aug 20 22:17:46 ip-172-31-28-190 polkadot[421016]: 2021-08-20 22:17:46 💤 Idle (4 peers), best: #564902 (0xd792…2339), finalized #564899 (0x246e…172e), ⬇ 8.3kiB/s ⬆ 77.8kiB/s
```

**Comment by Kailai-Wang** [comment]
never mind, despite of 4 peers in logs, the third validator seems not to be online => still need to be investigated

**Comment by Kailai-Wang** [comment]
will be completed once #109 is done.
