### ISSUE TITLE
Add dedicated label for devop issues

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#83]
It would be beneficial if we have a dedicated label for devop issues, which don't fit into the existing label-category so well.

Suggestion for the new label: **F7-devop**

We have some devop issues ongoing, e.g.:

https://github.com/litentry/litentry-parachain/issues/78
https://github.com/litentry/litentry-parachain/issues/82

and we might have more in the future as the parachain needs to be more frequently deployed and pratically tested.

**Comment by Satoshi-Kusumoto** [comment]
DONE
