### ISSUE TITLE
Return the encrypted id-graphs when it's updated

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#842]
### Context
proposed by @kaylawangnow, we should return the full encrypted ID-graph when some identity is updated in the ID-graph, e.g. together with the `IdentityVerified` event.

It's mainly for display purposes.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by jingleizhang** [comment]
~~needs:~~

~~- [ ] included in Parachain event, and encrypted by user_shielding_key~~
~~- [ ] to figure out which functionalities should include this feature, e.g, linking verification?~~

**Comment by Kailai-Wang** [comment]
I think `link|unlink|verify_identity` all can cause ID-graphs to change, thus all of them.

This is probably still meaningful even if the trusted port is exposed, where a user signature is required.

**Comment by jingleizhang** [comment]
related issue https://github.com/litentry/litentry-parachain/issues/1010

If we decided to open a trusted RPC port, it's not necessary to include the user's id-graph in Parachain event.

**Comment by Kailai-Wang** [comment]
> related issue [litentry/litentry-parachain#1010](https://github.com/litentry/litentry-parachain/issues/1010)
> 
> If we decided to open a trusted RPC port, it's not necessary to include the user's id-graph in Parachain event.

A second thought leads me to believe it might still be helpful. A trusted query needs user to sign the request while here the id graph is directly returned - better user experience

**Comment by Kailai-Wang** [comment]
closed via #1080
