### ISSUE TITLE
criterions for benchmark pallet inclusion in runtime

### ISSUE THREAD

**Issue by suinuj** [litentry/litentry-parachain#85]
Description
Currently, we have four pallets, frame-system, account-linker, offchain-worker and nft included in parachain runtime. We need to clarify the requirement for benchmark testing and decide if other pallets also should be in the benchmark testing.

Acceptance Criteria
- [x] Investigation of other parachains in lib.rs about benchmark
- [ ] The pallets are chosen and added into the runtime-benchmarks list

**Comment by suinuj** [comment]
link for investigation https://www.notion.so/litentry/benchmark-list-d65aa91dedac4ba4b27835399a1fd62a.
will discuss then decide pallets should be included in runtime benchmark

**Comment by h4n0** [comment]
30min
