### ISSUE TITLE
Research  the differences between running benchmark code with different commands or environment

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#851]
### Context
When adding benchmark code to a paralleled chain project, it was found that the benchmark code that could be passed by using the `cargo test --package pallet-pallet_name -features runtime-benchmarks` command ran an error under litmus runtime, and vice versa. Since they all run the same program with benchmark code, will the results be different because the execution environment is different? This question is still very necessary to explore.

In addition, we also need to ensure that all our pallets can successfully execute the `cargo test --package pallet-pallet_name -features runtime-benchmarks` command.

<img width="1122" alt="image" src="https://user-images.githubusercontent.com/87012234/191882807-5762b489-6f4d-4367-9874-fdea8c4c8ca3.png">

<img width="1037" alt="image" src="https://user-images.githubusercontent.com/87012234/191882893-49854862-0614-434a-b546-84ef2681b9d3.png">

<img width="814" alt="image" src="https://user-images.githubusercontent.com/87012234/191883009-9dc36a3f-7ee5-483c-b9a9-f6ef82751c3b.png">

**Comment by Kailai-Wang** [comment]
Yes this is something we ignored earlier.

When we do `cargo test -p pallet-... --features=runtime-benchmarks` it would also include the `benchmarking` mod and run the tests inside it (implied by `impl_benchmark_test_suite`).

Ideally we'd need to get these working too

**Comment by Marky-Shi** [comment]
In the process of changing the existing benchmark code, it was found that the `cargo test -p pallet-name --features runtime-benchmarks `command check is more stringent, in a sense the benchmark code checked by this command will be more streamlined. After this renovation, the benchmark code will become more standardized.
