### ISSUE TITLE
Wrong weight calculation for `acknowledge_proposal`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#871]
### Context
The current weight computation for `pallet_bridge::acknowledge_proposal` is wrong:
- the weight directive is wrongly written
- we should (almost) **never** edit the generated weights file manually
- do we have reason of using 15, 16, 17 for `make_proposal`? We could have simply used empty vec => it doesn't matter too much 

You can refer to the substrate proxy pallet: https://github.com/paritytech/substrate/blob/241b0d0455453499763d0db0b4ea4188012b372f/frame/proxy/src/lib.rs#L194-L202

Please correct it and rerun the weights for this pallet. 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Marky-Shi** [comment]
Thanks for pointing out my mistake, I will go and fix it

**Comment by Kailai-Wang** [comment]
Thanks, please merge the current PR and open a separate PR for this issue

**Comment by Marky-Shi** [comment]
Regarding this problem, I have fixed the benchmark code in the bridge pallet, and after debugging it locally, I submitted a[ pr](https://github.com/litentry/litentry-parachain/pull/877), hoping that you can review it
