### ISSUE TITLE
The parachain staking benchmark is running for too long

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#887]
### Context
[#Action](https://github.com/litentry/litentry-parachain/actions/runs/3155868677/jobs/5134984739)  When using parachain staking benchmark code to generate a weight file, the run time is too long.

### Task
Modifying the staking pallet staking benchmark code improves the runtime without affecting the weight file generation.

**Comment by Kailai-Wang** [comment]
Related: https://github.com/PureStake/moonbeam/issues/1950

**Comment by Marky-Shi** [comment]
https://github.com/litentry/litentry-parachain/actions/runs/3528580789/jobs/5919401779,  This is the result of using the CLI machine to run it. Unfortunately, it's cost 2 hours. It seems that the step and repeat need to be adjusted.

According to the previous test results on the T40 machine, if the step is adjusted to 30, the entire running process will be shortened to 1 hour. If it is run together with other pallet benchmark codes, it will take 2-3 hours to generate the weight file without counting the build-docker time. .
