### ISSUE TITLE
Investigate claim type and how to pass merkle tree proof to back end

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#89]
@bdmason commented on [Fri Aug 13 2021](https://github.com/litentry/litentry-webapp/issues/274)

Our API types:

```typescript
ApiRx.create({
        provider,
        types: {
          CID: 'Vec<u8>',
          ClassType: {
            _enum: {
              0: 'Simple<u32>',
              1: 'Claim<HashByte32>',
              2: 'Merge<ID, ID, bool>',
            },
          },
          ClassIdOf: 'ClassId',
          Properties: { _set: { _bitLength: 8, Transferable: 1, Burnable: 2 } },
          HashByte32: '[u8; 32]',
        },
      }).subscribe(setApiTemp);
```

Our call (we run `transaction/signAndSend` as normal on this):

```typescript
const transaction = await apiTemp.tx.nft.createClass(
        'CID', // will be IPFS metadata URL
        ['Transferable', 'Burnable'],
        null, // start block
        null, // end block
        1 // claim class type
      );
```

This call successfully lands on the chain - we get the created class event with the class ID. The event loop with `onEvent` is where we can see that even:

```typescript
tx.signAndSend(address, {
      signer: injector.signer,
    }).subscribe((result) => {
      console.log('TRANSACTION EVENT:', JSON.stringify(result));

      result.events.forEach((eventRecord) => {
        onEvent && onEvent(eventRecord.event);
      });
```

The fact that this lands on chain successfully makes me feel that the issue is 1 of 2 things:

1. The front end types are wrong, but the encoding happening within the polkadot API before it hits the chain makes the value appear correct.
2. The back end has an issue and needs to read the merkle proof from somewhere.

As the successful call is using an integer/enum key for class type it makes me think the issue might be parameter/back end based. If it were a hash I'd think it was on the front end and we were simply hashing the wrong thing.

**Comment by bdmason** [comment]
The types posted above are wrong, the API hadn't updated properly, these are the types that work _(ignore the one for merge - it's not tested at all)_

`ClassType: {
            _enum: {
              0: 'u32',
              1: 'HashByte32',
              2: 'Merge<ID, ID, bool>',
            },
          },`

**Comment by bdmason** [comment]
I think I've got the solution:

```typescript
const transaction = await apiTemp.tx.nft.createClass(
        'CID',
        ['Transferable', 'Burnable'],
        null, // start block
        null, // end block
        [1, '648e8db6546cccab368bfd911ddf0823f6d3f334204004131df019202b573ff2'] // claim class type
      );
```

This works too:

```typescript
{
          1: '648e8db6546cccab368bfd911ddf0823f6d3f334204004131df019202b573ff2',
        } // claim class type
```

Could you verify this on the chain? My transaction hash is `0x0c0b426bb72f14e6597db77f51d2d5412de9b11163491ece08902e208f38866f` and the class ID is `3`

For the 2nd transaction the hash is `0x479925a280c2401249bb565ee751aaab8a7e9065f602b069d747a5ecb2c92298` and the created class ID is `4`

**Comment by bdmason** [comment]
I have more info, all based on the following types:

```typescript
ClassType: {
            _enum: {
              1: 'u32', // simple
              2: 'HashByte32', // claim
              3: '<ID, ID, bool>', // merge
            },
          },
```

Sending just `2` fails _(IMPORTANT - I thought this was succeeding before, but realised I had my enum index wrong - I started at 0 instead of 1, so was actually calling simple not claim)_

Sending `[2, 'yourhash']` works

Sending `{ 2: 'yourhash' }` works

[This issue](https://github.com/polkadot-js/api/issues/271) seems to suggest both solutions should be fine... and they do work. When I just sent `2` I got an actual runtime error:

```
Error: 1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `ClassType::Merge.0`" }), desc: "Could not decode `Call::create_class.4`" }), desc: "Could not decode `Call::NFT.0`" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some, Error { cause: Some, Error { cause: Some, Error { cause: None, desc: \"Not enough data to fill buffer\"…
```

This makes a lot more sense - when I thought the integer alone was creating a class successfully it seemed very weird. Now I know that fails and the array and object methods work it's a lot more reassuring.

I have done another test with the correct indexes. My TX hash is `0x3e2429840adea7a3dc4b394d2a10cc971f1bfc553e32fa04ca9d0ecaddd80d2b` and the class ID is `12`. The fake hash I sent as the merkle proof is `648e8db6546cccab368bfd911ddf0823f6d3f334204004131df019202b573ff2`. Please verify this is on chain correctly.

**Comment by h4n0** [comment]
I have a summary workaround here https://www.notion.so/litentry/litentry-js-c7757921a40a4bd19c184d1c95505cd2.

This issue is however valuable as Ben wrote the usage of enum with param with polkadot js api. 

As the issue is solved, I will close this ticket now.
