### ISSUE TITLE
Explore the bounty workflow

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#896]
### Context
We are looking for externals to help us with designated tasks.
We'd like to do it via bounties.

Task: explore the whole workflow: creation, curation, tracking, distribution 

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/Parachain-How-to-use-pallet_bounty-102454bb599f46f6b50c563810e5546f

**Comment by wangminqi** [comment]
this one is the regular pallet_treasury sending reward. I think it is more suitable.
https://www.notion.so/web3builders/Parachain-How-to-use-pallet_treasury-for-volunteer-employee-b2369f886dba4238bccd7f99ff8bf73b

**Comment by jingleizhang** [comment]
The research is completed. This issue should be closed now.
