### ISSUE TITLE
[CI] Establish parallel jobs on CI to reduce the running time

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#9]
Currently CI takes too long to execute each build & test (~2.5h on github runner, ~ 1h on aws)

We may benefit from parallel jobs by refactoring workflow of GitHub Actions to reduce the running time.

**Comment by Kailai-Wang** [comment]
Probably deprecated?

**Comment by Kailai-Wang** [comment]
I close it as it's too old and probably not relevant anymore.
