### ISSUE TITLE
Explore the non-stopping DB backup

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#905]
### Context
We are constantly looking for ways to improve the whole backup and syncing experience, especially for the (incoming) newly joined collators.

Please read the following conversation and do the research to be able to answer these questions:
- can we achieve the non-stopping DB backup using EBS snapshots too? What's the cost for us?
- is "warp sync" a valid option for the new collators? Ideally we should play around with it. Current setting is always "full sync" I believe.
   extra info for this: https://substrate.stackexchange.com/questions/334/what-kinds-of-sync-mechanisms-does-substrate-implement/406
 
Please leave the research results in a notion doc and/or hold a sharing session.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/7630809/196807897-f16f5fd6-f910-4e6b-86ba-fd066bebe882.png">

<img width="926" alt="image" src="https://user-images.githubusercontent.com/7630809/196808108-f2a515a8-e96c-4acb-9b55-63c7184d0e2c.png">

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by niteshb3495** [comment]
Duplicate: https://github.com/litentry/litentry-parachain/issues/737
