### ISSUE TITLE
monitors and statistic reports for bi-direction Bridge

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#911]
### Monitors

- [x] sending sms/email/etc alerts if one of the bridge nodes was down
- [x] sending alerts if one of the transactions is stuck because of the low gas price
- [x] sending alerts if there are some big transactions ongoing (e.g, more than 1000LIT in one transaction)
- [x] collect more logs to CloudWatch and S3
- [x] collect ETH contract on-going and statistics data from theGraph

### Reports

- [x] Daily / Weekly / Monthly reports
- [x] metrics:
    - [x] transaction amount
    - [x] transaction volume
    - [x] amount of addresses that have interacted with the Bridge contract

**Comment by Kailai-Wang** [comment]
We have two ways of doing statistics:

- indexing on-chain events/extrinsics 
- using Prometheus provided by chainbridge

Either way we probably need a F/E, or at least a dashboard.

**Comment by Kailai-Wang** [comment]
I changed the priority to `High` as I saw the bridge was used quite often, maybe we should prioritize this ticket a bit.

As mentioned it would probably need some scripts/dashboard from F/E too, so we'd need @Verin1005 's help here

**Comment by jingleizhang** [comment]
The monitors&statistics for bridge is very necessary. 

Let's complete the setup of TEE staging env within this week https://github.com/litentry/tee-worker/issues/122, and start this ticket with top priority in the beginning of next week.

**Comment by jingleizhang** [comment]
one more monitoring task: https://github.com/litentry/litentry-parachain/issues/807

**Comment by jingleizhang** [comment]
The dashboard is live, close this issue.
