### ISSUE TITLE
Finalise the parameters in `parachainStaking`

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#921]
Especially the following parameters, are they still up-to-date?

```
	pub const MinCollatorStk: Balance = 50 * DOLLARS;
	pub const MinCandidateStk: Balance = 50 * DOLLARS;
	pub const MinDelegation: Balance = 50 * DOLLARS;
	pub const MinDelegatorStk: Balance = 50 * DOLLARS;
```

**Comment by qiuhaiguo** [comment]
Parameters | Value | Description
-- | -- | --
Session duration | 1800 blocks (6 hours) |  a specific number of blocks around which staking actions are enforced. 
Minimum staking per candidate | 50 LIT | the minimum amount of tokens to delegate candidates once a user is in the set of delegators
Maximum delegators per candidate | 1000 | the maximum number of delegators, by staked amount, that a candidate can have which are eligible to receive staking rewards
Maximum delegations | 100 | the maximum number of candidates a delegator can delegate
Reward payout delay | 2 sessions (12 hours) | How long until you get the staking rewards
Add or increase delegation | takes effect in the next round (funds are withdrawn immediately) | How long until your funds will take effect
Decrease delegation delay | 28 sessions (7 days) | How long until your funds will be transferrable after unbonding
Revoke delegations delay | 28 sessions (7 days) | How long until your funds will be transferrable after unbonding
Leave delegators delay | 28 sessions (7 days) | How long until your funds will be transferrable after unbonding

**Comment by wangminqi** [comment]
Recent discussion with @qiuhaiguo 

Minimum staking per candidate changes from 50 LIT to 5000 LIT.
collator commission rate changes from 0% to 33% (In order to maintain 0.5% out inflation, where 1.5% is global inflation target).

We still need to manually set global inflation rate to 1.5% (maybe collator commission also need to manually setup).
