### ISSUE TITLE
Restructure the gitbook doc

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#923]
### Context
The current [gitbook documentation](https://docs.litentry.com/) is a **mess**.

It's neither the best structured nor well maintained. I've started to revamp it a bit regarding the token bridge and collator operations but that's not enough for the whole hierarchical structure.

We need to think on how to better organise the chapters.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
Can we consider this issue as done? @cryptoade1

**Comment by cryptoade1** [comment]
Yes.
