### ISSUE TITLE
Staking dashboard and UI

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#927]
### Context

As part of the staking rollout, we'd like to have something tangible for the users.

It should basically contain two parts:

1. dashboard:  provides the overview for:
   - collators
   - backed up staking statistics: total amount and for each collator
   - chain state: round information, delay settings, commission, inflation config, minimum stake requirements etc
   - ideally with APY
  
2. UI: provides the interface for the users to interact with the parachain, including:
    - join/leave as collator candidates
    - join/leave as delegations (staking)
    - reward distribution/claim
    - bond more/less
    - personal staking overview display

@wangminqi please clarify internally if these requirements are feasible. Maybe you can add if I miss anything, as you guys have the best experience with it.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by wangminqi** [comment]
Web3Go team provided already.
https://app.web3go.xyz/#/LitentryMainnetStaking
