### ISSUE TITLE
Add token bridge commission chapter to gitbook

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#929]
### Context
We often got a question from the community about how we ended up calculating the **parachain => Ethereum** token bridge commission fee (16LIT).

Let's add a chapter in gitbook to explain that.

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
What is the status of this issue? It's been 3 weeks and we keep getting questions from the community how the fee is calculated :(

**Comment by cryptoade1** [comment]
The documentation is already in notion but needs to be reviewed by Quihai. Once reviewed and approved, it will be published tomorrow. I notified him earlier but he doesn't seem to be online today.

**Comment by Kailai-Wang** [comment]
> The documentation is already in notion but needs to be reviewed by Quihai. Once reviewed and approved, it will be published tomorrow. I notified him earlier but he doesn't seem to be online today.

thanks for the heads-up!

**Comment by Kailai-Wang** [comment]
> The documentation is already in notion but needs to be reviewed by Quihai. Once reviewed and approved, it will be published tomorrow. I notified him earlier but he doesn't seem to be online today.

thanks for the heads-up!

**Comment by cryptoade1** [comment]
> > The documentation is already in notion but needs to be reviewed by Quihai. Once reviewed and approved, it will be published tomorrow. I notified him earlier but he doesn't seem to be online today.
> 
> thanks for the heads-up!

You're welcome

**Comment by jingleizhang** [comment]
done
