### ISSUE TITLE
Open xcm channel to Bifrost

### ISSUE THREAD

**Issue by jingleizhang** [litentry/litentry-parachain#941]

**Comment by Kailai-Wang** [comment]
Please update [this doc](https://www.notion.so/web3builders/HRMP-XCM-channels-6d170f7c18fb4c7dad6dac2341c521a1) later too, thanks! 🙌

**Comment by wangminqi** [comment]
https://www.notion.so/web3builders/2022-08-29-Litmus-Bifrost-HRMP-Channel-Opening-104f7a0c98e5476386c7e0419f7c1aa0

**Comment by Kailai-Wang** [comment]
Waiting for council votes

**Comment by Kailai-Wang** [comment]
Bifrost's request should be accepted now.
