### ISSUE TITLE
Runtime upgrade test research

### ISSUE THREAD

**Issue by h4n0** [litentry/litentry-parachain#95]
- [x] try-runtime research and doc @wangminqi https://www.crowdcast.io/e/substrate-seminar/41

**Comment by wangminqi** [comment]
https://www.notion.so/litentry/49f35175ad41458fa1926f352b51485f?v=cbde74ac6a64488b833400758b608dda&p=d6cdba23c38045e8887d009b8930f4bc
try-runtime doc here for reference
