### ISSUE TITLE
XCM front_end adjust

### ISSUE THREAD

**Issue by wangminqi** [litentry/litentry-parachain#954]
ORML users: This PR will make a transaction_version change. 
https://github.com/open-web3-stack/open-runtime-module-library/pull/841

The destWeight is no longer needed as a parameter.

Once the new version applied. The document should be updated.
https://www.notion.so/web3builders/Parachain-XCM-front_end-document-473e99ca460a44f3bfa30982ce762308

**Comment by Kailai-Wang** [comment]
Is this done?

**Comment by jingleizhang** [comment]
cc @wangminqi

**Comment by wangminqi** [comment]
https://github.com/litentry/litentry-app/issues/1382
