### ISSUE TITLE
Replace `aes-gcm` with `ring` for AES encryption

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#963]
### Context
companion of https://github.com/litentry/tee-worker/issues/144

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
About the `ring` crate for wasm:

It failed to compile because `ring 0.16.20`implicitly [depends on](https://github.com/briansmith/ring/blob/b%2F0.16/Cargo.toml#L317) `web-sys` which has std dep - even for `default-features = false`
<img width="1062" alt="image" src="https://user-images.githubusercontent.com/7630809/203651002-17e4f341-5c09-451e-95ae-30d6e54cd4d0.png">

Btw the crate version `0.16.20` is rather old as they haven't updated the crate version for a while.

However, trying to switch to the up-to-date version won't work either, even though web-sys is removed:
```
ring = { git = "https://github.com/briansmith/ring", default-features = false, features = [ "alloc", "wasm32_unknown_unknown_js" ] }
```
as it's blocked by `getrandom` std (similar problem as above)

Solutions:
1. keep using `aes-gcm`, as it's for mock anyway
2. switch to patched version of `ring`, e.g. [integritee-branch](https://github.com/integritee-network/ring/commit/f663efa6478785a4a74d9de2684034ea7cabf29f)
3. switch to `ring-oxus`, see https://github.com/integritee-network/pallets/issues/115

**Comment by BillyWooo** [comment]
I would suggest we keep using `aes-gcm` for the moment to save the bandwidth for other more important tasks. And wait for INTEGRITEE's next movement. If necessary, we can propose our input to them for decision making about `ring`.

**Comment by Kailai-Wang** [comment]
OK let's keep `aes-gcm`. We need to add a comment sometime to explain why we didn't switch to `ring`. Integritee has more knowledge about it, I don't think they need any suggestion for now :/

**Comment by Kailai-Wang** [comment]
closing it now, nothing to do
