### ISSUE TITLE
Add Governance V2 for litentry?

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#972]
### Context
As described in the https://github.com/paritytech/substrate/pull/11649 , start governance v2 on kusama from 0.9.31, reduce the function of pallet-democracy, use referenda and other pallets instead, this needs to be discussed, whether it is necessary to implement governance v2 in litmus?

BTW, other parachain team governance v2 impl:
moonbeam impl https://github.com/PureStake/moonbeam/commit/19e6628be3ca9e76f36f0eb82eec9c0c2492d27a#diff-987ef9c021d8b990dd71100664289db7987e73317f9959a9c5d541c438d1a513

---
:heavy_check_mark: Please set appropriate **labels** and **assignees** if applicable.

**Comment by Kailai-Wang** [comment]
The moonbeam's impl is only for moonbase. I believe it would still take a while until most parachains switch to gov2.0 (by "a while" I mean maybe a few months), and it's not a must, we could keep using v1 as long as we are happy with it.

It's good that we keep an eye on it, but it's not high prior I'd say.

**Comment by Marky-Shi** [comment]
Yeah, I'll keep an eye on this.
