### ISSUE TITLE
Research run parachain staking benchmark args

### ISSUE THREAD

**Issue by Marky-Shi** [litentry/litentry-parachain#975]
### Context
Research run parachain staking benchmark args  related [https://app.[web3go](https://app.web3go.xyz/#/LitentryMainnetStaking).xyz/#/LitentryMainnetStaking](https://app.web3go.xyz/#/)https://app.[web3go](https://app.web3go.xyz/#/).xyz/#/

**Comment by Kailai-Wang** [comment]
The link is broken 😢 and we'd need more context why a dashboard is related to _benchmarking args_ I guess ..

**Comment by Marky-Shi** [comment]
> The link is broken 😢 and we'd need more context why a dashboard is related to _benchmarking args_ I guess ..

Related https://github.com/litentry/litentry-parachain/issues/887#issuecomment-1324573084, I want to investigate the parachain with staking, the parameters of the benchmark they set, and then choose a parameter with a short running time and relatively correct results. The link mentioned above is web3go's dashboard.

**Comment by Marky-Shi** [comment]
This is the parachain with staking on polkadot I counted and the parameters they set benchmark. Through this table, we can give a reference parameter for running our project staking benchmark.
https://www.notion.so/web3builders/parachain-staking-aa284cb82de643adab279d853f1f6957
