### ISSUE TITLE
[identityManagement] Support generating new challenge codes for non-verified Identities.

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#981]
### Context
Pallet: identityManagement[Mock] 

Consider the following scenario
1. A user request `identityManagement.linkIdentity('Twitter', 'my-handle')` -> `ChallengeCodeGenerated` event is emitted.
1. User request again `identityManagement.linkIdentity('Twitter', 'my-handle')`.

**Received:**
The transaction fails with `IdentityAlreadyExist`.

**Desired:**
On point 2, generate a new challenge code. i.e., a `ChallengeCodeGenerated` event is emitted.

## How this useful

- Better Developer Experience: It makes testing easier as you can re-use the same `web_type` and `handle` to get the same results while not minding spending tokens.
- Better User Experience: Users won't need to pay fees for `unlinkIdentity` in case they lose their challengeCode, and retrieving through an indexer is not an option for them.
- Better Consumer Experience: as a dApp developer, I would like to leave ChallengeCodes retrieval from an archive node for later.

**Comment by Kailai-Wang** [comment]
closed via #1074
