### ISSUE TITLE
[identityManagement] `linkIdentity` method name is misleading

### ISSUE THREAD

**Issue by jonalvarezz** [litentry/litentry-parachain#982]
Proposal: replace `linkIdentity` with `requestIdentityLink`.

### Context

As a dApp developer, I would like to have clearer method names.

The practical purpose of `linkIdentity` is to generate a challenge code. An identity is not linked for real until `verifyIdentity` succeeds.

**Comment by Kailai-Wang** [comment]
> An identity is not linked for real until verifyIdentity succeeds.

`linkIdentity` does get your identity linked, it's just unverified 😂 In this sense the name is correctly formulated.
Maybe we have to document somewhere the difference between `linked` and `verified`.

Your thoughts? @jingleizhang @zhizming-zhong

**Comment by jonalvarezz** [comment]
> linkIdentity does get your identity linked, it's just unverified

Technically it is, but confusing in practice. Is there any purpose of an un-verified identity? 

Think of the Identity Hub: "link your identity" would technically not be accurate as you need to link and verify. IMHO the term link identity should be a synonym for a verified identity and thus I would like our pallet to reflect this narrative.

**Comment by Kailai-Wang** [comment]
> > linkIdentity does get your identity linked, it's just unverified
> 
> Technically it is, but confusing in practice. Is there any purpose of an un-verified identity?
> 
> Think of the Identity Hub: "link your identity" would technically not be accurate as you need to link and verify. IMHO the term link identity should be a synonym for a verified identity and thus I would like our pallet to reflect this narrative.

There _was_ a use case where we want to display all unverified usecases, but it's probably irrelevant now.
I'm OK if we can find better names for it.

**Comment by BillyWooo** [comment]
> > > linkIdentity does get your identity linked, it's just unverified
> > 
> > 
> > Technically it is, but confusing in practice. Is there any purpose of an un-verified identity?
> > Think of the Identity Hub: "link your identity" would technically not be accurate as you need to link and verify. IMHO the term link identity should be a synonym for a verified identity and thus I would like our pallet to reflect this narrative.
> 
> There _was_ a use case where we want to display all unverified usecases, but it's probably irrelevant now. I'm OK if we can find better names for it.

If such use case `display all unverified but linked identity` doesn't exist any more, I would recommend merge current `link` and `verify` together. So it would be only:
- linkIdentity, means everything is done (register account, verify whatever needs to be verified, etc. )
- unlinkIdentity, means remove everything we can (unregister account, etc. )

If the use case still exists, how about: 
- applyLinking
- verifyLinking
- removeLinking

**Comment by jingleizhang** [comment]
The `request` or `apply` is indeed more understandable and accurate to users, because the identity in this step is unverified, whether the `display all unverified` use case exists or not. 

I'm fine if we change the name of 'link' to `request`.

**Comment by ziming-zung** [comment]
I think the practical purpose of `linkIdentity` is to create an un-verified identity on tee(or link identity with substrate account), not only generate a challenge code. 
Names with an **identity** suffix should be clearer.
So I personally prefer: `CreateIdentity` and `VerifyIdentity` 😂

**Comment by Kailai-Wang** [comment]
I like `create` 😂 

So how does this sound? @jonalvarezz 
| old  | new |
| ------------- | ------------- |
| `link_identity`  | `create_identity`  |
| `unlink_identity`  | `remove_identity`  |
| `verify_identity` | `verify_identity` |

**Comment by jonalvarezz** [comment]
It sounds good to me too :)

**Comment by Kailai-Wang** [comment]
Done via #1052
