### ISSUE TITLE
Can't reconnect to the parentchain once disconnected

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/litentry-parachain#997]
I assume this is a different problem other than litentry/litentry-parachain#999, once the worker node lost connection with the parentchain (e.g. due to an unstable network), it can't reconnect.

Maybe related: https://github.com/integritee-network/worker/issues/813

**Comment by ziming-zung** [comment]
Waiting for the PR https://github.com/scs/substrate-api-client/pull/377 to be completed

**Comment by ziming-zung** [comment]
related to https://github.com/scs/substrate-api-client/issues/391
